### ISSUE TITLE
App is requesting gallery access permission after that i already chose an image from the gallery IOS

### ISSUE THREAD

**Issue by ghost** [react-native-image-picker/react-native-image-picker#1187]
# Bug

Library version: 1.1.0
React-Native version: 0.60.5
Xcode version: 11.0
## Steps To Reproduce

1.Install Library
2.Pod Install
3.Provide info.plist permissions
...

Describe what you expected to happen:

1.Request Permission before displaying the photos gallery

## Reproducible sample code

    ImagePicker.showImagePicker(response => {
      if (response.didCancel) {
        Alert.alert('Action cancelled!');
      } else {
        const { data: b64Content, type: fileType, fileName: name, fileSize: size } = response;
        const b64 = `data:${fileType};base64,${b64Content}`;
        const fileExtension = String(fileType).substr(String(fileType).indexOf('/') + 1);

        const imagePicked = {
          id: ID,
          category: activeCategory,
          requiredDocuments: requiredDocs,
          imageExt: fileExtension,
          base64: b64,
          name,
          type: fileType,
          size,
        };
        if (images.length === 0) {
          setImages([...images, imagePicked]);
          return;
        }
      }
    });

**Comment by Frank1234** [comment]
And there is actually no permission needed on iOS. So why does the library ask for it?

**Comment by JulianoMajally** [comment]
@Frank1234  There is definitely permissions for the user to accept whether he grant access for the app to the Gallery or not (on IOS and Android).

**Comment by MamyChow** [comment]
+1 Same issue, i can load photo even if i don't give access to the app. (React-native: 0.61.1, image-picker:1.1.0)

**Comment by danielfein** [comment]
+1 here too. Same as MamyChow, loads photo as if access were granted, then asks for access.

**Comment by guliash** [comment]
Reproducible demo https://github.com/guliash/ImagePickerPermissionBug
Everything is fine on 454fff34df11a5c99eb053c3ea515c820d35bddc. So bug was added somewhere after that commit.
iOS 11.4, 12.1. Have not checked other iOS versions.
RN 0.60.6, 0.61.2. Have not checked other RN versions.
react-native-image-picker 1.1.0. Previous versions are fine.

**Comment by isalvador-ogun-io** [comment]
Same thing here. How could we solve this?

**Comment by Jazqa** [comment]
#1159 assumes an image could be used without a permission, thus skipping the permission check before opening the ImagePicker. However, if built with the newest iOS SDK the platform prompts for the permission after an image is selected.

When built with the newest SDK **the system will open the permission prompt** on iOS 12, but the image **can be used without the permission**.  On iOS 13 however, the App becomes unresponsive after declining the prompt.

I assume there have been changes related to this on the newest iOS and iOS SDK versions and the image can not be used without a permission, making #1159 redundant.

**Comment by AliUZAR** [comment]
Without permission request image picker cannot select image or video. Need to request permission first please fix this issue.

**Comment by namlee0005** [comment]
I still couldn't find a solution. Help me

**Comment by AliUZAR** [comment]
> I still couldn't find a solution. Help me

I used react-native-permissions to fix my issue. When i open application i got all permissions that i will use in app.

**Comment by Jazqa** [comment]
> I still couldn't find a solution. Help me

Drop the version to 1.0.1

**Comment by XingtianXin** [comment]
I'm using react-native 0.59.0 verion, and react-native-image-picker 0.28.0 .
we can't drop the version to 1.0.1

> > I still couldn't find a solution. Help me
> 
> Drop the version to 1.0.1

thank you
I'm using react-native 0.59.0 verion, and react-native-image-picker 0.28.0 .
we can't drop the version to 1.0.1

**Comment by bobjflong** [comment]
Mentioned above, but there is a workaround for this: requesting permission (`PERMISSIONS.IOS.PHOTO_LIBRARY`) explicitly with [`react-native-permissions`](https://github.com/react-native-community/react-native-permissions) before attempting to open the image picker. This seems to be working well for us.

Without this workaround, the library seems to callback with some sort of image response before the user has granted permission. This image doesn't have a `fileName` weirdly, and I haven't successfully read the image data. I'm confused about what's happening there.

**Comment by zach-luman** [comment]
No solution yet?

**Comment by Achilles718611** [comment]
I got the same error.
I use react-native-image-picker 1.1.0
After I select imge and image loaded, it asks permission.

**Comment by ravirajn22** [comment]
Version 2.x.x is not longer supported, please upgrade to 3.x.x

I hope the issue is solved, create new issue with details I am happy to fix it.
