### ISSUE TITLE
[Android] Image saves in gallery whenever launch image library

### ISSUE THREAD

**Issue by MohamadKh75** [react-native-image-picker/react-native-image-picker#1315]
# Question

Hey

I'm not sure if this is a feature that can be turned off or a bug!

Whenever I use `ImagePicker.launchImageLibrary()` and pick the image, it would duplicate (so I have 2 of that image in my gallery!

My options:
```js
const options = {
  title: 'لطفا انتخاب کنید:',
  cancelButtonTitle: 'لغو',
  takePhotoButtonTitle: 'دوربین',
  chooseFromLibraryButtonTitle: 'انتخاب از گالری',
  cameraType: 'back',
  mediaType: 'photo',
  maxWidth: 1280,
  maxHeight: 720,
  quality: 1,
  noData: true,
  storageOptions: {
    skipBackup: true
  },
  permissionDenied: {
    title: 'عدم دسترسی',
    text: 'لطفا دسترسی دوربین برای برنامه را از بخش تنظیمات فعال کنید',
    reTryTitle: 'تنظیمات',
    okTitle: 'بعدا'
  }
};
```

**Comment by MohamadKh75** [comment]
Any idea @janicduplessis

**Comment by raajnadar** [comment]
`storageOptions.path` check this api. Go through others also.

https://github.com/react-native-community/react-native-image-picker/blob/master/docs/Reference.md

**Comment by MohamadKh75** [comment]
> `storageOptions.path` check this api. Go through others also.
> 
> https://github.com/react-native-community/react-native-image-picker/blob/master/docs/Reference.md

The path will save the images in some other path!
The problem is whenever i select an image from gallery, it will create a duplicate of it 🤔

**Comment by raajnadar** [comment]
I found no option to disable it even I want to disable it. Maybe someone should send PR to fix this.

**Comment by MohamadKh75** [comment]
cc @Johan-dutoit @janicduplessis 
Please, any idea? It's a bug or can be turned off?

**Comment by callmeyan** [comment]
You can try remove storageOptions from options

**Comment by MohamadKh75** [comment]
> You can try remove storageOptions from options

It's just `skipBackup: true`

**Comment by MohamadKh75** [comment]
Ping @janicduplessis

**Comment by benchenchuang** [comment]
I think you can try 
storageOptions: { 
        skipBackup: true, 
        privateDirectory:false
    }

**Comment by marcoavazquez** [comment]
Could you solve this? I dont know if is the same problem...
I remove storageOptions but the picture is still saved in the camera roll, I tried to delete it manually but the path/uri that i get from response object is not the same.

**Comment by MohamadKh75** [comment]
> Could you solve this? I dont know if is the same problem...
> I remove storageOptions but the picture is still saved in the camera roll, I tried to delete it manually but the path/uri that i get from response object is not the same.
> I only need the base64 data

Unfortunately no :expressionless:

**Comment by ravirajn22** [comment]
If possible can you migrate to using version 3.0.0-vnext.1 https://github.com/react-native-image-picker/react-native-image-picker/releases/tag/v3.0.0-vnext.1

Check if your issue is solved.
Check 3.x.x docs for installation and API changes.
