### ISSUE TITLE
MediaType 'mixed' not working properly on android

### ISSUE THREAD

**Issue by sanborN93** [react-native-image-picker/react-native-image-picker#1339]
# Bug

## Environment info
Android API 28, Android API 27

`react-native info` output:

React Native Environment Info:
    System:
      OS: macOS 10.15.3
      CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
      Memory: 21.18 GB / 64.00 GB
      Shell: 5.7.1 - /bin/zsh
    Binaries:
      Node: 10.18.1 - /usr/local/opt/node@10/bin/node
      Yarn: 1.22.0 - /usr/local/bin/yarn
      npm: 6.13.4 - /usr/local/opt/node@10/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    IDEs:
      Xcode: 11.4/11E146 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.9 => 0.59.9
    npmGlobalPackages:
      react-native-cli: 2.0.1

Library version: NEWEST

## Steps To Reproduce

1. integrate Image picker
2. call ImagePicker.launchImageLibrary()
3. mediaType: 'mixed
4. Only showing photos instead of mixed content
...

Describe what you expected to happen:

1. Instead of showing just photos there has to be mixed content

**Comment by omerman** [comment]
I experience the same issue :(

**Comment by enigmablue** [comment]
I have the same issue. 

But its only happening on select phones. My Oneplus A5000. Works fine on my Samsungs.
The mediaType: Video on its own works fine. Photo and Video option is OK but Mixed Media is not. 

Any suggestioons from anyone?

**Comment by stefanplazic** [comment]
I also have the same problem. Did anyone find the solution?

**Comment by Andrei9889** [comment]
Still have the same problem

**Comment by enigmablue** [comment]
i studied this deeper and found that the code that is in this package dosen't work for all Android API versions.
  libraryIntent.setType("image/* video/*");

I had to switch to https://github.com/ivpusic/react-native-image-crop-picker which had the updated way of doing it.

![image](https://user-images.githubusercontent.com/35584085/86611950-f78d4980-bfe1-11ea-992c-202c1320e90b.png)

**Comment by tastafur** [comment]
i have a huawei mate 10 pro and not work, How do we fix this to make it compatible with more phones?

**Comment by walterdl** [comment]
Same problem over here using android 10, react-native 0.63.0 and react-native-image-picker ^2.3.3.

The modification showed by @hannojg fixed the issue for me but now I have this other issue: https://github.com/react-native-community/react-native-image-picker/issues/1427 😞

**Comment by remstos** [comment]
Still having the issue here, seems like some people have a solution and forks, can someone submit a PR? 🙏

**Comment by enigmablue** [comment]
@Johan-dutoit @ravirajn22 wondering if you could check this? videos / images are not being picked up in some phones

**Comment by Johan-dutoit** [comment]
Mixed is not supported in 3.x.x (yet...) and 2.x.x is no longer supported.
