### ISSUE TITLE
launchCamera is always prompting for WRITE_EXTERNAL_STORAGE despite storageOptions.privateDirectory

### ISSUE THREAD

**Issue by mattijsf** [react-native-image-picker/react-native-image-picker#1342]
# Bug

The `launchCamera` feature always requires `WRITE_EXTERNAL_STORAGE` permission on Android. However when using `storageOptions.privateDirectory` this permission is actually not needed on Android 4.4 and higher.

I believe that when `launchCamera()` is used with `storageOptions.privateDirectory` on Android 4.4 or later it should be able to function without the `WRITE_EXTERNAL_STORAGE` permission being present in the AndroidManifest.xml.

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 1.28 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.18.0 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 25, 26, 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.0, 29.0.0, 29.0.0, 29.0.2
      System Images: android-21 | Intel x86 Atom_64, android-21 | Google APIs Intel x86 Atom_64, android-22 | Intel x86 Atom_64, android-24 | Intel x86 Atom, android-24 | Google Play Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom_64
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    create-react-native-module: 0.16.0
    react-native-cli: 2.0.1
    react-native-compass-heading: 1.0.0
```

Library version: 2.3.1

## Steps To Reproduce

- Use an Android 4.4 emulator / device:
- Don't add the WRITE_EXTERNAL_STORAGE to AndroidManifest
- Use the following snippet to open the image picker:

```js
  ImagePicker.launchCamera(
    {
      quality: 0.75,
      mediaType: "photo",
      storageOptions: {
        privateDirectory: true,
      },
    },
    (response: ImagePickerResponse) => {
      console.log(response)
    }
  )
```

- When `WRITE_EXTERNAL_STORAGE` is present in AndroidManifest.xml: The library will now prompt for this permission.

- When `WRITE_EXTERNAL_STORAGE` is absent from the AndroidManifest.xml:  It will raise an error:
    > Couldn't get file path for photo

Describe what you expected to happen:

Since this is Android 4.4 and I configured the library to make use of the `privateDirectory` I expected the library to just open the camera and take a picture and provide the result to the app. Only prompting for camera permission, not the storage permission.

## Reproducible sample code

See above.

**Comment by mattijsf** [comment]
Not stale. PR #1343 is available to fix this.

**Comment by mattijsf** [comment]
Definitely not stale!

**Comment by iagormoraes** [comment]
Just did a [PR](https://github.com/react-native-image-picker/react-native-image-picker/pull/1439) with the fixes, for the moment you can add in your package.json the following:

```
"react-native-image-picker": "https://github.com/iagormoraes/react-native-image-picker",
```

**Comment by ravirajn22** [comment]
Please migrate to using version 3.x.x https://github.com/react-native-image-picker/react-native-image-picker/releases

Check 3.x.x docs for installation and API changes.
Post if you have any issue
