### ISSUE TITLE
Android upload img get Network request failed,

### ISSUE THREAD

**Issue by ceressteven** [react-native-image-picker/react-native-image-picker#1344]
React Native: 0.62.2
react-native-image-picker:2.3.1,
this erro only got with android ,and at the android studio debug,i got this info:
Stop reading file since a wrong offset may cause an infinite loop: 0

**Comment by the-white-tiger** [comment]
going through the same issue.

**Comment by cyber-claws** [comment]
This might not be the same problem but I was getting the same issue and managed to fix it but sending the `uri` instead of the `data` in my `multipartformdata`

```javaascript
const formData = new FormData();
formData.append('file', {
      uri: responce.uri,
      type: 'image/jpeg',
      name: responce.fileName,
});
```

How are you posting the image?

**Comment by dimitarnestorov** [comment]
https://github.com/react-native-community/react-native-image-picker/issues/1361#issuecomment-623071017:
> Sorry the problem was in react-native 0.62 .
> This solved my problem -
> [facebook/react-native#28551 (comment)](https://github.com/facebook/react-native/issues/28551#issuecomment-611085378)

**Comment by ebhdeveloper** [comment]
upgrade flipper 
FLIPPER_VERSION=0.41.0

**Comment by tientruongvan1995** [comment]
> upgrade flipper
> FLIPPER_VERSION=0.41.0

agree, I updated Flipper version and latest react-native-image-picker library then everything works fine
