### ISSUE TITLE
App restart after capture image from camera

### ISSUE THREAD

**Issue by atifaziz1** [react-native-image-picker/react-native-image-picker#1382]
### Description

Application is restarting after capture image from camera

### How to repeat issue and example
```
const options = {
      quality: 0.6,
      isVertical: true,
      originalRotation: 0,
      title: '',
      storageOptions: {
        skipBackup: true,
        path: 'images',
      },
      cancelButtonTitle: 'cancel',
      takePhotoButtonTitle: 'Camera',
      chooseFromLibraryButtonTitle: 'Select from Gallery',
      mediaType: 'photo',
    };

ImagePicker.showImagePicker(options, response => {
      // console.log('Response = ', response);

      if (response.didCancel) {
        console.log('User cancelled image picker');
      } else if (response.error) {
        console.log('ImagePicker Error: ', response.error);
      } else if (response.customButton) {
        console.log('User tapped custom button: ', response.customButton);``
      } else {
        console.log('i am in else', response.uri);
        // You can also display the image using data:
        const source = { uri: 'data:image/jpeg;base64,' + response.data };

        this.setState({
          avatarSource: source,
        });
      }
    });

```

### Additional Information

* React Native version: 0.61.5
* Platform: Android (5.0.1)
* Development Operating System: Macbook

**Comment by Lyd1223** [comment]
same as you

**Comment by lucasluca** [comment]
same here

**Comment by ManigandanRaamanathan** [comment]
same here, any solution @atifaziz1

**Comment by yorickshan** [comment]
same here

**Comment by Lorengamboa** [comment]
same here, but in my case its not always

**Comment by atifaziz1** [comment]
> same here, any solution @atifaziz1

Not yet. Still waiting for solution.

**Comment by Lorengamboa** [comment]
are this module still being under maintenance?

**Comment by PatricioBedregal** [comment]
Same

**Comment by wengkitt969696** [comment]
Same here, but only happen on some android devices

**Comment by TestProject-Tech** [comment]
Have you find solution guys?

**Comment by wengkitt969696** [comment]
I think the developer team is fixing the issue here [https://github.com/expo/expo/pull/9349](url)

**Comment by JaioSkura** [comment]
Hi! same here. Any fix?

**Comment by hienhodeveloper** [comment]
Any fix here? On android 10, just add android:requestLegacyExternalStorage="true" to <Application ... in Manifest file

**Comment by scrapecoder** [comment]
Facing the same issue. Any updates?

**Comment by McFlyssss** [comment]
Same problem here. Any idea?

**Comment by komelabbbas** [comment]
Same problem here. Any idea?
plz help

**Comment by Johan-dutoit** [comment]
Please create a new issue with as much info as possible.  If you're not on 3.x.x., then upgrade and try again.

**Comment by tiffanym19** [comment]
I already upgrade it to 3.x.x still the issue occurs. Any solutions?
