### ISSUE TITLE
Android and RN combined project  The Callback not receive

### ISSUE THREAD

**Issue by yuanbolin** [react-native-image-picker/react-native-image-picker#1383]
ImagePicker.launchImageLibrary({
      mediaType: 'photo'
    },(res)=>{
      console.log(res)
    })

Console does not receive

**Comment by yuanbolin** [comment]
Couldn't load memtrack module

**Comment by yuanbolin** [comment]
cannot android.app .clientTransactionHandler

**Comment by violinxliu** [comment]
the same mistake

**Comment by rezasazesh** [comment]
Did you find a solution to this?

**Comment by ravirajn22** [comment]
If possible can you migrate to using version 3.0.0-vnext.1 https://github.com/react-native-image-picker/react-native-image-picker/releases/tag/v3.0.0-vnext.1

Check if your issue is solved.
Check 3.x.x docs for installation and API changes.
