### ISSUE TITLE
App crash when take a picture and press back button

### ISSUE THREAD

**Issue by mateuschaves** [react-native-image-picker/react-native-image-picker#1387]
# Bug report

## Summary

The app crash when i open the camera or image library and press back button.

![image](https://user-images.githubusercontent.com/34848657/86137327-8faba000-bac3-11ea-950b-9e7f95ad1126.png)

## Environment info

`react-native info` output:

```bash
System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz     
    Memory: 2.53 GB / 15.92 GB
  Binaries:
    Node: 10.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD   
    npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Version  4.0.0.0 AI-193.6911.18.40.6514223
  Languages:
    Java: 1.8.0_221
    Python: 3.8.3
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 2.3.1

## Steps to reproduce

1. Launch Camera or ImageLibrary
2. Press back button

Describe what you expected to happen:

1. Should not crash

## Reproducible sample code

```javascript
  ImagePicker.launchImageLibrary(
            {storageOptions: constants.storageOptions},
            response => {
                if (response.error) {
                    Alert.alert(
                        'Algo deu errado',
                        'Verifique se você permitiu que o nosso aplicativo usasse a sua galeria'
                    );
                    return;
                }

               
            }
        );
```

**Comment by HapitatEric** [comment]
Any updates on this? Experience the same.

**Comment by scrapecoder** [comment]
Any updates?

**Comment by ravirajn22** [comment]
If possible can you migrate to using version 3.0.0-vnext.1 https://github.com/react-native-image-picker/react-native-image-picker/releases/tag/v3.0.0-vnext.1

Check if your issue is solved.
Check 3.x.x docs for installation and API changes.

**Comment by Kurikaeshiru** [comment]
Have you tried to handle response.didCancel state? I had the same issue (without camera) and it was a solution for my case.

**Comment by eldirb21** [comment]
ImagePicker.launchCamera(option, (response) => {
        if (response.didCancel === true) {
          return ''
        }
        const datatransfer = response.assets
        var datas = {}
        for (let d = 0; d < datatransfer.length; d++) {
          datas = datatransfer[d];
        }
        ImageResizer.createResizedImage(datas.uri, 250, 250, 'JPEG', 100).then((response) => {
          RNFS.readFile(response.uri, 'base64').then(res => {
           

{this  help full
