### ISSUE TITLE
Can't build android

### ISSUE THREAD

**Issue by benduongquang** [react-native-image-picker/react-native-image-picker#1391]
Hi I'm trying to build android and have this issue.

```
* Where:
Build file 'C:\Users\Administrator\Desktop\MyProject\node_modules\react-native-image-picker\android\build.gradle' line: 20

* What went wrong:
A problem occurred evaluating project ':react-native-image-picker'.
> Failed to apply plugin [id 'com.android.internal.library']
   > The option 'android.enableUnitTestBinaryResources' is deprecated.
     The current default is 'false'.
     It has been removed from the current version of the Android Gradle plugin.
     The raw resource for unit test functionality is removed.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

```

![2020-07-10_15-30-01](https://user-images.githubusercontent.com/65145478/87134008-48db5880-c2c2-11ea-9195-5c72977bb477.png)

**Comment by dharminderraja** [comment]
Yep Same error is happening here also after updating the react-native from 62 to 63 and gradle to latest.

**Comment by cltsang** [comment]
#1390

**Comment by jafar-jabr** [comment]
https://github.com/jafar-jabr/node_modules_temp_fixes

**Comment by grndvl1** [comment]
> Yep Same error is happening here also after updating the react-native from 62 to 63 and gradle to latest.
> But found the solution here
> https://github.com/react-native-community/react-native-image-picker/pull/1390/files

Thank you this saved me a ton of time since I was compiling a library and no seemed to have the reason why.  This fixed my compiling issues!

**Comment by Samtapes** [comment]
I've tried everything and I'm having it:

```
BUILD FAILED in 10s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
Note: Some input files use or override a deprecated API.
```

**Comment by michaelVictoriaDev** [comment]
android -> build.gradle

buildscript {
  ...
        minSdkVersion = 21
  ...
}
