### ISSUE TITLE
Android app crashes when choose image from Gallery (Android API 28 )

### ISSUE THREAD

**Issue by Luckygirlllll** [react-native-image-picker/react-native-image-picker#1394]
# Bug report

## Summary

Android app crashes when choose image from Gallery (Android API 28 ). I test Android API 29 and 30 and it works fine. 

```
 ImagePicker.launchImageLibrary(options, (image) => {
        console.log("image ", image)
        const source = { uri: image.uri };
        this.setState({imagePath: source})
        this.setState({image: image})
      });

```
## Environment info

`react-native info` output:
```bash
# paste it here
```

OS: macOS 10.15.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 19.32 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 25.0.0, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 27.0.1, 27.0.3, 28.0.3, 29.0.2
      System Images: android-23 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-26 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  npmPackages:
    react: ~16.9.0 => 16.9.0 
    react-native: ~0.61.4 => 0.61.5 
  npmGlobalPackages:
    create-react-native-app: 1.0.0
    react-native-cli: 2.0.1
    react-native-device-info: 2.0.0
    react-native-fabric: 0.5.2
    react-native-gesture-handler: 1.4.1
    react-native-git-upgrade: 0.2.7
    react-native-maps: 0.25.0
    react-native-permissions: 2.0.2
    react-native-reanimated: 1.2.0

Library version: 2.3.3

## Steps to reproduce

 ImagePicker.launchImageLibrary(options, (image) => {
        console.log("image ", image)
        const source = { uri: image.uri };
        this.setState({imagePath: source})
        this.setState({image: image})
      });

Describe what you expected to happen:

App doesn't crash

**Comment by vobear** [comment]
我也遇到程序奔溃问题，从安卓手机图库选择图片大小超过10兆，程序崩溃。

**Comment by rezasazesh** [comment]
Mine does not crash but it does not return an image and closes the image picker! Only some users have this problem! Did you find a solution?

**Comment by Luckygirlllll** [comment]
@rezasazesh I switched to react-native-image-crop-picker library, it doesn't crash.

**Comment by ravirajn22** [comment]
Sorry we could not respond in time.
Version 2.x.x is not longer supported, please upgrade to 3.x.x
I hope the issue is solved, if not reply here or create new issue with details I am happy to fix it.
