### ISSUE TITLE
S3 Upload with Pre-signed URL - EntityTooLarge for small file

### ISSUE THREAD

**Issue by MayoudP** [react-native-image-picker/react-native-image-picker#1402]
## Summary

Hello, I'm using S3 Upload with a pre-signed URL method on my application to send basically, pictures and photo. Concerning the picker, I'm using `react-native-image-picker`. 
I haven't any issue to get the pre-signed URL, and all the needed Infos `key, bucket, credentials,...` however, when I'm trying to validate the file upload on S3, I'm keep having this error on iOS : 

```
"<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>EntityTooLarge</Code>
<Message>Your proposed upload exceeds the maximum allowed size</Message>
<ProposedSize>26354</ProposedSize>
<MaxSizeAllowed>23326</MaxSizeAllowed>
<RequestId>...</RequestId>
<HostId>...</HostId>
</Error>"
```

I think it could be related to this issue : https://github.com/react-native-community/react-native-image-picker/issues/1272 
However using other library or trick didn't worked. I literally tried everything, base64, react-native-image-resize, react-native-fetch-blob... Nothing worked. 
⚠️ It works well on Android tho. 

## Environment info

`react-native info` output:

```bash
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

Library version: x.x.x

## Steps to reproduce

```
function formData(data) {
    var res = new FormData();
    for (var k in data) {
      res.append(k, data[k]);
    }
  
    res.append("file", {name, uri, size});
    return res;
  }

  const response = yield call(api.validateUploadMedia, preSignedUrl, formData(fields)); //Where fields are the bucket info...
```

Describe what you expected to happen:

S3 upload should works. Got the error mentioned above instead.

**Comment by nicolas-amabile** [comment]
Any updates on this? I have exactly the same problem.
I tried with [this solution](https://github.com/facebook/react-native/issues/29021#issuecomment-662196480) using [patch-package](https://www.npmjs.com/package/patch-package) but I got the same error 😕

**Comment by MayoudP** [comment]
@nicolas-amabile Where do you fill all the needed fields when using pre-signed URL such as `key, bucket, credentials` ? 
I'm still having the error, I'm appending to the formData a `file`.
If using image like you, I'm getting this error : `<Error><Code>MaxPostPreDataLengthExceeded</Code><Message>Your POST request fields preceeding the upload file was too large.</Message>`

```
const promise = new Promise((resolve, reject) => {
    RNFS.readFile(uri, "base64").then(response => {
      const arrayBuffer = decode(response);
      resolve(arrayBuffer);
    });
  });

  const formattedData = yield promise;

  function formData(data) {
    var res = new FormData();
    for (var k in data) {
      res.append(k, data[k]);
    }
    res.append("image", {
      uri: uri,
      name: path(["fileName"], file),
      type,
      size
    });
    res.append("data", formattedData);
    return res;
  }

  const response = yield call(api.validateUploadMedia, url, formData(fields));
`

**Comment by nicolas-amabile** [comment]
In my case, all the S3 config is handled by the server. The app only sends the file and expect the URL back instead of uploading directly from react-native.
`s3.service` file:
```
const aws = require('aws-sdk');
const multer = require('multer');
const multerS3 = require('multer-s3');

const {
  AWS_S3_SECRET_ACCESS_KEY: secretAccessKey,
  AWS_S3_ACCESS_KEY_ID: accessKeyId,
  AWS_S3_REGION: region,
} = process.env;

aws.config.update({
  secretAccessKey,
  accessKeyId,
  region,
});

const s3 = new aws.S3();

const fileFilter = (req, file, cb) => {
  if (['image/jpeg', 'image/png'].includes(file.mimetype)) {
    cb(null, true);
  } else {
    cb(new Error('Invalid Mime Type, only JPEG and PNG'), false);
  }
};

const upload = multer({
  fileFilter,
  storage: multerS3({
    s3,
    bucket: 'your-bucket-name-here',
    acl: 'public-read',
    limits: { fileSize: 30000000 }, // In bytes: 30000000 bytes = 30 MB
    metadata: (req, file, cb) => {
      cb(null, { fieldName: file.fieldname });
    },
    key: (req, file, cb) => {
      const ext = file.mimetype.split('/').pop();
      const fileName = `${Date.now().toString()}.${ext}`;
      cb(null, fileName);
    },
  }),
});

module.exports = {
  upload,
};
```

And then the controller for my `/images/upload` endpoint:
```
const { upload } = require('../services/s3.service');

const singleUpload = upload.single('image');

const uploadImage = async (req, res) => {
  singleUpload(req, res, (error) => {
    if (error) {
      return res.status(422).send({ errors: [{ title: 'File Upload Error', detail: error.message }] });
    }
    return res.status(201).json({ imageUrl: req.file.location }); // The only field we need at the moment
  });
};

module.exports = {
  uploadImage,
};
```

**Comment by matamicen** [comment]
@aleluis777 do you have the code please? We called the pre signed function but we don't know how to map everything, we are trying to uplaod videos of 10mb.

Thanks.
