### ISSUE TITLE
ImagePicker Error: Cannot launch photo library

### ISSUE THREAD

**Issue by mayur-bhandari** [react-native-image-picker/react-native-image-picker#1405]
# Bug report

## Summary

Hi, I was using react-native v0.59.5 and react-native-image-picker v0.28.1 and after installing the package and running react-native link react-native-image-picker everything worked fine. Recently I created a new react-native application using react-native v0.63.0 and I installed react-native-image-picker v2.3.3. Since react-native v0.60+ everything is auto-linked. I did not run the react-native link react-native-image-picker command. So after, running the app, I was not able to get images from the library. I can click images from the camera but not able to pick images from the library. On clicking Choose from Library, I get the error `ImagePicker Error:  Cannot launch photo library`

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz
    Memory: 388.00 MB / 12.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.6.0. - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 23, 26, 27, 28, 29
      Build Tools: 26.0.2, 27.0.3, 28.0.3, 29.0.2
      System Images: android-26 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_211 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.9.0 => 16.9.0 
    react-native: 0.63.0 => 0.63.0 
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 2.3.3

## Steps to reproduce

1. Create a new react-native application. Install react-native-image-picker v2.3.3

Describe what you expected to happen:

1. I should be able to pick images from the Library.

## Reproducible sample code

```

const options = {
    quality: 1.0,
    storageOptions: {
        skipBackup: true,
    },
};
ImagePicker.showImagePicker(options, (response) => {
    if (response.didCancel) {
        console.log('User cancelled photo picker');
    } else if (response.error) {
        console.log('ImagePicker Error: ', response.error);
    } else if (response.customButton) {
        console.log('User tapped custom button: ', response.customButton);
    } else {
        console.log('ImagePicker Response: ',response.type, response.fileName, response.uri);
    }
});

```

**Comment by mayur-bhandari** [comment]
I also tried using ImagePicker.launchImageLibrary() but even that gives an error `Cannot launch photo library`.

**Comment by meiqi1992** [comment]
0.63.2 same issue ，how resolve？

**Comment by cham1985** [comment]
same issue "Cannot launch photo library" on  Pixel 3a

**Comment by RNTop** [comment]
This is not an issue of SDK. seems like it is related with your RN version. actually getting tons of stranges with new version.
So please add  ```android:requestLegacyExternalStorage="true"``` application tag in Androidmanifest.xml

**Comment by ravirajn22** [comment]
If possible can you migrate to using version 3.0.0-vnext.1 https://github.com/react-native-image-picker/react-native-image-picker/releases/tag/v3.0.0-vnext.1

Check if your issue is solved.
Check 3.x.x docs for installation and API changes.

**Comment by davidbiller** [comment]
any news?

**Comment by davidbiller** [comment]
> This is not an issue of SDK. seems like it is related with your RN version. actually getting tons of stranges with new version.
> So please add `android:requestLegacyExternalStorage="true"` application tag in Androidmanifest.xml

tried. Same error

**Comment by davidbiller** [comment]
@ravirajn22 
Error: Unable to resolve module `./internal/nativeInterface` from `node_modules/react-native-image-picker/src/index.ts`:

**Comment by ravirajn22** [comment]
@davidbiller are you importing correctly? May be also cache issue, run `npx react-native start --reset-cache`. Remove node_modules and reinstall. Try and ping.

**Comment by davidbiller** [comment]
> @davidbiller are you importing correctly? May be also cache issue, run `npx react-native start --reset-cache`. Remove node_modules and reinstall. Try and ping.

fixed it yes. 
now I get this:
[TypeError: undefined is not an object (evaluating '_reactNativeImagePicker.default.launchImageLibrary')]

**Comment by ravirajn22** [comment]
Import like,

`import {launchCamera, launchImageLibrary} from 'react-native-image-picker'`

**Comment by iwantadventureinthegreatwidesomewhere** [comment]
@ravirajn22 I had same issue, upgraded to 3.x.x on RN 0.63.2. Works on iOS, but Android has a much different issue:

<img width="266" alt="Screen Shot 2020-12-17 at 3 04 20 PM" src="https://user-images.githubusercontent.com/32583016/102537625-2b809680-4079-11eb-9477-aa27bcde25ec.png">

Imported like this:

`import { launchImageLibrary } from "react-native-image-picker";`

Used like this:

`launchImageLibrary(
      {
        mediaType: "photo",
        includeBase64: false,
        maxHeight: 200,
        maxWidth: 200,
        quality: 1,
      },
      (response) => {
        if (!response.didCancel) {
          setProfileImage(response.uri);
        }
      }
    );`

**Comment by Johan-dutoit** [comment]
I installed the library over the weekend on a new project of mine and was able to get it working without problems.
My only suggestion @iwantadventureinthegreatwidesomewhere is that you clean y& rebuild your android project.

**Comment by iwantadventureinthegreatwidesomewhere** [comment]
@Johan-dutoit Thank you for the suggestion. Unfortunately, we tried cleaning and rebuilding across multiple devices, and all tested devices experienced the same issues. We decided to move forward with a different package, and that worked successfully out of the box on RN 0.63.3 for us.

**Comment by davidbiller** [comment]
> @Johan-dutoit Thank you for the suggestion. Unfortunately, we tried cleaning and rebuilding across multiple android devices, and all tested devices experienced the same issues as before. We decided to move forward with a different package that worked successfully for us out of the box on RN 0.63.3.

Which package?

**Comment by iwantadventureinthegreatwidesomewhere** [comment]
> > @Johan-dutoit Thank you for the suggestion. Unfortunately, we tried cleaning and rebuilding across multiple android devices, and all tested devices experienced the same issues as before. We decided to move forward with a different package that worked successfully for us out of the box on RN 0.63.3.
> 
> Which package?

react-native-image-crop-picker https://github.com/ivpusic/react-native-image-crop-picker. I'm using version 0.35.2 and it uses your device's cropping tools as well, which I don't recall if this package enabled.

**Comment by SINGHPRT** [comment]
Added the folloiwng in androidManifest.xml. It fixed this issue for me.

  <queries>
        <intent>
            <action android:name="android.media.action.IMAGE_CAPTURE" />
        </intent>
        <intent>
            <action android:name="android.intent.action.GET_CONTENT" />
            <data android:mimeType="image/*" />
        </intent>
        <intent>
            <action android:name="android.intent.action.PICK" />
            <data android:mimeType="image/*" />
        </intent>
        <intent>
            <action android:name="android.intent.action.CHOOSER" />
        </intent>
    </queries>

**Comment by kamalverma911** [comment]
> Added the following queries section in androidManifest.xml. It fixed this issue for me.

Can you please tell what did you added in manifest to solved this?

**Comment by SINGHPRT** [comment]
> > Added the following queries section in androidManifest.xml. It fixed this issue for me.
> 
> Can you please tell what did you added in manifest to solved this?

We had this issue with Image picker package with Android 12. I added the queries section within [MANIFEST] node as follows:

`
<manifest ...
    package="com.sampleApp" >

    <queries>
        <intent>
            <action android:name="android.media.action.IMAGE_CAPTURE" />
        </intent>
        <intent>
            <action android:name="android.intent.action.GET_CONTENT" />
            <data android:mimeType="image/*" />
        </intent>
        <intent>
            <action android:name="android.intent.action.PICK" /> 
            <data android:mimeType="image/*" />
        </intent>
        <intent>
            <action android:name="android.intent.action.CHOOSER" />
        </intent>
    </queries>

    <application ...

</application>

</manifest>
`


Note: Android studio though may say - "Element queries is not allowed here"  but donot worry it works like a charm :)

**Comment by kamalverma911** [comment]
Thank you its working :)

**Comment by ThanhNguyen140797** [comment]
> > > Added the following queries section in androidManifest.xml. It fixed this issue for me.
> > 
> > 
> > Can you please tell what did you added in manifest to solved this?
> 
> We had this issue with Image picker package with Android 12. I added the queries section within [MANIFEST] node as follows:
> 
> ` <manifest ... package="com.sampleApp" >
> 
> ```
> <queries>
>     <intent>
>         <action android:name="android.media.action.IMAGE_CAPTURE" />
>     </intent>
>     <intent>
>         <action android:name="android.intent.action.GET_CONTENT" />
>         <data android:mimeType="image/*" />
>     </intent>
>     <intent>
>         <action android:name="android.intent.action.PICK" /> 
>         <data android:mimeType="image/*" />
>     </intent>
>     <intent>
>         <action android:name="android.intent.action.CHOOSER" />
>     </intent>
> </queries>
> 
> <application ...
> ```
> 
> `
> Note: Android studio though may say - "Element queries is not allowed here" but donot worry it works like a charm :)

thanks. it's working.
Note: need update android/build.gradle at least verison 3.5.4 like this: 

   ```
dependencies {
        classpath("com.android.tools.build:gradle:3.5.4")      
        ...
    }
```
