### ISSUE TITLE
图片无法上传，请问怎么解决呢？

### ISSUE THREAD

**Issue by Zhongxiangyun** [react-native-image-picker/react-native-image-picker#1406]
我实现上传图片的操作，也在header里面做了类型设置。
headers: {"Content-Type":"multipart/form-data; charset=utf-8"},
下面是核心的代码，但是后端会报错：msg: "Current request is not a multipart request"

请问应该怎么解决呢？

console.log(fileUrl, fileName);
    let formData = new FormData();//如果需要上传多张图片,需要遍历数组,把图片的路径数组放入formData中
    let file = {uri: fileUrl, type: 'image/jpeg', name: fileName};   //这里的key(uri和type和name)不能改变,
    formData.append("file",file);   //这里的files就是后台需要的key

**Comment by ravirajn22** [comment]
English please.
