### ISSUE TITLE
setObjectForKey: object cannot be nil (key: data)

### ISSUE THREAD

**Issue by kilimchoi** [react-native-image-picker/react-native-image-picker#1407]
Hi, When I try to pick from photo library I get the following error :

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** setObjectForKey: object cannot be nil (key: data)'

But it happens to only some users and I was only able to discover this from the crash report. It happened to someone using iphone X with ios 13.6
I'm using react-native-image-picker": "^2.3.1 and "react-native": "0.62.2"

It seems that other people have experienced this issue in the past here, https://github.com/react-native-community/react-native-image-picker/issues/611 but reopening this because many people said it's happening to them as well.

**Comment by demchenkoalex** [comment]
Almost the same config (iPhone X, iOS 13.5.1, react-native-image-picker 2.3.3, react-native 0.63.2), the same error, happens only on a specific picture. Crash is happening on the native side as stated in the #611. Tried to export that picture from the phone, but after uploading it or sending it as a file and downloading it back to the phone - everything works as expected, so I assume something is wrong with an original picture, however it shows ok in the photos and I can send it through, for example Telegram, without a crash.

**Comment by ravirajn22** [comment]
Version 2.x.x is not longer supported, please upgrade to 3.x.x
I hope the issue is solved, if not create new issue with details I am happy to fix it.
