### ISSUE TITLE
[iOS] Image library opening without permission

### ISSUE THREAD

**Issue by danilozano** [react-native-image-picker/react-native-image-picker#1411]
# Bug report

## Summary

Hi, I've been testing the ImagePicker with opening the image library and observe that on iOS it opens the gallery without having given any permission. I expect there to be a dialog asking the user to allow or deny access to the image library before opening. If denied, I would expect to pop my custom alert telling the user to give the app permission from their settings. It works as expected on Android.

I have tested iOS on a physical device on a release build and still see this issue. I also observe that on press of my app in settings, I don't see "Photos" as an option to allow permissions for.

## Environment info

`react-native info` output:

```bash
System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 64.18 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  npmPackages:
    react: 16.10.2 => 16.10.2 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version: 2.3.0

## Steps to reproduce

1. Use ImagePicker to launch image library on iOS
2. Observe no permission dialog appears to grant/deny permission - image library is opened.

Describe what you expected to happen:

1.  Use ImagePicker to launch image library on iOS
2. Permission dialog appears asking to grant/deny image library permission for the app
3. Press allow -> image library opens successfully
4. Press deny -> alert dialog appears describing that the user must give the app permission

```
ImagePicker.launchImageLibrary(options, response => {
            if (response.didCancel) {
                // Cancelled
            } else if (response.error) {
                const error = new Error(response.error);
                if (response.error === ImagePickerPermissionError) {
                    Alert.alert(
                        'We need your permission to access your photos',
                        'To upload, open your device settings and allow this app to access photos.',
                    );
                }
            } else {
                // Upload
            }
        });
    };
```

**Comment by abemusic** [comment]
@danilozano I was also having issues figuring out how permissions work because the docs point to a `permissionDenied`, but the only place that appears to be used is in the android implementation. I've since started using `react-native-permissions` to handle checking and requesting for the proper permissions. Good luck!

**Comment by dantonio1401** [comment]
I am also having this issue, the app opens the photo library and asks for permissions after I pick a photo.

**Comment by dantonio1401** [comment]
Did some research and found that Apple actually doesn't require asking for permission to open the photo library found here https://developer.apple.com/documentation/photokit/requesting_authorization_to_access_photos

So if you update the library, it shouldn't ask for permission at all before or after the library opens.

Another option is to explicitly ask for permission using https://github.com/react-native-community/react-native-permissions

Hope this helps 👌🏾

**Comment by anton-patrushev** [comment]
+

**Comment by beattractive** [comment]
> Did some research and found that Apple actually doesn't require asking for permission to open the photo library found here https://developer.apple.com/documentation/photokit/requesting_authorization_to_access_photos
> 
> So if you update the library, it shouldn't ask for permission at all before or after the library opens.
> 
> Another option is to explicitly ask for permission using https://github.com/react-native-community/react-native-permissions
> 
> Hope this helps 👌🏾

The Apple link doesn't work anymore 👎 
https://developer.apple.com/documentation/bundleresources/information_property_list/protected_resources/requesting_authorization_to_access_photos

Does that mean you have to ask permission again?
https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/plist/info/NSPhotoLibraryUsageDescription
