### ISSUE TITLE
i got the error ../react-native-image-picker/src/index.ts: Unexpected token, expected "{"

### ISSUE THREAD

**Issue by acaixuediananao** [react-native-image-picker/react-native-image-picker#1412]
i got the error ../react-native-image-picker/src/index.ts: Unexpected token, expected "{";
![image](https://user-images.githubusercontent.com/10300702/92300375-f13d2e80-ef8c-11ea-92a3-aecbd39f3a76.png)
when i use the version 0.26.2 of the react-native-image-picker and the version 0.47 of react-native ,  there is no error.But when i change the react-native-image-picker’s version to 2.3.3 and react-native's version to 0.63 ,the error appeared;
how can i solve it?
this is my package.json

{
	"name": "HouseKeeperApp",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"configureJPush": "node node_modules/jpush-react-native/JPushConfiguration.js",
		"start": "react-native start",
		"test": "jest"
	},
	"dependencies": {
		"axios": "^0.16.1",
		"jcore-react-native": "^1.3.2",
		"jpush-react-native": "^2.5.10",
		"lodash": "^4.16.6",
		"moment": "^2.17.1",
		"numeral": "^1.5.3",
		"react": "16.13.1",
		"react-native": "^0.63",
		"react-native-communications": "^2.2.1",
		"react-native-config": "^1.3.3",
		"react-native-datepicker": "^1.6.0",
		"react-native-easy-toast": "^1.0.5",
		"react-native-fetch-blob": "^0.10.8",
		"react-native-fs": "^2.16.6",
		"react-native-image-crop-picker": "^0.18.1",
		"react-native-image-picker": "^2.3.3",
		"react-native-navigation": "v2.0.0-experimental.300",
		"react-native-parsed-text": "0.0.16",
		"react-native-scrollable-tab-view": "^1.0.0",
		"react-native-sk-toast": "^1.0.2",
		"react-native-smart-amap-location": "^1.1.3",
		"react-native-smart-pull-to-refresh-listview": "^1.6.10",
		"react-native-socketio": "^0.3.0",
		"react-native-splash-screen": "^2.1.0",
		"react-redux": "^5.0.4",
		"react-timer-mixin": "^0.13.3",
		"redux": "^3.6.0",
		"redux-subscriber": "^1.1.0",
		"redux-thunk": "^2.2.0",
		"rn-fetch-blob": "^0.10.12"
	},
	"devDependencies": {
		"babel": "^6.23.0",
		"babel-jest": "^23.4.0",
		"babel-plugin-module-alias": "^1.6.0",
		"babel-plugin-module-resolver": "^4.0.0",
		"babel-preset-react-native": "^5.0.2",
		"jest": "^23.6.0",
		"react-test-renderer": "^16.13.1",
		"redux-immutable-state-invariant": "^1.2.4",
		"redux-logger": "^2.7.4"
	},
	"license": "MIT",
	"jest": {
		"preset": "react-native"
	}
}

**Comment by Atuldhaka** [comment]
Facing the same issue when i upgraded to the new latest version of react native i.e. 0.63.2

**Comment by ravirajn22** [comment]
Version 2.x.x is not longer supported, please upgrade to 3.x.x
