### ISSUE TITLE
[Android] App restart after choose photo (camera and image library)

### ISSUE THREAD

**Issue by LucasClemencio** [react-native-image-picker/react-native-image-picker#1413]
Hi, my app is restarting after choosing a photo on the camera or library.
This happens only on some devices, for example: ASUS Zenphone Maxshot (Android 9).
My emulator works fine, but on some real devices it happens.

"react": "16.13.1",
"react-native": "0.63.2",
"react-native-image-picker": "^2.3.3"

Code:
import ImagePicker from 'react-native-image-picker';

Function:
ChooseImage = () => {
    let options = { noData: true, mediaType: 'photo', };

    ImagePicker.showImagePicker(options, response => {
      if (response) {
        this.setState({ image: response, });
      }
    });
}

Button
<Button 
      onPress={this.ChooseImage} 
      title="Choose Image" 
/>

npx react-native info

System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz   
    Memory: 1.50 GB / 7.88 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE        
    Yarn: Not Found
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 26, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
    Windows SDK: Not Found
  IDEs:
    Android Studio: Version  3.5.0.0 AI-191.8026.42.35.5977832
    Visual Studio: 16.3.29519.87 (Visual Studio Community 2019)
  Languages:
    Java: 1.8.0_231 - C:\Program Files\Java\jdk1.8.0_231\bin\javac.EXE
    Python: 2.7.17 - C:\Python27\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by Stanley521** [comment]
https://github.com/react-native-community/react-native-image-picker/issues/1350#issue-605813254

The response is different when it encounters an error and it will not have the property that you need like filename or URI, which will cause an error

```ImagePicker.launchCamera(imageOptions, async (response) => {
                    if (response.didCancel) {
                        // handle cancel
                    } else if (response.error) {
                        // handle error
                    } else if (response.customButton) {
                        // handle custom button
                    } else {
                        // When success
                    })```

**Comment by LucasClemencio** [comment]
Thanks for the answer.
The problem wasn't  the response (because in my case i just want the 'success' case).
I solved it using android:requestLegacyExternalStorage="true" in application tag in AndroidManifest.xml, but is 
temporary

**Comment by fredyonge** [comment]
Same problem, happens on my real life S9 device

**Comment by edo1493** [comment]
I have the same

**Comment by scrapecoder** [comment]
Facing same issue..any updates?

**Comment by crushy26** [comment]
Same issue +1

This is critical happening on oneplus 3, android 9

**Comment by nahansans** [comment]
i have same issue

**Comment by HaffASE** [comment]
Same issue for the first photo on android devices. The app is restarted after taking a photo

**Comment by SaraChicaD** [comment]
I also have this issue using version `3.1.3`, RN `63.2` and Android SDK `29`. I tried the solution mentioned by @LucasClemencio with `android:requestLegacyExternalStorage="true"` and wasn't able to get that to work.

**Comment by ravirajn22** [comment]
duplicate of #1502
