### ISSUE TITLE
ImagePicker returns empty data in response object when capture image from camera.

### ISSUE THREAD

**Issue by ketanbrydotinfotech** [react-native-image-picker/react-native-image-picker#1420]
# Bug report

## Summary

I want to capture image using camera and get base64. When I launch camera and capture image, picker returns response with empty data, but it contains file name and path.

## Environment info

`react-native info` output:

```bash
 react: 16.13.1 => 16.13.1
 react-native: 0.63.0 => 0.63.0
```

Library version: ^2.3.3

## Steps to reproduce

1. Launch camera. 
2. Capture image.
3. response.data is empty string.

Describe what you expected to happen:

1. response.data should be base64 string

## Reproducible sample code

    const selectProfilePic = () => {
    var options = {
      title: 'Select Image',
      takePhotoButtonTitle: 'Take Photo',
      chooseFromLibraryButtonTitle: 'Choose Image',
      storageOptions: {
        skipBackup: true,
        path: 'images',
      },
    };

    ImagePicker.showImagePicker(options, res => {
      //console.log('Response = ', res);

      if (res.didCancel) {
        console.log('User cancelled image picker');
      } else if (res.error) {
        console.log('ImagePicker Error: ', res.error);
      } else if (res.customButton) {
        console.log('User tapped custom button: ', res.customButton);
      } else {
        let source = res;
        setProfilePic('data:image/jpeg;base64,' + source.data)

      }
    });
    };

**Comment by LiuTangLei** [comment]
same issue for me

**Comment by LeandroBernardo** [comment]
same issue for me

**Comment by LeandroBernardo** [comment]
same issue for me

**Comment by A-Tokyo** [comment]
@ketanbrydotinfotech Does the response contain the uri? Can you please show us a preview of the response object?

**Comment by mv-developer** [comment]
I think that happen because fileName didn't return

**Comment by ravirajn22** [comment]
If possible can you migrate to using version 3.0.0-vnext.1 https://github.com/react-native-image-picker/react-native-image-picker/releases/tag/v3.0.0-vnext.1

Check if your issue is solved.
Check 3.x.x docs for installation and API changes.

**Comment by ravirajn22** [comment]
I hope the issue is solved, if not reply here or create new issue with details I am happy to fix it.
