### ISSUE TITLE
[Question] Way to determine whether photo is taken from camera or selected from gallery

### ISSUE THREAD

**Issue by R4DIC4L** [react-native-image-picker/react-native-image-picker#1423]
# Question
Is there any way to determine whether the photo you receive has been taken from a shot with the camera or existing one selected via the gallery after using showImagePicker method?

**Comment by ravirajn22** [comment]
Sorry we could not respond in time.
Version 2.x.x is not longer supported, please upgrade to 3.x.x.
showImagePicker API is removed
