### ISSUE TITLE
Open video local storage (library)  exit the application

### ISSUE THREAD

**Issue by khuongsatou** [react-native-image-picker/react-native-image-picker#1427]
# Bug report

## Summary
Open video local storage (library) cash app.

## Environment info
"react-native-image-picker": "^2.3.3",
"react": "16.13.1",
"react-native": "0.63.2",

`react-native info` output:

```bash
# paste it here
```

Library version: x.x.x

## Steps to reproduce
<img width="1440" alt="Screen Shot 2020-09-16 at 9 54 30 AM" src="https://user-images.githubusercontent.com/44874881/93286980-a16b2c80-f802-11ea-80e9-51f2122abfa5.png">

Describe what you expected to happen:

1. Open library.
2. Choose Video.
3. Exit the application

## Reproducible sample code

<img width="1440" alt="Screen Shot 2020-09-16 at 10 00 01 AM" src="https://user-images.githubusercontent.com/44874881/93287324-6a494b00-f803-11ea-8eab-d5473521003b.png">

**Comment by MaoPeng94** [comment]
Same here. 
I did got some error response : 
{"error": "Can't resize the image", "fileName": "VID_20200917_172436.mp4", "fileSize": 12943805, "isVertical": true, "originalRotation": 0, "path": "/storage/emulated/0/DCIM/Camera/VID_20200917_172436.mp4", "type": "video/mp4", "uri": "content://media/external/video/media/326095"}

I think it is because the file size is too large.
Is there any solution?

**Comment by walterdl** [comment]
Same problem over here using android 10, react-native 0.63.0 and react-native-image-picker ^2.3.3

**Comment by walterdl** [comment]
This is the stacktrace that Flipper provides when the app crash after a video gets selected.
![image](https://user-images.githubusercontent.com/26971414/93520974-f2f3e400-f8f4-11ea-8ec4-31afac34ceab.png)

**Comment by khuongsatou** [comment]
> Same here.
> I did got some error response :
> {"error": "Can't resize the image", "fileName": "VID_20200917_172436.mp4", "fileSize": 12943805, "isVertical": true, "originalRotation": 0, "path": "/storage/emulated/0/DCIM/Camera/VID_20200917_172436.mp4", "type": "video/mp4", "uri": "content://media/external/video/media/326095"}
> 
> I think it is because the file size is too large.
> Is there any solution?

I don't know

**Comment by padunk** [comment]
I have the same problem too. Is this a bug?
Using android 10, rn 0.63.2, rn-image-picker 2.3.4
And I got no error

**Comment by khuongsatou** [comment]
> I have the same problem too. Is this a bug?
> Using android 10, rn 0.63.2, rn-image-picker 2.3.4
> And I got no error

Wait admin fix. You can open android studio logcat if not error

**Comment by matamicen** [comment]
we have the same problem on Android 10, rn 063.2,  rn-image-picker 2.3.4

**Comment by CarvalhoPaulo** [comment]
I got a same error

**Comment by CarvalhoPaulo** [comment]
I got same error and was solved setting noData param to true
`ImagePicker.launchImageLibrary({
      mediaType: 'mixed',
      allowsEditing: false,
      noData: true,
      storageOptions: {
        cameraRoll: false,
        skipBackup: true,
        path: 'images'
      }
    }, (file) => {
      if (file && file.type && file.type.includes('image')) {
        this.cropImage(file.uri)
      }
      if (file && file.type && file.type.includes('video')) {
        this.cropVideo(file.path)
      }
    })`

**Comment by matamicen** [comment]
@CarvalhoPaulo doesn't work noData: true to get videos. The same error. Thanks anyway.

**Comment by ravirajn22** [comment]
If possible can you migrate to using version 3.0.0-vnext.1 https://github.com/react-native-image-picker/react-native-image-picker/releases/tag/v3.0.0-vnext.1

Check if your issue is solved.
Check 3.x.x docs for installation and API changes.

**Comment by khuongsatou** [comment]
> If possible can you migrate to using version 3.0.0-vnext.1 https://github.com/react-native-image-picker/react-native-image-picker/releases/tag/v3.0.0-vnext.1
> 
> Check if your issue is solved.
> Check 3.x.x docs for installation and API changes.

Thanks you. I will try it later and give feedback

**Comment by khuongsatou** [comment]
> If possible can you migrate to using version 3.0.0-vnext.1 https://github.com/react-native-image-picker/react-native-image-picker/releases/tag/v3.0.0-vnext.1
> 
> Check if your issue is solved.
> Check 3.x.x docs for installation and API changes.

<img width="693" alt="Screen Shot 2020-11-01 at 2 38 56 PM" src="https://user-images.githubusercontent.com/44874881/97797474-fac2da00-1c4f-11eb-8d06-c48659845931.png">

**Comment by ravirajn22** [comment]
https://stackoverflow.com/questions/61586124/illegalargumentexception-invalid-column-latitude
Looks like this is an issue with android 10 default google photos app. Works properly on android 9 and 11. All tested in emulators. Some one test it with real android 10 device and tell if the issue happens. But the bug is on android side.

**Comment by pi0trpietruszewski** [comment]
+1

**Comment by ravirajn22** [comment]
Open a new issue with details with latest version to further diagnose. Thanks
