### ISSUE TITLE
How can I use it in PWA React Native Web?

### ISSUE THREAD

**Issue by ZahraMirali** [react-native-image-picker/react-native-image-picker#1430]
when I install it in react-native-web project in shows an error : Unexpected token 
is this library only for Native (android and ios) ?

**Comment by ravirajn22** [comment]
It's only for android and iOS. No web support.

**Comment by hyochan** [comment]
Why is this closed? This module will be really valuable if we can have this in `web` either.
[Here](https://github.com/expo/expo/blob/master/packages/expo-image-picker/src/ExponentImagePicker.web.ts) is a great example from [expo](https://expo.io)!

@ravirajn22 Will `react-native-image-picker` not going to support `web` in future releases either?

**Comment by ravirajn22** [comment]
I dont know about web API for image picking, so someone should send PR. I will look into expo to see if its feasible for this library to include Web support

**Comment by alessiocancian** [comment]
> Why is this closed? This module will be really valuable if we can have this in `web` either.
> [Here](https://github.com/expo/expo/blob/master/packages/expo-image-picker/src/ExponentImagePicker.web.ts) is a great example from [expo](https://expo.io)!
> 
> @ravirajn22 Will `react-native-image-picker` not going to support `web` in future releases either?

It would be really nice to add web support to this library.
I'll try to send a PR based on that code but without Expo dependencies

**Comment by Ramaraju1992** [comment]
> > Why is this closed? This module will be really valuable if we can have this in `web` either.
> > [Here](https://github.com/expo/expo/blob/master/packages/expo-image-picker/src/ExponentImagePicker.web.ts) is a great example from [expo](https://expo.io)!
> > @ravirajn22 Will `react-native-image-picker` not going to support `web` in future releases either?
> 
> It would be really nice to add web support to this library. I'll try to send a PR based on that code but without Expo dependencies

Hi @alessiocancian, have you able to achieve this?
