### ISSUE TITLE
App cannot be launched after installation

### ISSUE THREAD

**Issue by kkCode** [react-native-image-picker/react-native-image-picker#1431]
### Steps to reproduce
1. `$ yarn add react-native-image-picker`
2. `$ npx react-native run-android --no-jetifier` 

### Actual behaviour
The App can't start.

### Environment
- **React Native version**: 0.63.2
- **React Native platform + platform version**: Android 10.0

### react-native-image-picker
**Version**: npm version 2.3.4

**Comment by andreyevyk** [comment]
run in android folder ./gradlew clean

**Comment by ravirajn22** [comment]
Version 2.x.x is not longer supported, please upgrade to 3.x.x
I hope the issue is solved, if not reply here or create new issue with details I am happy to fix it.
