### ISSUE TITLE
App crashed when taking picture or selecting from the gallery in redmi 7

### ISSUE THREAD

**Issue by scrapecoder** [react-native-image-picker/react-native-image-picker#1432]
**#** Bug report

## Summary
Whenever I'm using the app on the **redmi 7** app is crashing after taking a picture or selecting from the gallery. working on all the devices but not on **redmi 7**

react-native: '"0.63.0"
react-native-image-picker: "^2.3.1",

**Comment by sergeykimaia** [comment]
also happening on xiaomi redmi 8A

**Comment by hienhodeveloper** [comment]
I'm crying. Still waiting for new update

**Comment by absami11** [comment]
Any update on this?

**Comment by scrapecoder** [comment]
@absami11 no updates

**Comment by MathieuLopes** [comment]
Same problem on Huawei P20 ( EML-L29 - Android 10 ).

**Comment by mayurgajra** [comment]
Facing the same issue on **Samsung M20** and there is no error log in the console as well.

**Comment by nashvent** [comment]
I had the same proble but by activating the multidex it was fixed. Follow these [instructions](https://dev-yakuza.github.io/en/react-native/react-native-multidex/)

**Comment by scrapecoder** [comment]
@nashvent I already have multidex support

**Comment by tomahto** [comment]
any update on this? I am facing same issue on Oppo and Xiaomi. Both on Android 10. However after restarting the phone, i didnt encounter any error anymore.

**Comment by scrapecoder** [comment]
@tomahto for android 10 issue please add `android:requestLegacyExternalStorage="true"` in the `application` tag in `AndroidManifest.xml`

**Comment by tomahto** [comment]
@scrapecoder yes, I have added that one but still getting the same issue.

**Comment by scrapecoder** [comment]
@tomahto you facing this issue on all android 10 model or some particular modal?

**Comment by tomahto** [comment]
@scrapecoder Most of them using Huawei, Oppo, or Xiaomi and mostly on Android 10.

**Comment by ravirajn22** [comment]
If possible can you migrate to using version 3.0.0-vnext.1 https://github.com/react-native-image-picker/react-native-image-picker/releases/tag/v3.0.0-vnext.1

Check if your issue is solved.
Check 3.x.x docs for installation and API changes.

**Comment by scrapecoder** [comment]
@ravirajn22 already migrated but nothing change

**Comment by ravirajn22** [comment]
If possible can you print the log, because I don't have those phones with me.

**Comment by HugoGresse** [comment]
I believe you can test using if you use "no not keep activities" from developer option on android which only allow one activity to be running at the same time.

**Comment by ravirajn22** [comment]
duplicate of #1502
