### ISSUE TITLE
IOS 14 ImagePicker launchImageLibrary response.timestamp undefined

### ISSUE THREAD

**Issue by suzushima-ryousuke** [react-native-image-picker/react-native-image-picker#1433]
### Description

```
ImagePicker.launchImageLibrary(options, (response) => {
  // Same code as in above section!
});
```

I uploaded on ios 14, the property `response.timestamp` returns undefined.
Why did that happen?
How can I get  property `response.timestamp` a as before
Who can give me advice or solution?
Thank you everyone

### Environment info
"react-native-image-picker": "^2.3.4",

`npx react-native info ` 

- System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 625.09 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
- Binaries:
    Node: 14.11.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.5 - ~/SourceCode/SVN/FlowerRecordApp107/node_modules/.bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
- Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
- SDKs:
    iOS SDK: Platforms: iOS 14.0, DriverKit 19.0, macOS 10.15, tvOS 14.0, watchOS 7.0
    Android SDK: Not Found
- IDEs:
    Android Studio: Not Found
    Xcode: 12.0/12A7209 - /usr/bin/xcodebuild
- Languages:
    Java: Not Found
    Python: 2.7.16 - /usr/bin/python
- npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.63.2 => 0.63.2 
    react-native-macos: Not Found
- npmGlobalPackages:
    *react-native*: Not Found

**Comment by wanderlust252** [comment]
it happen in Android too

**Comment by ravirajn22** [comment]
Version 2.x.x is not longer supported, please upgrade to 3.x.x. timestamp is removed in latest version.

**Comment by lukebrandonfarrell** [comment]
There is no solution to this? This is a major drop in functionality, could you at least point us in the right direction @ravirajn22  ?
