### ISSUE TITLE
How to not save images but get base64?

### ISSUE THREAD

**Issue by taehoon719** [react-native-image-picker/react-native-image-picker#1434]
I'm trying to just get images (base64) but doesn't want to save images. I using it for both ios and android and I don't want any pictures to be saved.

* React Native version: 0.62.2
* Platform: both
* Development Operating System: MaxOS
* Dev tools: Android Studio version = 3.6.1, Xcode= 11.4.1

**Comment by ravirajn22** [comment]
If possible can you migrate to using version 3.0.0-vnext.1 https://github.com/react-native-image-picker/react-native-image-picker/releases/tag/v3.0.0-vnext.1

Check if your issue is solved.
Check 3.x.x docs for installation and API changes.

**Comment by ravirajn22** [comment]
I hope the issue is solved, if not reply here or create new issue with details I am happy to fix it.
