### ISSUE TITLE
Please merge pull request (converting option .mov to .mp4 for ios)

### ISSUE THREAD

**Issue by adriantabirta** [react-native-image-picker/react-native-image-picker#1437]
### Description

There is a pull request with .mov to .mp4 convert option, please review it and merge. It is a feature that everybody is missing. I have to convert it on server side (kind a hard to do and require extra work) or use another lib on client.
PLEASE MERGE PULL REQUEST

**Comment by ravirajn22** [comment]
Sorry this feature cannot be supported for now.

**Comment by ettingshausen** [comment]
@ravirajn22 There are some PRs implements this feature but no one of them merged. Any reason ?

**Comment by afilp** [comment]
Is there a way to not accept .mov files and only accept .mp4?

Thanks.

**Comment by nica0012** [comment]
Any update here? MOV files not being supported makes this package not usable right now on IOS
