### ISSUE TITLE
In Ios ,picker is opening the keybord

### ISSUE THREAD

**Issue by Tharinducs** [react-native-image-picker/react-native-image-picker#1442]
After picking or taking an image through the picker it makes the keyboard visible for the first time?

**Comment by systemride** [comment]
This isn't necessarily a fix, but I use react-navigation and I had a screen with a TextInput that came before my screen with the image picker. If I add a `Keyboard.dismiss()` when I submit the text, this prevented it from coming back.

**Comment by Johan-dutoit** [comment]
I'm not convinced this is related to the image picker.  Most likely that a text input (or something similar) is taking focus once the picker closes.

I don't see this behaviour in the iOS example app of 3.x.x.  Compare your code to the example app and if the issue perists, share reproducible code here.  Thanks.

**Comment by ravirajn22** [comment]
I hope the issue is solved, if not reply here or create new issue with details I am happy to fix it.

**Comment by wearedusa** [comment]
The same problem. I think `Keyboard.dismiss()` is not a good fix.

**Comment by kopax-polyconseil** [comment]
We have the same issue in our project. We do not have any input, we are just uploading an identity document.

When document is uploading, we render a `<Loader />` component , on top of it, we have eraticaly the keyboard showing up:

![image](https://user-images.githubusercontent.com/77674046/121383043-705df980-c947-11eb-9601-27be2e3252c2.png)

Could this be reopened?
