### ISSUE TITLE
When is android 29 compatible

### ISSUE THREAD

**Issue by Liangwenb** [react-native-image-picker/react-native-image-picker#1443]

**Comment by matamicen** [comment]
We ara facing the same problem ... in android 29 we can get the videos. Latitude error. May be we have to be patient, this is one of the best library. 

Matt.

**Comment by ravirajn22** [comment]
If possible can you migrate to using version 3.0.0-vnext.1 https://github.com/react-native-image-picker/react-native-image-picker/releases/tag/v3.0.0-vnext.1

Check if your issue is solved.
Check 3.x.x docs for installation and API changes.

**Comment by matamicen** [comment]
@ravirajn22 we will migrate and let you know the results asap. Thanks for your work guys. :)

**Comment by matamicen** [comment]
@ravirajn22 we got some manifest error:

`Error: Attribute provider#androidx.core.content.FileProvider@authorities value=(com.txtomobile.provider) from AndroidManifest.xml:10:19-66 is also present at AndroidManifest.xml:5:17-75 value=(com.txtomobile.imagepickerprovider). Suggestion: add 'tools:replace="android:authorities"' to <provider> element at AndroidManifest.xml:10:9-12:20 to override. txtoMobile-app debug manifest, line 9 Error: Attribute meta-data#android.support.FILE_PROVIDER_PATHS@resource value=(@xml/provider_paths) from AndroidManifest.xml:11:75-113 is also present at AndroidManifest.xml:6:75-125 value=(@xml/imagepicker_provider_paths). Suggestion: add 'tools:replace="android:resource"' to <meta-data> element at AndroidManifest.xml to override. txtoMobile-app debug manifest, line 10`

We don't know if we have to do [this](https://stackoverflow.com/questions/62564958/allow-fileprovider-content-provider-in-2-manifests) to fix it ? or may be is something that you guys should fix? we don't know becasue we don't have expierence in Android ... 

We are using **3.0.0-vnext.2**

thanks!

**Comment by ravirajn22** [comment]
@matamicen your issue is fixed. Test now from latest version.

**Comment by matamicen** [comment]
Thanks @ravirajn22 for this quick response :) ... we will try the latest version and then give some feedback to this community.

**Comment by vikjovanov** [comment]
Hi ! What do you mean by "When is android 29 compatible" ?
My users with recent android phones are unable to send images to my server. Is it due to the fact that the library does not support new android versions?

Thanks

**Comment by Liangwenb** [comment]
The pictures stored externally are in the android10 version and cannot be accessed using absolute paths. @vikjovanov

**Comment by matamicen** [comment]
@ravirajn22 Thanks for the fix, we installed 3.0.0-vnext.4 and it is working with no problems in both platforms (Android X and iOS 14.2) 

Thanks again!

**Comment by matamicen** [comment]
@Liangwenb You mean that the picker could not response the uri of the selected external picture or you can not access the file with the response uri of the library? 

Thnaks.

**Comment by ugrdursun** [comment]
Hello, is there a way to fix it without upgrading to v3 ?

**Comment by bobananto24** [comment]
I did post-install steps for ios but for android, there is nothing provided in the GitHub docs.
In my ios simulator, the "launchImageLibrary" method works perfectly fine (as "launchCamera" will not work on the simulator).
But when it comes to my android (running android 10) it shows error like "TypeError: null is not an object (evaluating '_reactNative.NativeModules.ImagePickerManager.launchImageLibrary')"
 And this is my AndroidManifest.xml file:

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.imgpick">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme"
      android:requestLegacyExternalStorage="true">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>

What should I do to correct this issue

**Comment by carlosrodrigues94** [comment]
> I did post-install steps for ios but for android, there is nothing provided in the GitHub docs.
> In my ios simulator, the "launchImageLibrary" method works perfectly fine (as "launchCamera" will not work on the simulator).
> But when it comes to my android (running android 10) it shows error like "TypeError: null is not an object (evaluating '_reactNative.NativeModules.ImagePickerManager.launchImageLibrary')"
> And this is my AndroidManifest.xml file:
> 
> ```
> <uses-permission android:name="android.permission.INTERNET" />
> <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
> <uses-permission android:name="android.permission.CAMERA" />
> <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
> 
> <application
>   android:name=".MainApplication"
>   android:label="@string/app_name"
>   android:icon="@mipmap/ic_launcher"
>   android:roundIcon="@mipmap/ic_launcher_round"
>   android:allowBackup="false"
>   android:theme="@style/AppTheme"
>   android:requestLegacyExternalStorage="true">
>   <activity
>     android:name=".MainActivity"
>     android:label="@string/app_name"
>     android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
>     android:launchMode="singleTask"
>     android:windowSoftInputMode="adjustResize">
>     <intent-filter>
>         <action android:name="android.intent.action.MAIN" />
>         <category android:name="android.intent.category.LAUNCHER" />
>     </intent-filter>
>   </activity>
>   <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
> </application>
> ```
> 
> What should I do to correct this issue

Hello bobananto24, have you figer out how to solve this problem? im having the same error on my app and don´t know why..

**Comment by ravirajn22** [comment]
Version 2.x.x is not longer supported, please upgrade to 3.x.x
