### ISSUE TITLE
Possible enhancement on opening the camera.

### ISSUE THREAD

**Issue by Joachimzeelmaekers** [react-native-image-picker/react-native-image-picker#1444]
I was wondering if it would be possible to introduce a property to cancel out all pointer-events on opening the camera using `ImagePicker.launchCamera()`.

The reason for this, is when we try and take multiple pictures in a row the camera opens and closes. 
This open and close animation shows the UI for half a second, where the user can accidently click on the eg: `back button`.
Doing this could possibly introduce bugs in apps, where we sometimes get errors with the paths of the images or functions are being canceled.

Do you think this should be part of the plug-in or handle separately? 

Thanks in advance!

**Comment by ravirajn22** [comment]
I don't think the library might be able to handle your use case.
