### ISSUE TITLE
Relative path is being given for android Instead of absolute path 

### ISSUE THREAD

**Issue by surajl11** [react-native-image-picker/react-native-image-picker#1445]
In Android when u choose a photo from  gallery,it returns the relative path which is difficult to upload instead of absolute path ,please help....

**Comment by ravirajn22** [comment]
If possible can you migrate to using version 3.0.0-vnext.1 https://github.com/react-native-image-picker/react-native-image-picker/releases/tag/v3.0.0-vnext.1

Check if your issue is solved.
Check 3.x.x docs for installation and API changes.

**Comment by ravirajn22** [comment]
I hope the issue is solved, if not reply here with details I am happy to fix it.
