### ISSUE TITLE
Permissions error in android

### ISSUE THREAD

**Issue by puneetkansal04** [react-native-image-picker/react-native-image-picker#1447]
permission denial reading com.google.android.apps.photos.contentprovider.impl.mediacontentprovide

I am getting this error in android but in ios it is working fine.Please provide a solution

**Comment by Loown** [comment]
Same problem here

**Comment by Loown** [comment]
```
ImagePicker Error:
1
/storage/emulated/0/Pictures/Screenshots/Screenshot_20201021_152405_com.discord.jpg: open failed: EACCES (Permission denied)
```

Followed installation steps : https://github.com/react-native-image-picker/react-native-image-picker/blob/master/docs/Install.md

Like @puneetkansal04 works fine on iOS but got this error on Android

**Comment by ravirajn22** [comment]
If possible can you migrate to using version 3.0.0-vnext.1 https://github.com/react-native-image-picker/react-native-image-picker/releases/tag/v3.0.0-vnext.1

Check if your issue is solved.
Check 3.x.x docs for installation and API changes.

**Comment by usamaehsan** [comment]
@Loown  Add this permission in your manifest file inside application tag
android:requestLegacyExternalStorage="true"

**Comment by nicholasess** [comment]
@usamaehsan thanks so much, it works

**Comment by sadikyalcin** [comment]
> @Loown Add this permission in your manifest file inside application tag
> android:requestLegacyExternalStorage="true"

Note that this will be removed on `SDK 30`. Not a permanent solution.

**Comment by GunnarAK** [comment]
Adding to @sadikyalcin's comment:
Android docs about `android:requestLegacyExternalStorage`
https://developer.android.com/training/data-storage/use-cases#opt-out-scoped-storage

**Comment by BravenxX** [comment]
> @Loown Add this permission in your manifest file inside application tag
> android:requestLegacyExternalStorage="true"

Didn't work for me

**Comment by yalcinozer** [comment]
So I think, downgrading target sdk version anything below 29 is a good solution;
android/build.gradle:

targetSdkVersion=28

This solved my problem on android 10.

> Adding to @sadikyalcin's comment:
> Android docs about `android:requestLegacyExternalStorage`
> https://developer.android.com/training/data-storage/use-cases#opt-out-scoped-storage

**Comment by ravirajn22** [comment]
Version 2.x.x is not longer supported, please upgrade to 3.x.x
