### ISSUE TITLE
Being able to skip the photo validation

### ISSUE THREAD

**Issue by benjaminaudet** [react-native-image-picker/react-native-image-picker#1448]
### Description
When you take a picture with the launchCamera() function, you can see you picture taken with 2 buttons (one cross to cancel and one checkmark to validate). Is there a possibility to skip this step during the photo shooting ?

### How to repeat issue and example
* take a picture with launchCamera function
* You're now on the view I'm talking about

### Solution

Have the possibility to pass a boolean into the options arguments of launchCamera function to disable this step

### Additional Information

* React Native version: 0.63.2
* Platform: both
* Development Operating System: MacOS
* Dev tools: Xcode: 12.0.1, Android studio : Android Studio 4.0, build AI-193.6911.18.40.6514223.

Thanks in advance ;)

**Comment by ravirajn22** [comment]
Not possible.
