### ISSUE TITLE
Android 11 Cannot launch camera, photo library

### ISSUE THREAD

**Issue by MacMillan133** [react-native-image-picker/react-native-image-picker#1449]
In android 11 don't work photo library and camera.

Did somebody fix it? Thanks.

**Comment by Sebosam** [comment]
Try to add queries it worked in my case. https://github.com/react-native-image-picker/react-native-image-picker/issues/1393#issuecomment-713299590

**Comment by MacMillan133** [comment]
> Try to add queries it worked in my case. [#1393 (comment)](https://github.com/react-native-image-picker/react-native-image-picker/issues/1393#issuecomment-713299590)

Thanks for your answer. I have tried to add `<queries>` between `<intent-filter>`, but got the error ` unexpected element <queries>` when run-android. In which place of manifest did you add `<queries>`?

**Comment by MacMillan133** [comment]
> Try to add queries it worked in my case. [#1393 (comment)](https://github.com/react-native-image-picker/react-native-image-picker/issues/1393#issuecomment-713299590)

Thanks, that's work!

**Comment by ujujjwal** [comment]
Thanks, Man! It worked.

**Comment by Sasha411** [comment]
> Try to add queries it worked in my case. [#1393 (comment)](https://github.com/react-native-image-picker/react-native-image-picker/issues/1393#issuecomment-713299590)

Can you be more specific just got to know about this library and I am facing the same issue.
