### ISSUE TITLE
launchImageLibrary Not working on vvnext.1

### ISSUE THREAD

**Issue by traxx10** [react-native-image-picker/react-native-image-picker#1452]
### Description
Explain the bug in as much detail as possible

launchImageLibrary always launching camera instead of image gallery

### How to repeat issue and example
* step to reproduce the issue
* ...

### Solution
![Screenshot 2020-10-29 at 14 50 06](https://user-images.githubusercontent.com/31565764/97582644-4712dd80-19f6-11eb-8e4f-86f233aa7939.png)

Please update the index.ts file to point to launchImageLibrary instead

What needs to be done to address this issue? 

### Additional Information

* React Native version: [FILL THIS OUT: Be specific, filling out "latest" here is not enough.]
* Platform: [FILL THIS OUT: iOS, Android, or both?]
* Development Operating System: [FILL THIS OUT: Are you developing on MacOS, Linux, or Windows?]
* Dev tools: [FILL THIS OUT: Xcode or Android Studio version, iOS or Android SDK version, if applicable] navigation crash for Android

**Comment by ravirajn22** [comment]
Thanks for the report, fixed in master vnext.
