### ISSUE TITLE
LaunchImageLibrary returns 'camera_unavailable' using an iOS simulator

### ISSUE THREAD

**Issue by stuki** [react-native-image-picker/react-native-image-picker#1453]
### How to repeat issue and example

We implement this library as this in our app:

```
import {
    CameraOptions,
    ImagePickerResponse,
    launchCamera,
    launchImageLibrary,
} from "react-native-image-picker";
import { askCameraPermission, askPhotoPermission } from "./permissions";

const options: CameraOptions = {
    mediaType: "photo",
    maxHeight: 1600,
    maxWidth: 1600,
    includeBase64: true,
    quality: 0.8,
};

export async function openCamera(callback: (response: ImagePickerResponse) => void) {
    const hasPermission = await askCameraPermission();

    if (hasPermission) {
        launchCamera(options, callback);
    }
}

export async function openPhotoLibrary(callback: (response: ImagePickerResponse) => void) {
    const hasPermission = await askPhotoPermission();

    if (hasPermission) {
        launchImageLibrary(options, callback);
    }
}
```

Calling `await openImageLibrary((response) => {})` returns a response object of `{ errorCode:'camera_unavailable }`. Camera should not be required to browse images on simulator.

### Solution

Image gallery should open when calling `launchImageLibrary()` on simulators

### Additional Information

* React Native version: 0.63
* Platform: ios
* Development Operating System: macos
* Dev tools: iOS 14.1 Simulator

**Comment by ravirajn22** [comment]
Thanks for the report, fixed in master vnext.

**Comment by ravirajn22** [comment]
@Johan-dutoit we need to release a new version

**Comment by Johan-dutoit** [comment]
Check out the latest version ([3.0.0-vnext.1](https://github.com/react-native-image-picker/react-native-image-picker/releases/tag/3.0.0-vnext.2)).  If this doesn't resolve your issue, please feel free to reopen.
