### ISSUE TITLE
Opening image library without all settings defined in Android simulator crashes app

### ISSUE THREAD

**Issue by stuki** [react-native-image-picker/react-native-image-picker#1454]
### How to repeat issue and example

```
const options = {
};


launchImageLibrary(options, response => {});
```

![Screenshot_1603980998](https://user-images.githubusercontent.com/1611640/97585852-4122f980-1a02-11eb-8f41-4de56800cbbf.png)

### Additional Information

* React Native version: 0.63
* Platform: Android
* Development Operating System: macos
* Dev tools: android simulator, android 7.1.1

**Comment by Johan-dutoit** [comment]
version of the image picker?

**Comment by stuki** [comment]
3.0.0-vnext.1

**Comment by ravirajn22** [comment]
@stuki I am not able to reproduce this on master vnext. Please check again.

**Comment by stuki** [comment]
Yeah, I figured it out, I had swapped out launchImageLibrary with NativeModules.ImagePickerManager.launchImageLibrary because of #1453
