### ISSUE TITLE
(3.0.0-vnext.1) permission Denial (requires the provider to be exported, or grantUriPermission())

### ISSUE THREAD

**Issue by mtford90** [react-native-image-picker/react-native-image-picker#1457]
### Description

Error when picking from Image library.

![Screenshot_1604051330](https://user-images.githubusercontent.com/1734057/97690902-893f2c00-1a95-11eb-8150-9246d6673022.png)

### How to repeat issue and example

Call `ImagePicker.launchImageLibrary` on Android

Permissions:

```
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
```

Also added:

```
android:requestLegacyExternalStorage="true"
```

But no luck... using the camera works fine though.

### Solution

No idea.

### Additional Information

* Image Picker version: 3.0.0-vnext.1
* React Native version: 0.63.3
* Platform: Android
* Development Operating System: OSX
* Dev tools: 
```
        buildToolsVersion = "29.0.2"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
```

**Comment by Johan-dutoit** [comment]
See [Breaking Changes](https://github.com/react-native-image-picker/react-native-image-picker/releases/tag/v3.0.0-vnext.1).

**Comment by ravirajn22** [comment]
@mtford90 Try this in latest vnext version. Post if you still get an error.
