### ISSUE TITLE
Remove buildToolsVersion from build.gradle or provide default

### ISSUE THREAD

**Issue by scousino** [react-native-image-picker/react-native-image-picker#1458]
### Description
Remove buildToolsVersion from the build.gradle. According to this [documentation](https://developer.android.com/studio/releases/gradle-plugin.html#3-1-0), after 3.1.0 the plugin automatically picks a version.

However, if its necessary to keep, then you should provide a default value as well as the extension. Here is an example of how you would do that:

![image](https://user-images.githubusercontent.com/8717527/97750358-ffa85200-1ac6-11eb-89ea-d4e69e6cb3fb.png)

This package will break builds on projects that do not specify a buildToolsVersion in their build.gradle ext section.

### How to repeat issue and example
* Install package in react native project
* Don't specify buildToolsVersion in the build.gradle ext section of that project
* Build fails

### Solution

Remove buildToolsVersion or specify a default fallback value.

### Additional Information

* Image Picker version: 3.0.0-vnext.2
* React Native version: 0.62.2
* Platform: Android
* Development Operating System: Windows

**Comment by scousino** [comment]
It looks like in version 2.3.4, this default functionality was in place.

**Comment by Johan-dutoit** [comment]
@scousino can you test directly from GH using the vnext branch?

**Comment by scousino** [comment]
@Johan-dutoit tested and works

**Comment by Johan-dutoit** [comment]
Thanks @scousino.
