### ISSUE TITLE
Take picture doesn`t work

### ISSUE THREAD

**Issue by ksielyov** [react-native-image-picker/react-native-image-picker#1459]
import ImagePicker from 'react-native-image-picker';

const CameraGallery = () => {
    // More info on all the options is below in the API Reference... just some common use cases shown here
    const options = {
        title: 'Select Avatar',
        // customButtons: [{name: 'fb', title: 'Choose Photo from Facebook'}],
        storageOptions: {
            skipBackup: true,
            path: 'images',
        },
    };

    /**
     * The first arg is the options object for customization (it can also be null or omitted for default options),
     * The second arg is the callback which sends object: response (more info in the API Reference)
     */
    ImagePicker.showImagePicker(options, (response) => {
        console.log('Response = ', response);

        if (response.didCancel) {
            console.log('User cancelled image picker');
        } else if (response.error) {
            console.log('ImagePicker Error: ', response.error);
        } else {
            const source = {uri: response.uri};

            // You can also display the image using data:
            // const source = { uri: 'data:image/jpeg;base64,' + response.data };

            this.setState({
                avatarSource: source,
            });
        }
    });
};

export default CameraGallery;

Error screen => https://prnt.sc/van8j8

**Comment by ksielyov** [comment]
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          package="com.languagenow">

    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.CAMERA"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

    <application
            android:name=".MainApplication"
            android:label="@string/app_name"
            android:icon="@mipmap/ic_launcher"
            android:roundIcon="@mipmap/ic_launcher_round"
            android:allowBackup="false"
            android:usesCleartextTraffic="true"
            android:theme="@style/AppTheme">
        <activity
                android:name=".MainActivity"
                android:label="@string/app_name"
                android:configChanges="keyboard|keyboardHidden|orientation|screenSize|uiMode"
                android:launchMode="singleTask"
                android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <activity android:name="com.facebook.react.devsupport.DevSettingsActivity"/>
    </application>

</manifest>

**Comment by ksielyov** [comment]
https://prnt.sc/vandei

**Comment by ksielyov** [comment]
Don`t work in any case

**Comment by mopilo** [comment]
see this https://github.com/react-native-image-picker/react-native-image-picker/issues/1447#issuecomment-718685230

**Comment by Pragnesh-Dharajiya** [comment]
**I was able to fix it by adding android:requestLegacyExternalStorage="true" to application tag in AndroidManifest.xml file** @ksielyov

**Comment by Johan-dutoit** [comment]
Please try [3.0.0-vnext.3](https://github.com/react-native-image-picker/react-native-image-picker/releases/tag/3.0.0-vnext.3).  If the issue persists, feel free to reopen.
