### ISSUE TITLE
Error when pressing BACK button even though the image selection was not activated

### ISSUE THREAD

**Issue by rvgroup** [react-native-image-picker/react-native-image-picker#1461]
### Description
ImagePickerModule.onActivityResult handler fires even if there was no call to select the image picker function

The error is similar
https://github.com/react-native-image-picker/react-native-image-picker/issues/713

### How to repeat issue and example
1) Call the document picker from another library (for example, react-native-document-picker).
2) Click Back
3) We get an error in our module 

### Solution

ImagePickerModule.onActivityResult handler should only work if the image selection from our module is active

### Additional Information

* Image Picker version: 3.0.0-vnext.2
* React Native version: 0.63.3
* Platform: Android
* Development Operating System: Windows 10
* Dev tools: VSCode

**Comment by Johan-dutoit** [comment]
Closing issue.  Will release fix in 3.0.0-vnext.3
