### ISSUE TITLE
Example App needs permissions setup on Android

### ISSUE THREAD

**Issue by scousino** [react-native-image-picker/react-native-image-picker#1465]
### Description
The example app does not currently work on android, because requesting permissions was removed from the API calls.

### How to repeat issue and example
* Run example app on android

### Solution
Add permissions requesting logic on Android

### Additional Information

* Image Picker version: 3.0.0-vnext.2
* React Native version: 0.62.2
* Platform: Android
* Development Operating System: Windows

**Comment by ravirajn22** [comment]
Just go to Android settings and enable manually for time being.

**Comment by Johan-dutoit** [comment]
I've nearly got a PR ready that updates the examples to cover real usages.  Watch this space.

**Comment by Johan-dutoit** [comment]
Example update, but no permissions required with latest [3.0.0-vnext.3](https://github.com/react-native-image-picker/react-native-image-picker/releases/tag/3.0.0-vnext.3).  If the issue persists, feel free to reopen.
