### ISSUE TITLE
Feature request for next: launchCamera for vertical images

### ISSUE THREAD

**Issue by jladuval** [react-native-image-picker/react-native-image-picker#1466]
I've been using the v1next project image picker and it's great! I would love to use launchCamera too but I need to take vertical images instead of horizontal ones. Is this possible already? If not it would be a great feature!

**Comment by ravirajn22** [comment]
I don't understand by what you mean vertical and horizontal images. 

FYI, this library does not access camera API directly instead delegates it to the default Camera app. So you should probably be able to take any image.

**Comment by jladuval** [comment]
Ok this could be my phone (Pixel 3). It seems like the orientation is off by 90 degrees. If I open the camera holding the phone vertically and take a photo vertically then the image comes out horizontal (width larger than length). If I flip my phone 90 degrees then take the image it comes out vertically (length larger than width). 

Perhaps this is related to #1338 and I should close this issue.

**Comment by ravirajn22** [comment]
pixel android version

**Comment by jladuval** [comment]
Android version 11 (Kernel version 4.9.223)

**Comment by KeitelDOG** [comment]
Hi. How did you manage to get it to work with NextJS. I'm using React Native  with RN Web + NextJS, with next config. So far every complicated things have worked. But this package, with this import on Typescript `export * from './types';` can't work. I'm not using typescript yet. Do I need to install Typescript to get the Types?
