### ISSUE TITLE
[Android] getting errorCode: "permission"

### ISSUE THREAD

**Issue by SamiChab** [react-native-image-picker/react-native-image-picker#1468]
### Description
On Android, I request the following permissions with `react-native-permissions`:
- CAMERA
- READ_EXTERNAL_STORAGE

When I call `launchImageLibrary` or `launchCamera`, I always get following response in callback:
`errorCode: "permission"`

herer are the function calls:
```
launchCamera({mediaType: 'photo', saveToPhotos: false, includeBase64: true, quality: 0.5}, this.onImageSelected)
launchImageLibrary({mediaType: 'photo', includeBase64: true, quality: 0.5}, this.onImageSelected)
```

I have added the required permissions in my AndroidManifext.xml:
```
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
```

### Additional Information

* Image Picker version: 3.0.0-vnext.2
* React Native version: 0.62.2
* Platform: Android
* Development Operating System: MacOS
* Dev tools: I've tested it on Android 11 and 8.1 devices, got the same error.

Please help!

**Comment by ravirajn22** [comment]
In version 3.0.0-vnext.2 WRITE_EXTERNAL_STORAGE for android is just enough. No need for CAMERA and READ_EXTERNAL_STORAGE. Check the docs. Post if it is not clear in the docs, I will try to update it.

**Comment by Johan-dutoit** [comment]
Please try [3.0.0-vnext.3](https://github.com/react-native-image-picker/react-native-image-picker/releases/tag/3.0.0-vnext.3).  If the issue persists, feel free to reopen.

**Comment by scousino** [comment]
> 
> 
> In version 3.0.0-vnext.2 WRITE_EXTERNAL_STORAGE for android is just enough. No need for CAMERA and READ_EXTERNAL_STORAGE. Check the docs. Post if it is not clear in the docs, I will try to update it.

This is not true, I'm running 3.0.0-vnext.3, and tried to launch the camera. You get a permission denial on android.

**Comment by Johan-dutoit** [comment]
I was also surprised (perhaps there will be edge cases), but can confirm this is the case.
The example app runs without any additional permissions requests.

Would be best to compare it to your project (specifically the manifest file).
