### ISSUE TITLE
When selecting image from library on Android, uri is wrong.

### ISSUE THREAD

**Issue by malgorzatamaz** [react-native-image-picker/react-native-image-picker#1470]
### Description
I'm not sure what's wrong, but when selecting image from my Samsung s20 gallery, uri from callback does not present anything in Image component. It works perfectly with camera and selecting form Google Photos app.

### How to repeat issue and example
* Use `launchImageLibrary({ mediaType: 'photo' }, imagePickerCallback)`
* It returns uri like `content://media/external/images/media/2354`
* Tried also with base64, still does not work.
* It worked on version 2.3.1 with showImagePicker

### Solution
Let me know what should I do to have proper uri returned.

### Additional Information

* Image Picker version: 3.0.0-vnext.3
* React Native version: 0.63.2
* Platform: Android
* Development Operating System: MacOS
* Dev tools: Visual Studio Code, Android SDK: 10

**Comment by ravirajn22** [comment]
What uri are you getting in version 2.3.1 for the same file? For testing purpose don't use any other option other than `mediaType: 'photo'`.

I have tested this in samsung phone and picking from gallery it seems to work.

**Comment by malgorzatamaz** [comment]
Strange, but when juggling through versions I started to work! :) Probably some issue with modules in my app.

Thanks for help :)

**Comment by malgorzatamaz** [comment]
I just tested it on apk, and it still not work for release version.

This is what both version returns:

2.3.1
`{data: "/9j/4d1uRXhpZgAASUkqAAgAAAANAAABBAABAAAAwA8AAAEBBA…” fileName: "20201102_131051.jpg",  fileSize: 2417061,  height: 2268,  isVertical: false, latitude: 49.67026901245117,  longitude: 19.22437286376953,  originalRotation: 90 ,path: "/storage/emulated/0/DCIM/Camera/20201102_131051.jpg",  timestamp: "2020-11-02T12:10:52Z" , type: "image/jpeg" , uri: "content://media/external/images/media/2354, " width: 4032 }`

3.0.0-vnext.3
`{fileName: "20201102_131051.jpg" , fileSize: 2417061 height: 2268,  type: "image/jpeg" , uri: "content://media/external/images/media/2354, " width: 4032}`

and uri is the same 🙈

**Comment by malgorzatamaz** [comment]
And again I found solution. Image was too big!

**Comment by nguyenhoanglam** [comment]
@malgorzatamaz please tell me your solution with code! thanks a lot!

**Comment by malgorzatamaz** [comment]
@nguyenhoanglam I think that I changed this in build.gradle 
`com.android.tools.build:gradle:3.5.2`
