### ISSUE TITLE
Support Autolinking

### ISSUE THREAD

**Issue by scousino** [react-native-image-picker/react-native-image-picker#1471]
### Description

This package's documentation implies that if you're using a RN version above 0.60, it supports autolinking. However, this is not the case. This package will not work on Android unless you run react-native link react-native-image-picker.

There is a similar issue with 3.0.0-vnext.3 right now I believe, where all calls to launchCamera and launchImageLibrary throw an error saying both of the native functions are null.

### How to repeat issue and example
1. Create a new react native project
2. Install and use react-native-image-picker (DO NOT RUN react-native link)

### Solution

Change the documentation, or support auto linking.

### Additional Information

* Image Picker version: 2.3.4 & 3.0.0-vnext.3
* React Native version: 0.62.2
* Platform: Android

**Comment by scousino** [comment]
The example app is even setup via a manual link: 
![image](https://user-images.githubusercontent.com/8717527/98006192-f1f11600-1dbf-11eb-94b1-7dcc11c672e9.png)

**Comment by ravirajn22** [comment]
This package uses autolink.

Don't compare it with example app inside this repo, that uses files from local folder not from node_modules. You have confused somewhere.

I tried in a fresh project auto link is working properly.
