### ISSUE TITLE
Returned image uri produces security exception on Android

### ISSUE THREAD

**Issue by vorlovsky** [react-native-image-picker/react-native-image-picker#1473]
# Description

The uri returned from Google Photos app can't be used due to security restrictions

There are two responses returned for the same file (note the URIs):
from Google Photos:
`{"fileName": "20201104_185129.jpg", "fileSize": 4044295, "height": 2988, "isVertical": false, "originalRotation": 90, "path": "/storage/emulated/0/DCIM/Camera/20201104_185129.jpg", "timestamp": "2020-11-04T16:51:29Z", "type": "image/jpeg", "uri": "content://com.google.android.apps.photos.contentprovider/-1/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F630/ORIGINAL/NONE/image%2Fjpeg/1388424768", "width": 5312}`

from a third-party app: 
`{"fileName": "20201104_185129.jpg", "fileSize": 4044295, "height": 2988, "isVertical": false, "originalRotation": 90, "path": "/storage/emulated/0/DCIM/Camera/20201104_185129.jpg", "timestamp": "2020-11-04T16:51:29Z", "type": "image/jpeg", "uri": "content://media/external/images/media/630", "width": 5312}`

### How to repeat issue and example

(The same problem was mentioned in the issue #1380)
Steps:
1. Call `ImagePicker.showImagePicker` in your code
2. Select an image using Google Photos (!)
3. Try to access the selected image file by the returned URI

Result:
an error
`Permission Denial: reading com.google.android.apps.photos.contentprovider.MediaContentProvider uri content://com.google.android.apps.photos.contentprovider/-1/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F630/ORIGINAL/NONE/image%2Fjpeg/1388424768 from pid=18891, uid=10128 requires the provider be exported, or grantUriPermission()`

### Solution

I've not digging deep into it, just noted and wish to inform you so you'll be able to handle it somehow.
I'll try to use path value instead of uri value.

### Additional Information

* React Native version: 0.63.2
* Platform: Android
* Development Operating System: Windows
* Dev tools: Android SDK version 29

**Comment by ravirajn22** [comment]
Check the breaking changes and upgrade to version 3.0.0-vnext.4
