### ISSUE TITLE
Failed on oppening photo camera (Android)

### ISSUE THREAD

**Issue by hiagoLF** [react-native-image-picker/react-native-image-picker#1474]
### Description

When I call ImagePicker.launchCamera() it does not open in photo option but in video option it woks as well.
.
### Additional Information

* React Native version: 0.63.3
* Platform: Android
* Development Operating System: Windows 10
* Dev tools: VScode

**Comment by ravirajn22** [comment]
Require library version, mobile OS version, and your code to debug.

**Comment by tamacroft** [comment]
me too, I think need to permission access camera. In version 2 is built in permission access pop up. But in version 3 did not show up pop up permission.

**Comment by ravirajn22** [comment]
Version 2.x.x is not longer supported, please upgrade to 3.x.x
I hope the issue is solved, if not reply here or create new issue with details I am happy to fix it.
