### ISSUE TITLE
EACCES (Permission denied) launchImageGallery Android

### ISSUE THREAD

**Issue by GunnarAK** [react-native-image-picker/react-native-image-picker#1475]
### Description
I am testing with my OnePlus 6 and tried picking the same image with all my suggested apps (OnePlus' gallery app & Google Photos). Rendering only functions properly for the Google Photos' attempt.
I have tested with both storage-permission enabled & disabled, both give same result. 
Manifest includes `WRITE_EXTERNAL_STORAGE`.
Things work as expected for `launchCamera()` with same options.

Error:
`nativeEvent:
error: "/storage/emulated/0/WhatsApp/Media/WhatsApp Images/IMG-20201104-WA0003.jpg: open failed: EACCES (Permission denied)`

It does not have anything to do with the space in the pathname. Other attempt: `/storage/emulated/0/DCIM/Camera/IMG_20201024_233443.jpg: open failed: EACCES (Permission denied)`

Component-state:
```
imageSource:
0:
  fileName:"IMG-20201104-WA0003.jpg"
  fileSize:129868
  height:805
  type:"image/jpeg"
  uri:"content://media/external/images/media/152634"
  width:580
1:
  fileName:"IMG-20201104-WA0003.jpg"
  fileSize:129868
  height:805
  type:"image/jpeg"
  uri:"content://com.google.android.apps.photos.contentprovider/0/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F152634/ORIGINAL/NONE/image%2Fjpeg/1086794781"
  width:580
```

### How to repeat issue and example
* Launch image library picker:
```
launchImageLibrary(
  {
    mediaType: "photo"
  },
  (response: ImagePickerResponse) => {
    this.processImageReponse(response);
  }
);
```
* Choose "Google Photos"-option for picking an image.
* Repeat for other Gallery-apps such as OnePlus' native Gallery app (https://play.google.com/store/apps/details?id=com.oneplus.gallery)
* Render preview:
```
<Image
  style={{
    height: 90,
    width: 120,
    backgroundColor: "#ccc"
  }}
  source={{ uri: item.uri }}
  onLoadEnd={() => console.warn("onLoadEnd")}
  fadeDuration={0}
  onError={e => {
    e.persist();
    console.error("Error loading marker image", e);
  }}
/>
```

### Additional Information

* Image Picker version: `3.0.0-vnext.3`
* React Native version: `0.61.5`
* Platform: Android API 29
* Development Operating System: MacOS
* Android SDK Platfom-tools: 30.0.4
* Android SDK Tools: 26.1.1

**Comment by ravirajn22** [comment]
Where is this error coming, while using it in `<Image>` component or while selecting the image via gallery app?

Is selecting the image using google photos working properly?

Is the app crashing or just the error is logged?

**Comment by joshjo** [comment]
I faced the same problem, but I fixed with:

https://github.com/react-native-image-picker/react-native-image-picker/issues/1447#issuecomment-721520908

**Comment by A-Tokyo** [comment]
@joshjo's fix works! 💪

**Comment by VBSwebs** [comment]
Add this permission in your manifest file inside application tag
android:requestLegacyExternalStorage="true"

**Comment by GunnarAK** [comment]
Adding `android:requestLegacyExternalStorage="true"` is not a solid fix, unless you don't care about Android 11..

From Google's docs:
> Caution: After you update your app to target Android 11 (API level 30), the system ignores the requestLegacyExternalStorage attribute when your app is running on Android 11 devices, so your app must be ready to support scoped storage and to migrate app data for users on those devices.

https://developer.android.com/training/data-storage/use-cases#opt-out-scoped-storage

**Comment by ram95krishh** [comment]
android:requestLegacyExternalStorage="true" fixes the permission issue, however files that we capture using `launchCamera()` have started getting saved in the Gallery which is something I was specifically trying to avoid. Any suggestion on avoiding that would help! Thanks in advance!

**Comment by ravirajn22** [comment]
Fixed in latest version
