### ISSUE TITLE
ReactNative app when compiled for Mac gets error AssetsLibrary is deprecated

### ISSUE THREAD

**Issue by mihir-mehta** [react-native-image-picker/react-native-image-picker#1476]
### Description

I am trying to build app for for mac platform which is built on react-native platform. while compiling the code i am getting error.

The app is already build for iPad and working fine 

> AssetsLibrary is deprecated and is not available when building for Mac Catalyst.Consider migrating to Photos instead, or 

> use #if !TARGET_OS_MACCATALYSTto conditionally import this framework, first

> importing TargetConditionals.h if necessary.

I am getting this error in react-native-image-picker => ImagePickerManager.m

On this line

> #import <AssetsLibrary/AssetsLibrary.h>

I am using Xcode 12.1.1 mac target is 10.15

### How to repeat issue and example

Create react-native app and enable Mac platform from Xcode 

### Solution

Need to replace deprecated AssetLibrary 

### Additional Information

* Image Picker version:  2.3.4
* React Native version: 0.63.2
* Platform: iOS and Mac
* Development Operating System: Mac OS 10.15.7
* Dev tools: Xcode 12.1.1

**Comment by ravirajn22** [comment]
Check the breaking changes and upgrade to version 3.0.0-vnext.4

If you still get the error ping here.

**Comment by marcosrdz** [comment]
Getting this error on 3.0.1

**Comment by marcosrdz** [comment]
https://github.com/react-native-image-picker/react-native-image-picker/pull/1534
