### ISSUE TITLE
TypeError: Cannot read property 'launchImageLibrary' of undefined, js engine: v8

### ISSUE THREAD

**Issue by tamacroft** [react-native-image-picker/react-native-image-picker#1477]
**ERROR**
I have problem using this lib, how to fix it ? 
Current version is **3.0.0-vnext.3**

Btw I'm using RN 0.63.3 with react-native-v8

![photo_2020-11-05_16-25-08](https://user-images.githubusercontent.com/11469684/98222593-9a9ba300-1f83-11eb-9e39-195ffce67538.jpg)

**Comment by tamacroft** [comment]
solved with replace **import ImagePicker from 'react-native-image-picker'** to **import {launchImageLibrary} from 'react-native-image-picker'**

**Comment by BravenxX** [comment]
This works for launchCamera too. Thanks.

**Comment by DNA-h** [comment]
@tamacroft Thanks saved me some precious time. I think this should be added to documentation too, since it is very vague.

**Comment by YuKitAs** [comment]
> solved with replace **import ImagePicker from 'react-native-image-picker'** to **import {launchImageLibrary} from 'react-native-image-picker'**

this doesn't work for me. Then I got the error `Cannot read property 'launchImageLibrary' of undefined` from the module:
```
> 28 |   NativeModules.ImagePickerManager.launchImageLibrary(
  29 |     {...DEFAULT_OPTIONS, ...options},
  30 |     callback,
  31 |   );
```

**Comment by havinhthai** [comment]
> > solved with replace **import ImagePicker from 'react-native-image-picker'** to **import {launchImageLibrary} from 'react-native-image-picker'**
> 
> this doesn't work for me. Then I got the error `Cannot read property 'launchImageLibrary' of undefined` from the module:
> 
> ```
> > 28 |   NativeModules.ImagePickerManager.launchImageLibrary(
>   29 |     {...DEFAULT_OPTIONS, ...options},
>   30 |     callback,
>   31 |   );
> ```
> 
> I'm using version 3.1.4.

Run `npx pod-install` in ios folder resolved the problem with me.

**Comment by yogesh-badgujar** [comment]
at the place of 
import ImagePicker from 'react-native-image-picker';
replace 
var ImagePicker = require('react-native-image-picker');
and run the application again

**Comment by talhabinkhalil** [comment]
I followed the following steps
1.) removed permissions from AndroidManifest.xml (which i provided earlier while watching a tutorial)
2.) instead of  `import ImagePicker from 'react-native-image-picker';`  USE Following way to import Image `const ImagePicker = require('react-native-image-picker');`
it worked for me

**Comment by souhailtourjmen** [comment]
it worked for me

**Comment by Hedayet** [comment]
In my case restarting the emulator fixed this issue -`npm run android`
my current understanding from this experience is that, it needs a restart after installing the package ?
