### ISSUE TITLE
android.content.Intent.getData()' on a null object reference

### ISSUE THREAD

**Issue by 90Mark** [react-native-image-picker/react-native-image-picker#1478]
### Description

Android crashed ,when I used 
ImagePicker.launchCamera({}, (res) => {})
{ java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=13001, result=-1, data=null} to activity {xxxx.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri android.content.Intent.getData()' on a null object reference
}

### Solution

I read the source code, trying to remove  line 288 
 cameraIntent.putExtra(MediaStore.EXTRA_OUTPUT,cameraCaptureURI);
the program is normal

### Additional Information

* Image Picker version: 2.3.4
* React Native version: 0.61.5
* Platform:  Android
* Development Operating System: MacOS
* Dev tools: Android Studio 3.6.3

Hope to repair as soon as possible.

**Comment by ravirajn22** [comment]
Check the breaking changes and upgrade to version 3.0.0-vnext.4
