### ISSUE TITLE
Cannot render Image from uri return on Android >=10

### ISSUE THREAD

**Issue by tamacroft** [react-native-image-picker/react-native-image-picker#1482]
### Description

Cannot render Image from uri return on Android >=10, if I downgrade target version to 28, my other lib will be problem, I have to set android:requestLegacyExternalStorage="true" but still not work. (v3 vnext4)

### Additional Information

* React Native version: 0.63.3
* Platform :Android
* Development Operating System: MacOS
* Dev tools: -

**Comment by ravirajn22** [comment]
what is the error you are getting while rendering, check logcat and post it here.

**Comment by ravirajn22** [comment]
There is an issue in fresco library used by react-native image component https://github.com/facebook/fresco/issues/2455 which causes this issue.

Temporarily try adding `android:requestLegacyExternalStorage="true"` and READ_EXTERNAL_STORAGE (obtain the same)  permission.

I will post if any other info.

**Comment by tamacroft** [comment]
currently the solution is render using base64, not with url path. Thanks
