### ISSUE TITLE
showImagePicker opens empty picker on iOS 14+

### ISSUE THREAD

**Issue by akshitrcrm** [react-native-image-picker/react-native-image-picker#1483]
On iOS13 and android, it is working fine. But on iOS 14.1 simulator, i am not able to see any pictures it shows empty modal which i cant even close.

Using:
react-native 0.63.3
"react-native-image-picker": "^2.3.4",

![simulator_screenshot_9B863C79-26B7-4F2A-B137-D5F57C0ABB3C](https://user-images.githubusercontent.com/69840129/98652423-9bf11500-2361-11eb-969b-1ea15a69b584.png)

**Comment by akshitrcrm** [comment]
The app doesnt even ask for any permissions. And as per i have heard, iOS 14 brings even more restrictions on picking images from the photo library

**Comment by Johan-dutoit** [comment]
Try using the latest v3.x.x

**Comment by akshitrcrm** [comment]
i tried that version but it kept giving me error like Unable to resolve module 'native.......' from 'node_modules/react-native-image-picker/src/index.ts'

**Comment by Johan-dutoit** [comment]
I'd recommend clearing node modules, doing a pod install & rebuilding your project.

**Comment by akshitrcrm** [comment]
@Johan-dutoit same issue after using "react-native-image-picker": "^3.0.0-vnext.4" and updating the code with launchImagePicker()

**Comment by asvine-p** [comment]
Same here

**Comment by Johan-dutoit** [comment]
With the latest version (3.0.0-vnext.4), `showImagePicker` no longer exists and is replaced with `launchImageLibrary`.

Here's a screenshot form the example app, running the latest version of the image picker, along with 14.1

![image](https://user-images.githubusercontent.com/1611055/98711463-af19da00-238d-11eb-9e0b-b7a11674a033.png)

**Comment by ksielyov** [comment]
> Try using the latest v3.x.x

No matching version found

**Comment by ksielyov** [comment]
> With the latest version (3.0.0-vnext.4), `showImagePicker` no longer exists and is replaced with `launchImageLibrary`.
> 
> Here's a screenshot from the example app, running the latest version of the image picker, along with 14.1
> 
> ![image](https://user-images.githubusercontent.com/1611055/98711463-af19da00-238d-11eb-9e0b-b7a11674a033.png)

TypeError: undefined is not an object (evaluating '_reactNativeImagePicker.default.launchImageLibrary')

**Comment by Johan-dutoit** [comment]
@ksielyov the reason for that error is most likely due to either not using the latest 3.x.x or you didn't run pod install or you didn't rebuild after running pod install.

**Comment by darknessproduction** [comment]
@akshitrcrm @asvine-p made it working by this
rm -rf node_modules
use yarn install instead of npm install
cd ios && pod install & cd ..
clear build folder
and yes it works only on real device
        "react": "16.13.1",
        "react-native": "0.63.3",
        "react-native-image-crop-tools": "^1.3.6",
        "react-native-image-picker": "v3.0.0-vnext.3",

**Comment by ravirajn22** [comment]
I hope the issue is solved, if not reply here or create new issue with details I am happy to fix it.

**Comment by darknessproduction** [comment]
@ravirajn22 I dont think its fixed. its not working in simulator anymore. If you dont want to fix this issue just do it with other issues in the same way. And dont reply any new issues if you dont help

**Comment by darknessproduction** [comment]
or if you dont want to help.
to close an issue is very simple

**Comment by ravirajn22** [comment]
How can I diagnose an issue If I am unable to reproduce, better you create a new issue. Use a fresh react-native and add just this library and see if you can reproduce. Give the repo link to this sample app, so that I can see and fix. What more you expect me to do.

**Comment by Janak-Nirmal** [comment]
I faced same issue and its because of import. If we change import from 

`import ImagePicker from 'react-native-image-picker';`
to 
`import * as ImagePicker from 'react-native-image-picker';`

It works and doesn't raise above issue. Posting here so that someone may benefit.

**Comment by smakosh** [comment]
The issue is still happening, your fix @Janak-Nirmal is not working.

It occurs on BigSur and iOS 14.2

**Comment by Janak-Nirmal** [comment]
@smakosh If you can share some code/repo to look at would be helpful to investigate further.

**Comment by smakosh** [comment]
> @smakosh If you can share some code/repo to look at would be helpful to investigate further.

I just had to import directly the exported functions like so `import { launchCamera, launchImageLibrary } from 'react-native-image-picker'`, Seems like a breaking change on a recent version

**Comment by vignesh-pibase** [comment]
same here
