### ISSUE TITLE
When I install the Dependency and Launch the App there are Tests that fail (on Android).

### ISSUE THREAD

**Issue by jawil003** [react-native-image-picker/react-native-image-picker#1484]
### Description

When I install the Dependency and Launch the App there are Tests that fail.

### How to repeat issue and example

1. Install Dependency in latest React Native App.
2. Start the App.
3. See this Error Message: 
```
> Task :react-native-image-picker:testDebugUnitTest FAILED

com.imagepicker.testing.ImagePickerModuleTest > testCancelTakingPhoto FAILED
    java.lang.UnsupportedOperationException at RobolectricTestRunner.java:265

com.imagepicker.testing.media.ImageConfigTest > testParsingOptions FAILED
    java.lang.UnsupportedOperationException at RobolectricTestRunner.java:265

com.imagepicker.testing.media.ImageConfigTest > testGetActualFile FAILED
    java.lang.UnsupportedOperationException at RobolectricTestRunner.java:265

com.imagepicker.testing.media.ImageConfigTest > testOnImmutable FAILED
    java.lang.UnsupportedOperationException at RobolectricTestRunner.java:265

com.imagepicker.testing.media.ImageConfigTest > testUseOriginal FAILED
    java.lang.UnsupportedOperationException at RobolectricTestRunner.java:265
```

### Solution

May there is some Android Configuration which needs to be done, which should be added to Docs.

### Additional Information

* React Native version: 0.63.2
* Platform: Android
* Development Operating System: Windows 10
* Dev tools: VS Code and Android Studio

**Comment by fraser018** [comment]
I also just came across this issue.
I can build our app fine on anl Android emulator but just tried to build on my physical handset and received these errors.
Emulator is running Android 11, handset is a Huawei running Android 10.
We've had this package installed but quite some time during development.

React Native - 0.63.3
Platform - Android
Dev OS - Linux (Manjaro) using latest versions of VS Code and Android Studio

**Comment by ravirajn22** [comment]
Check the breaking changes and upgrade to version 3.0.0-vnext.4

**Comment by developius** [comment]
Can confirm this issue only happens on Android 10 and was introduced by v2.3.4. Not quite sure [which change](https://github.com/react-native-image-picker/react-native-image-picker/compare/v2.3.3...v2.3.4) caused it?

**Comment by frankitox** [comment]
Well @ravirajn22 , `3.0.0-vnext.4` works. Although I had to update `minSdkVersion` to `21`.

**Comment by ravirajn22** [comment]
Version 2.x.x is not longer supported, please upgrade to 3.x.x
