### ISSUE TITLE
Android API >= 29  "Permission denied" or "Couldn't get file path for photo"

### ISSUE THREAD

**Issue by vikjovanov** [react-native-image-picker/react-native-image-picker#1492]
### Description

When I open the ImagePicker, after selecting an image or taking a picture, I receive these errors.

This happens only on android with version >= 10.

It seems to me that I read that this was due to a breaking change in the photo management since android V10. But I'm not sure.

EDIT: These errors are the response of the image picker. 

When I take a picture with the camera
![Screenshot 2020-11-12 at 12 31 13](https://user-images.githubusercontent.com/43797348/98934940-14331400-24e3-11eb-9f49-536c85279bb9.png)

When I select an image from the gallery
![Screenshot 2020-11-12 at 12 31 21](https://user-images.githubusercontent.com/43797348/98934961-19905e80-24e3-11eb-9cba-8dea34a871e0.png)

### How to repeat issue and example

Install `react-native-image-picker v2.3.2` and try to use it on android with version >= 10

### Additional Information

* Image Picker version: 2.3.3
* React Native version: 0.63.2
* Platform: Android >= V10 (api 29 and higher)
* Development Operating System: MacOS Mojave (10.14.6)
* Dev tools: Android studio version 3.5.3

**Comment by ravirajn22** [comment]
Upgrade to version 3.x.x

If you are using 2.x.x check https://github.com/react-native-image-picker/react-native-image-picker/issues/1447#issuecomment-721520908

**Comment by vikjovanov** [comment]
@ravirajn22 Thank you for your prompt response!

I'll test it directly! However, I read that this is a temporary solution!

Is version 3.x.x compatible with scoped storage? And is it a good idea to already use this version in production or is it better to wait a little longer?

**Comment by ravirajn22** [comment]
3.x.x is compatible with scoped storage
3.x.x version is mostly stable and I use it in production.
Post any issues will be happy to fix it.

2.x.x is legacy will not be maintained, for time being may be you can use some fixes.

**Comment by vikjovanov** [comment]
Perfect thanks a lot, I will in this case use v2.x.x with the patch you provided me and I add in my short term plans to upgrade to 3.x.x.

Thank you very much to you!
