### ISSUE TITLE
Image rotation (from the gallery and the camera) on android and iOS

### ISSUE THREAD

**Issue by vikjovanov** [react-native-image-picker/react-native-image-picker#1493]
### Description
When I take a picture from the camera, I have a 90deg image rotation and a horizontal flip in selfie mode.

I did the test on an
- iPhone 6 (iOS 12.4.8)
- Galaxy a20 (Android 10)
- Huawei P8 Lite 2017 (Android 7.0)
- iPhone SE (iOS 13.7)
- Huawei P20 Lite. (Android 9)

Here are the different rotations:

**iPhone 6 and iPhone SE**: 
- If the image is a screenshot I made with my phone: **no rotation**
- If I take a picture from the camera or a picture from the gallery that was taken with my camera (portrait and landscape): **rotation at 90 degrees**
- If I take a selfie: **rotation a 90 degree + horizontal flip**

**Galaxy a20**:
- If I take a picture from the gallery (portrait and landscape): **rotation at 90 degrees**
- If I take a picture with the camera: **rotate at 90 degrees**

**Huawei P8 Lite 2018 and Huawei P20 Lite**:
**No rotation except a horizontal flip when I do a selfie**

### Additional Information

* Image Picker version: 3.0.0-vnext.4
* React Native version: 0.63.2
* Platform: Both
* Development Operating System: MacOS Mojave

**Comment by ravirajn22** [comment]
i dont have those devices but will try to check. But just make sure its latest version of 3.x and tell me are u using any options like quality, maxHeight, maxWidth. or just paste ur input options and output values.

This will help me debug

**Comment by vikjovanov** [comment]
Hi @ravirajn22,

In fact I was sending my image directly to the server and it's true that I didn't try so much to display the image directly, I was displaying directly the url that my server was returning.

That said, the problem is fixed on my side.
Indeed after discussing this with my colleague backend, he asked me about it and he saw many times that he had to use Efix on the pictures he was receiving in order to put the image back in the right direction.

What I don't understand is how come when I was using V2.3, he didn't have to do that! Could it be due to the fact that in the source code of V2.3, there is a "fix orientation" and therefore, the orientation of the picture was already corrected before sending it to the back-end?

Thanks again for your time!

**Comment by ravirajn22** [comment]
Yes in previous version they could have corrected the orientation before saving but when you work with image data you have to check its exif.

People can upload images from various modes (through browser also) and fixing orientation if required better handled in backend.
