### ISSUE TITLE
Cannot take video via launchCamera

### ISSUE THREAD

**Issue by scousino** [react-native-image-picker/react-native-image-picker#1497]
### Description
Cannot get the results from taking video via launchCamera. The camera app is launched and I can take video, but when I hit okay, instead of the callback being called I get a java.lang.RuntimeException saying "Failure delivering result"

![Screenshot_20201117-114546_ALIMqa](https://user-images.githubusercontent.com/8717527/99420243-fee72c80-28ca-11eb-9878-e7214f83d790.jpg)

### How to repeat issue and example
* Use launchCamera to take video. Record video and then hit ok

### Solution

Should be able to take video and receive the result on android

### Additional Information

* Image Picker version: 3.0.0-vnext.3
* React Native version: 0.62.2
* Platform: Android
* Development Operating System: Windows

**Comment by scousino** [comment]
It looks like in onActivityResult in ImagePickerModule.java the data param is null, which is causing the null pointer exception that crashes our app.

**Comment by scousino** [comment]
Device I'm using is running Android 9 if that helps

**Comment by ravirajn22** [comment]
@scousino a PR is made to fix this issue. Try using it directly and check if the issue is fixed on your device. That would be helpful.

**Comment by scousino** [comment]
I'm not sure how to test this directly, there is no branch for me to pull down with these changes

**Comment by ravirajn22** [comment]
This is the branch https://github.com/ravirajn22/react-native-image-picker/tree/fix_videoCaptureUri

**Comment by scousino** [comment]
Got it, thanks!

**Comment by scousino** [comment]
@Johan-dutoit @ravirajn22 I saw the PR was merged in, but there isn't a new release version. When can I expect this?

**Comment by ravirajn22** [comment]
point to master for now or that commit. @Johan-dutoit release ?

**Comment by scousino** [comment]
Pointing to master is not a viable option for me. I need an actual npm package version release. Is this coming soon?

**Comment by ravirajn22** [comment]
@Johan-dutoit can you make a release. 

Make this 3.x.x as the latest in npm so that new users install it. 

Remove the next string from the version names.

Can you add me to this library so that I can do release and minor commits.

**Comment by scousino** [comment]
@Johan-dutoit anyone update on this??

**Comment by Johan-dutoit** [comment]
@scousino try the latest 3.0.1.  Should be in there.
