### ISSUE TITLE
how can I get resized image without loosing transparency?

### ISSUE THREAD

**Issue by pyeonjaesik** [react-native-image-picker/react-native-image-picker#1504]
const options = {
  title: '이미지 선택',
  // storageOptions: {
  //   skipBackup: true,
  //   path: 'images',
  // },
 // includeBase64:true,
 //quality:0.1,
 mediaType:'photo',
 maxWidth:360,
 maxHeight:360,
};

my image is resized well but loose transparency.

how can I get resized image without loosing transparency?

**Comment by ravirajn22** [comment]
Which library version are you using?

**Comment by ravirajn22** [comment]
Any info?

**Comment by ravirajn22** [comment]
I hope the problem is solved, if not upload the original image which caused the problem. Or provide more info.
