### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by ravirajn22** [react-native-image-picker/react-native-image-picker#1507]
@Johan-dutoit can you make a release.

Make this 3.x.x as the latest in npm so that new users install it.

Remove the next string from the version names.

Please add me to this library so that I can do releases, minor commits, manage issues and PR's. It's taking lot of effort coordinate, which instead I will spend on code. Any major change or feature addition will go through regular PR model.

**Comment by ravirajn22** [comment]
@Johan-dutoit ??

**Comment by ravirajn22** [comment]
@Johan-dutoit  at least reply something. Lets see when I will get a reply, from your contributions it looks like you'r active in github.

**Comment by ravirajn22** [comment]
@janicduplessis @EvanBacon can you people give me permission to this repo, need to manage PR and issues? is it possible?

**Comment by Johan-dutoit** [comment]
Been busy with a paid job and I missed this on my radar.  

A proper changelog would be required for the release notes from 2.x.x to 3.0.0, explaining how to migrate (i.e. permissions, etc.)
Happy to do a release at ant point after a changelog has been posted.

p.s. I'll add you here, but I don't have the powers to give you NPM permissions.

**Comment by ravirajn22** [comment]
Please add me here, I will update the docs and tell. You just make the release. About the changelog I don't were to add it?

**Comment by ravirajn22** [comment]
@Johan-dutoit add me.
