### ISSUE TITLE
Disable select from Google photo

### ISSUE THREAD

**Issue by vinhtran6921** [react-native-image-picker/react-native-image-picker#1508]
How can I set option that only pick from device's gallery?
I want to disable select from Google photo
Thanks for your help

**Comment by ravirajn22** [comment]
Sorry it's not possible from what I know.

**Comment by vinhtran6921** [comment]
when I try to select video on Google photo. It's not response anything and have to force app to reopen.
Did you resolve this case before, @ravirajn22 ?

**Comment by vinhtran6921** [comment]
When I select video on Google photo it's take a long time to return App. 
Response return uri like this `"content://com.google.android.apps.photos.contentprovider/0/2/mediakey%3A%2Flocal%253A3c158be3-5f1c-43b0-be6f-1aed13c3f2d3/ORIGINAL/NONE/1346294710"`
I can't use it for play with react-native-video also upload this video to server
Did you have any ideas for this?

**Comment by ravirajn22** [comment]
What version of library you are using?

Why can't you upload to server or use it with react-native-video? What error are you getting?

**Comment by ravirajn22** [comment]
@vinhtran6921 any updates on this issue?

**Comment by vinhtran6921** [comment]
Sorry for the delayed response. I just show popup error when user pick from Drive or Google.
When select video from cloud it just return uri from google and I don't know how to download it.
Thank you so much for your thoughtful note

**Comment by shubhamraka08** [comment]
@ravirajn22 I am also facing the same issue can you please help us here.

**Comment by ravirajn22** [comment]
Update to latest version and try again. Ping here with details.
