### ISSUE TITLE
GIFs are being selected as JPGs

### ISSUE THREAD

**Issue by mhui** [react-native-image-picker/react-native-image-picker#1509]
### Description
This wasn't an issue on 2.3.4 but on the latest 3 version GIFs are being selected as JPGs. The uri has a jpg extension and the type is image/jpg

EDIT: I noticed it's only on certain GIFs

### How to repeat issue and example
Select a GIF from camera roll

### Solution

What needs to be done to address this issue? 

### Additional Information

* Image Picker version: 3.0.0-vnext.4
* React Native version: 0.63.3
* Platform: iOS
* Development Operating System: Mac
* Dev tools: iOS 14.2

**Comment by ravirajn22** [comment]
Since not all gifs cause problem, can you upload the gif which causes the issue so that I can check it.

**Comment by mhui** [comment]
Sorry mean to attach it earlier. This was the GIF I tested with. It's a kpop group don't judge lol
![CC7376A3-DE36-4D7A-883E-3B72E4FAF75B](https://user-images.githubusercontent.com/1037474/101222377-7f818900-363e-11eb-9ba9-57d1bc0db7e8.GIF)

**Comment by ravirajn22** [comment]
@mhui I downloaded the image and saved to iOS photos and used this library to select the image. Its properly showing as `type: "image/gif"`.  Need more info or can you set a break point inside iOS code `getFileType` and see what is happening?

**Comment by mhui** [comment]
@ravirajn22 Hmm I just tried it again once on the prod app and it worked so I'll close this issue. I'll make another one if I can catch it again.

**Comment by lucas-alberto98** [comment]
Hello, This same problem is happening to me in the latest version (3.2.1).

Gif link with the problem: https://media.tenor.com/images/9e6a2b02e91bc6611d38ed0496418b18/tenor.gif
