### ISSUE TITLE
unhandled promise rejection typeError undefined is not object mediaTypes:ImagePicker.MediaTypes Options.Images,

### ISSUE THREAD

**Issue by umerhayat54** [react-native-image-picker/react-native-image-picker#1513]
![Screenshot_20201205-144300.png](https://user-images.githubusercontent.com/67622257/101239837-b32ae480-370c-11eb-8d5a-fbd5fad1395a.png)

When i chick on that image this error come

![Screenshot_20201205-144249.png](https://user-images.githubusercontent.com/67622257/101239858-cd64c280-370c-11eb-9630-96651e17f4f5.png)

Code is
 ![20201205_144314.jpg](https://user-images.githubusercontent.com/67622257/101239868-e1102900-370c-11eb-94a9-df6c376c92e3.jpg)

**Comment by ravirajn22** [comment]
Please fill the issue details.

**Comment by AldivioAlves** [comment]
@umerhayat54 you must import library as **import * as ImagePicker from 'react-native-image-picker'** . I got same error...

**Comment by ravirajn22** [comment]
@AldivioAlves thanks
