### ISSUE TITLE
saveToPhotos: false still save to gallery. Android only

### ISSUE THREAD

**Issue by amirulasrof** [react-native-image-picker/react-native-image-picker#1514]
const options = {
      saveToPhotos: false,
      quality: 0.6,
}

ImagePicker.launchCamera(options, (response) => {
      // do anything here
}

I wanted to capture image without saving the image in gallery.

**Comment by ravirajn22** [comment]
What version are you using?

**Comment by amirulasrof** [comment]
Hi @ravirajn22, version used is 2.3.0

**Comment by ravirajn22** [comment]
Upgrade to 3.x.x version 2.3.0 does not support `saveToPhotos`. Read the docs https://github.com/react-native-image-picker/react-native-image-picker

Check latest version here https://github.com/react-native-image-picker/react-native-image-picker/releases

**Comment by amirulasrof** [comment]
Will try it later. Thank you ! @ravirajn22

**Comment by ravirajn22** [comment]
I hope the issue is solved, if not reply here with details I am happy to fix it.

**Comment by amirulasrof** [comment]
It is solved @ravirajn22 thank you !
