### ISSUE TITLE
Cannot access launchCamera, launchImageLibrary with TypeScript[🐛] 

### ISSUE THREAD

**Issue by ZeroCho** [react-native-image-picker/react-native-image-picker#1518]
### Description

```ts
import {
  launchImageLibrary,
  launchCamera,
  ImagePickerResponse,
} from 'react-native-image-picker';
```
gives me a TypeScript Error.
```
TS2307: Cannot find module 'react-native-image-picker' or its corresponding type declarations.
```
Below is fine.
```ts
import {
  launchImageLibrary,
  launchCamera,
  ImagePickerResponse,
} from 'react-native-image-picker/src/index';
```

### Solution

Those should be accessible from 'react-native-image-picker'

### Additional Information

- Image Picker version: 3.0.0
- React Native version: 0.63.4
- Platform: Android
- Development Operating System: MacOS
- Dev tools: WebStorm 2020.3, Android SDK 29

**Comment by ravirajn22** [comment]
@Johan-dutoit check it.

**Comment by Johan-dutoit** [comment]
A PR was merged yesterday to fix this.  I'll do a minor release now.

**Comment by Johan-dutoit** [comment]
https://github.com/react-native-image-picker/react-native-image-picker/releases/tag/3.0.1

**Comment by tamacroft** [comment]
same here, on version 3.1.2, please fix it
