### ISSUE TITLE
after selctiong image from galary app gets crash without log and catch [🐛] 

### ISSUE THREAD

**Issue by al0kdash** [react-native-image-picker/react-native-image-picker#1521]
### Description

Explain the bug in as much detail as possible

### How to repeat issue and example

- step to reproduce the issue
- ...

### Solution

What needs to be done to address this issue?

### Additional Information

- Image Picker version: [FILL THIS OUT: Be specific, filling out "latest" here is not enough.]
- React Native version: [FILL THIS OUT: Be specific, filling out "latest" here is not enough.]
- Platform: [FILL THIS OUT: iOS, Android, or both?]
- Development Operating System: [FILL THIS OUT: Are you developing on MacOS, Linux, or Windows?]
- Dev tools: [FILL THIS OUT: Xcode or Android Studio version, iOS or Android SDK version, if applicable] navigation crash for Android

**Comment by ravirajn22** [comment]
See android Logcat for error and post it here. Without that we cannot diagnose.  And spend some time and fill the details first.

**Comment by Hamza6244** [comment]
**After capturing video from the camera when clicking on the confirmation screen then the app is crashing without any logs and this crash is on device specific**
Image Picker version: 2.3.4
React Native version: 0.63.4
Platform: Android
Development Operating System: macOS
Dev tools: Android SDK 29

**Comment by ravirajn22** [comment]
Support for version 2.x.x is stopped, upgrade to 3.x.x. Reply if you still get the issue in the latest version I will open the issue.

**Comment by Hamza6244** [comment]
@ravirajn22 Sure let me upgrade this version then give the feedback
