### ISSUE TITLE
[🐛] Huawei p30 pro launchimagelibrary is stuck after being used for many times

### ISSUE THREAD

**Issue by caoqin** [react-native-image-picker/react-native-image-picker#1523]
### Description

Huawei p30 pro launchimagelibrary is stuck after being used for many times

### How to repeat issue and example

   "react-native-image-picker": "^3.0.0",
    "react": "16.13.1",
    "react-native": "0.63.3",

import {launchCamera, launchImageLibrary} from 'react-native-image-picker';

const OPTIONS = {
  mediaType: 'photo',
  maxHeight: 800,
  maxWidth: 600,
  quality: 1, 
  saveToPhotos: true,
};

-    // choose image
    launchImageLibrary(OPTIONS, (response) => {
      console.log('launchImageLibrary', response);
      if (response.type == 'video/mp4') {
        ToastAndroid.show('please choose image~！', ToastAndroid.SHORT);
        return;
      }
    });
- ...

**Comment by Johan-dutoit** [comment]
Hey, any chance you can translate to english?
Based on google translate, it's something along the lines of the image picker freezing/getting stuck after multiple uses?

**Comment by caoqin** [comment]
> Hey, any chance you can translate to english?
> Based on google translate, it's something along the lines of the image picker freezing/getting stuck after multiple uses?

yes，Launchimagelibrary has been called many times on Huawei mobile phone to select images

**Comment by ravirajn22** [comment]
paste your android logcat and system trace when this happens. Without that, we cannot diagnose.

**Comment by caoqin** [comment]
![image](https://user-images.githubusercontent.com/38684911/101878677-eec12500-3bca-11eb-9021-b9aaefe396e8.png)

**Comment by caoqin** [comment]
> paste your android logcat and system trace when this happens. Without that, we cannot diagnose.
![image](https://user-images.githubusercontent.com/38684911/101878954-73ac3e80-3bcb-11eb-87a7-29971c505f74.png)

**Comment by caoqin** [comment]
![image](https://user-images.githubusercontent.com/38684911/101879145-d30a4e80-3bcb-11eb-98ae-8c49bec109e3.png)

**Comment by ravirajn22** [comment]
Have to test if there are any memory leaks in code, but I don't have time now. May be a week later, I will check it out.

**Comment by ravirajn22** [comment]
Sorry could not diagnose the issue, comment here with more info I will fix it.
