### ISSUE TITLE
[🌟] Unable to set video duration limit

### ISSUE THREAD

**Issue by Hamza6244** [react-native-image-picker/react-native-image-picker#1524]
### Description

I'm unable to set the video duration limit in version 3.0.1

### Proposed Solution

Kindly add a video duration limit option

### Test Solution

Record the video and you will see default 5 minutes for video recording

**Comment by Hamza6244** [comment]
Please release the new version with this update

**Comment by Johan-dutoit** [comment]
@Hamza6244 already been released.  3.1.0.

**Comment by irion94** [comment]
But what about limiting duration on launchImageLibrary? I think it would be great to implement this too 🙄
