### ISSUE TITLE
[🐛] Called method on background thread

### ISSUE THREAD

**Issue by adriantabirta** [react-native-image-picker/react-native-image-picker#1526]
### Description

Explain the bug in as much detail as possible
ios - App freezes, crash

### How to repeat issue and example
- add lib
- launch camera and take a photo
- press done
- crash

### Solution
please update file **ImagePickerManager.m**
call methods on main thread.

```
RCT_EXPORT_METHOD(launchCamera:(NSDictionary *)options callback:(RCTResponseSenderBlock)callback)
{
    self.callback = callback;
    
    dispatch_async(dispatch_get_main_queue(), ^{
        [self launchImagePicker:RNImagePickerTargetCamera options:options];
    });
}

RCT_EXPORT_METHOD(launchImageLibrary:(NSDictionary *)options callback:(RCTResponseSenderBlock)callback)
{
    self.callback = callback;
    
    dispatch_async(dispatch_get_main_queue(), ^{
        [self launchImagePicker:RNImagePickerTargetLibrarySingleImage options:options];
    });
}

```

**Comment by ravirajn22** [comment]
dispatch_get_main_queue makes the function run in main thread, so I don't think there is a problem here. Paste your error log.

**Comment by adriantabirta** [comment]
I have a problem with launch camera. Xcode highlight where code was called from other thread. Picker appears after seconds slow or never.

**Comment by ravirajn22** [comment]
This thread should solve your problem, https://github.com/react-native-image-picker/react-native-image-picker/issues/1456

If not message here, I will open the issue
