### ISSUE TITLE
[🐛] undefined is not a function (near '...ImagePicker.showImagePicker...')

### ISSUE THREAD

**Issue by smakosh** [react-native-image-picker/react-native-image-picker#1528]
### Description
<img width="400" src="https://user-images.githubusercontent.com/20082141/101969813-60a16a80-3bdb-11eb-8c5d-2e68c8649a7d.png" />

### How to repeat issue and example

- `npx react-native init`
- Install and use this library

### Additional Information

- Image Picker version: `3.0.1`
- React Native version: `0.63.4`
- Platform: iOS
- Development Operating System: MacOS, BigSur

**Comment by smakosh** [comment]
![Screenshot_20201211-181455.png](https://user-images.githubusercontent.com/20082141/101970041-d6f29c80-3bdc-11eb-8062-911a3823a8bc.png)

Same on Android
> pixel 2

**Comment by smakosh** [comment]
`import {launchImageLibrary} from 'react-native-image-picker'` fixed it

**Comment by BiplovQss** [comment]
@smakosh , @pedro , @ligaz , @nevir , @jkappers 
as `ImagePicker.showImagePicker` is not working then how can i get option for either select image from gallery or camera.

**Comment by smakosh** [comment]
There are now 2 exported functions that you can import, one to get images from the library and the other to launch the camera.

**Comment by BiplovQss** [comment]
Need both image option at a time. any option for that @smakosh .

**Comment by redko-o** [comment]
same on Android

**Comment by SatalBill** [comment]
Still there is no solution on this issue? I also want to select both option - library & launch camera. 
How to fix this issue?

**Comment by eddievlagea** [comment]
Is there a way to get both options, library and launch camera?

**Comment by nasiefk** [comment]
I think you need to downgrade to version `2.3.4` to get this option

**Comment by vasuchawla** [comment]
you can use `react-native-options-menu` to build your own menu to show both options.

**Comment by 3DJakob** [comment]
> `import {launchImageLibrary} from 'react-native-image-picker'` fixed it

Really strange solution but works for me too. It would be nice for someone to take a look at why this is.

**Comment by Maijied** [comment]
Follow this solution:
https://stackoverflow.com/a/68378454/7921804
