### ISSUE TITLE
[🐛] Unable to resolve path to module 'react-native-image-picker'

### ISSUE THREAD

**Issue by papuruth** [react-native-image-picker/react-native-image-picker#1530]
### Description

I upgraded to v3.0.1 and now I'm getting "Unable to resolve path to module 'react-native-image-picker'."
### How to repeat issue and example

- step to reproduce the issue
Import the module
```js
import { launchImageLibrary } from 'react-native-image-picker';
```
The package name is underlined with red.

### Additional Information

- Image Picker version: [3.0.1]
- React Native version: [0.63.4]
- Platform: [Android]
- Development Operating System: [Windows]
- Dev tools: [Android Studio version, iOS or Android SDK version, if applicable] navigation crash for Android

When I add "main": "src/index.ts" in react-native-image-picker/package.json the error goes away

**Comment by 7arsandre** [comment]
Having the same issue!

<img width="995" alt="image" src="https://user-images.githubusercontent.com/20848327/102048921-3c62ab00-3de0-11eb-807a-7030fae774b0.png">

When I try to execute the `ImagePicker.launchImageLibrary()` the console prompts the following error

<img width="445" alt="image" src="https://user-images.githubusercontent.com/20848327/102049058-7cc22900-3de0-11eb-8a6b-c8f14ab1c559.png">
Version: 
"react": "16.13.1",
"react-native": "0.63.3",
...
"react-native-image-picker": "^3.0.1",

**Comment by papuruth** [comment]
> Having the same issue!
> 
> <img alt="image" width="995" src="https://user-images.githubusercontent.com/20848327/102048921-3c62ab00-3de0-11eb-807a-7030fae774b0.png">
> 
> When I try to execute the `ImagePicker.launchImageLibrary()` the console prompts the following error
> 
> <img alt="image" width="445" src="https://user-images.githubusercontent.com/20848327/102049058-7cc22900-3de0-11eb-8a6b-c8f14ab1c559.png">
> 
> Version: "react": "16.13.1", "react-native": "0.63.3", ... "react-native-image-picker": "^3.0.1",

For mean time you can access like this
```js
import { launchImageLibrary } from 'react-native-image-picker';
```

**Comment by 7arsandre** [comment]
That solved the undefined error, thanks @papuruth !

**Comment by papuruth** [comment]
> That solved the undefined error, thanks @papuruth !

for underline error, you can add as specified above

**Comment by Johan-dutoit** [comment]
I'm not sure what the issue is here anymore?  The import works fine on 3.0.1 (see image below)

![image](https://user-images.githubusercontent.com/1611055/102049917-7cc72680-3dea-11eb-97e7-cad85b4a1711.png)

**Comment by papuruth** [comment]
> I'm not sure what the issue is here anymore? The import works fine on 3.0.1 (see image below). Default export/import is not supported.
> 
> Usage is either
> 
> `import * as ImagePicker from 'react-native-image-picker`
> or
> `import { launchImageLibrary } from 'react-native-image-picker';`
> 
> ![image](https://user-images.githubusercontent.com/1611055/102049917-7cc72680-3dea-11eb-97e7-cad85b4a1711.png)

The import is fine but the package name is underline with red as eslint can't resove the module path. But after adding "main": "src/index.ts" in node_modules/react-native-image-picker/package.json the eslint error goes away.

**Comment by Johan-dutoit** [comment]
What does your eslint config look like, as I don't face this error in the projects that I have that uses this.

**Comment by 7arsandre** [comment]
> What does your eslint config look like, as I don't face this error in the projects that I have that uses this.

For me it's the following rule that yields
https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-unresolved.md

**Comment by papuruth** [comment]
```json
{
  "parser": "babel-eslint",
  "env": {
    "es6": true,
    "jest": true
  },
  "extends": ["airbnb", "plugin:react-native/all", "prettier"],
  "globals": {
    "Atomics": "readonly",
    "SharedArrayBuffer": "readonly",
    "__DEV__": true
  },
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    },
    "ecmaVersion": 2020,
    "sourceType": "module"
  },
  "plugins": ["react", "react-native", "jsx-a11y", "import"],
  "rules": {
    "global-require": "off",
    "import/prefer-default-export": "off",
    "no-unused-vars": ["error", { "argsIgnorePattern": "^_" }],
    "react-native/no-raw-text": "off",
    "react-native/sort-styles": "off",
    "react/jsx-one-expression-per-line": "off",
    "react-native/no-inline-styles": 0,
    "no-console": 0,
    "no-undef": 0,
    "no-underscore-dangle": "off",
    "camelcase": "off",
    "react-native/no-color-literals": 0,
    "react/jsx-props-no-spreading": "off",
    "react/jsx-filename-extension": ["error", { "extensions": [".js", ".jsx"] }]
  },
  "settings": {
    "import/resolver": {
      "babel-plugin-root-import": {
        "rootPathSuffix": "./src",
        "rootPathPrefix": "@/"
      }
    }
  }
}
```

> What does your eslint config look like, as I don't face this error in the projects that I have that uses this.

**Comment by Johan-dutoit** [comment]
Check out 3.1.0

**Comment by papuruth** [comment]
> Check out 3.1.0

Great. It's fine now.
