### ISSUE TITLE
Getting this error :TypeError: undefined is not an object (evaluating '_reactNativeImagePicker.default.showImagePicker')[🐛] 

### ISSUE THREAD

**Issue by sultanMachido** [react-native-image-picker/react-native-image-picker#1531]
### Description
I tried to use showImagePicker for  version 3 but keep getting the above error

### How to repeat issue and example

- step to reproduce the issue
- ...

### Solution

What needs to be done to address this issue?

### Additional Information

- Image Picker version: [FILL THIS OUT: Be specific, filling out "latest" here is not enough.]
- React Native version: [FILL THIS OUT: Be specific, filling out "latest" here is not enough.]
- Platform: [FILL THIS OUT: iOS, Android, or both?]
- Development Operating System: [FILL THIS OUT: Are you developing on MacOS, Linux, or Windows?]
- Dev tools: [FILL THIS OUT: Xcode or Android Studio version, iOS or Android SDK version, if applicable] navigation crash for Android

**Comment by mrridho01** [comment]
try importing the module with :
import { launchImageLibrary} from 'react-native-image-picker;

and then to call the function, use : 
launchImageLibrary (options?, calback);

Not ImagePicker.launchImageLibrary (options, callback) like in the previous versions..

I got the same issue before, and now it solved

**Comment by dhamdani666** [comment]
> try importing the module with :
> import { launchImageLibrary} from 'react-native-image-picker;
> 
> and then to call the function, use :
> launchImageLibrary (options?, calback);
> 
> Not ImagePicker.launchImageLibrary (options, callback) like in the previous versions..
> 
> I got the same issue before, and now it solved

thx you it solved !

**Comment by sultanMachido** [comment]
> try importing the module with :
> import { launchImageLibrary} from 'react-native-image-picker;
> 
> and then to call the function, use :
> launchImageLibrary (options?, calback);
> 
> Not ImagePicker.launchImageLibrary (options, callback) like in the previous versions..
> 
> I got the same issue before, and now it solved

Bless brother....you solved it

**Comment by Alix-stack** [comment]
> > try importing the module with :
> > import { launchImageLibrary} from 'react-native-image-picker;
> > and then to call the function, use :
> > launchImageLibrary (options?, calback);
> > Not ImagePicker.launchImageLibrary (options, callback) like in the previous versions..
> > I got the same issue before, and now it solved
> 
> thx you it solved !

yes, it's on react-native 0.63.3v
thanks again

**Comment by ebnersilva** [comment]
Not Working Here!
