### ISSUE TITLE
Getting TypeError: undefined is not an object (evaluating '_reactNativeImagePicker.default.launchImageLibrary')[🐛] 

### ISSUE THREAD

**Issue by ahmed5605** [react-native-image-picker/react-native-image-picker#1548]
import React from 'react';
import { StyleSheet,SafeAreaView,ScrollView,  Text, View, TouchableOpacity, Button, Image } from 'react-native';
import ImagePicker from 'react-native-image-picker';
import {launchCamera, launchImageLibrary} from 'react-native-image-picker';
export default function App() {
  const [response, setResponse] = React.useState(null);

  return (
    <SafeAreaView>
      <ScrollView>
        <Button
          title="Take image"
          onPress={() =>
            ImagePicker.launchCamera(
              {
                mediaType: 'photo',
                includeBase64: false,
                maxHeight: 200,
                maxWidth: 200,
              },
              (response) => {
                setResponse(response);
              },
            )
          }
        />

        <Button
          title="Select image"
          onPress={() =>
            ImagePicker.launchImageLibrary(
              {
                mediaType: 'photo',
                includeBase64: false,
                maxHeight: 200,
                maxWidth: 200,
              },
              (response) => {
                setResponse(response);
              },
            )
          }
        />

        <Button
          title="Take video"
          onPress={() =>
            ImagePicker.launchCamera({mediaType: 'video'}, (response) => {
              setResponse(response);
            })
          }
        />

        <Button
          title="Select video"
          onPress={() =>
            ImagePicker.launchImageLibrary({mediaType: 'video'}, (response) => {
              setResponse(response);
            })
          }
        />

        <View style={styles.response}>
          <Text>Res: {JSON.stringify(response)}</Text>
        </View>

        {response && (
          <View style={styles.image}>
            <Image
              style={{width: 200, height: 200}}
              source={{uri: response.uri}}
            />
          </View>
        )}
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  button: {
    marginVertical: 24,
    marginHorizontal: 24,
  },
  image: {
    marginVertical: 24,
    alignItems: 'center',
  },
  response: {
    marginVertical: 16,
    marginHorizontal: 8,
  },
});

**Comment by jake-chambers** [comment]
experiencing same issue with:
        "react-native-image-picker": "^3.1.1",
        "react-native": "~0.63.3",
        iOS v 14, iphone 11 pro simulator

**Comment by ertucaglar** [comment]
i have same issue

**Comment by ctlincfaisal** [comment]
I have the same problem. Looking for a solution

**Comment by ravirajn22** [comment]
Read this thread https://github.com/react-native-image-picker/react-native-image-picker/issues/1531
Import the module as shown in the docs.

I hope the issue is solved, if not reply here or create new issue with details I am happy to fix it.
Thanks

**Comment by zhaiyjgithub** [comment]
Thanks.
