### ISSUE TITLE
[🐛] Cannot find module 'react-native-image-picker' or its corresponding type declarations.

### ISSUE THREAD

**Issue by ighotouch** [react-native-image-picker/react-native-image-picker#1554]
### Description

Explain the bug in as much detail as possible
Cannot find module 'react-native-image-picker' or its corresponding type declarations.

**Comment by BretzelLudique** [comment]
Facing the same issue, temporarily using this : 
`import {launchCamera, launchImageLibrary} from 'react-native-image-picker/src/index';`

**Comment by ravirajn22** [comment]
@Johan-dutoit can you check the issue with typescript implementation, in a fresh project not the example one.

**Comment by Andidevnk** [comment]
@ighotouch @ravirajn22 @BretzelLudique 
Use like this 
import * as ImagePicker from 'react-native-image-picker/src';

**Comment by AngeloLanch** [comment]
Same problem...
I was fixed using  `import { launchCamera, launchImageLibrary } import from 'react-native-image-picker/src'`

**Comment by marcelxsilva** [comment]
I'm using version `"react-native-image-picker": "^3.1.1"`, only remove operator `^` and worked.

**Comment by olayenca** [comment]
Randomly started getting this issue on  `react-native-image-picker@^2.3.1` after a fresh install `ImagePicker.showImagePicker()` no longer worked. @marcelxsilva 's suggestion worked for me after a reinstall.

**Comment by djMax** [comment]
I think the problem is package.json:

https://github.com/react-native-image-picker/react-native-image-picker/blob/main/package.json#L7

It should be

```
  "types": "lib/typescript/index.d.ts",
```
