### ISSUE TITLE
How to get uri of the file to store it on firebase ?[🌟] 

### ISSUE THREAD

**Issue by bscs17047** [react-native-image-picker/react-native-image-picker#1555]
**### Description**

I want to upload file to server  (Firebase)

**Comment by ravirajn22** [comment]
Use the response uri to upload the file or show it on screen

**Comment by ravirajn22** [comment]
I hope the issue is solved, if not reply here or create new issue with details I am happy to fix it.

**Comment by michaellu88** [comment]
same issue, the uri missing "file://"
