### ISSUE TITLE
[🐛] version 3.1.2  not found module

### ISSUE THREAD

**Issue by Txiaomo** [react-native-image-picker/react-native-image-picker#1557]
### Description

Explain the bug in as much detail as possible

### How to repeat issue and example

import ImagePicker from 'react-native-image-picker'

**Comment by Andidevnk** [comment]
@Txiaomo Use please import * as ImagePicker from 'react-native-image-picker/src';

**Comment by ravirajn22** [comment]
Import it correctly like said in Readme
