### ISSUE TITLE
[iOS] Build failed with error: Undefined symbols for architecture x86_64 [🐛] 

### ISSUE THREAD

**Issue by papts0909** [react-native-image-picker/react-native-image-picker#1558]
### Description

I tried to upgrade & build my project on Xcode with version react-native-image-picker@3.1.2 and encountered error : 
`Undefined symbols for architecture x86_64:
"_OBJC_CLASS_$_ImagePickerUtils", referenced from:
objc-class-ref in libRNImagePicker.a(ImagePickerManager.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

So i unlink and link a package again with no luck

### How to repeat issue and example

- npm install react-native-image-picker@3.1.2
- react-native link react-native-image-picker
- Run build on Xcode => Encounter error

### Solution

I found 'ImagePickerUtils.m' is missing in 'RNImagePicker'.
After add 'ImagePickerUtils.m' to 'RNImagePicker', it worked again.
![image](https://user-images.githubusercontent.com/20726300/103125834-f69ac200-46be-11eb-84f8-ac8d233427cd.png)

At this time my project can run & build normally, but i dont know that's correct, so please help me check. Thanks you!

### Additional Information

- Image Picker version: 3.1.2
- React Native version: 0.59.10
- Platform: iOS
- Development Operating System: MacOS
- Dev tools: Xcode 11.6

**Comment by tienle46** [comment]
I also has this bug in RN version 0.59.10. Pretty sure this will happen if we link the library manually

**Comment by ravirajn22** [comment]
Sorry guys don't have time to support older versions, request you to fork this library and make these small changes and use it.
