### ISSUE TITLE
IOS 14.1 is not requesting any permission when triggering launchImageLibrary[🐛] 

### ISSUE THREAD

**Issue by brendan1809** [react-native-image-picker/react-native-image-picker#1559]
### Description

The app will just go to the image gallery without asking permission.
https://developer.apple.com/app-store/review/guidelines/
Based on the privacy in the guideline I am afraid that this will cause the failure of the submission to app store 

### How to repeat issue and example

- A clean project
- Trigger launchImageLibrary
- Instantly open up photo library

### Solution

Ask user for library permission

### Additional Information

- Image Picker version: 3.1.2
- React Native version: 0.63.4
- Platform: IOS
- Development Operating System: MacOS
- Dev tools: XCode

**Comment by ravirajn22** [comment]
Yes thats expected, we are not accessing all the photos we are given permission to only that single photo which the user selects. You can read more on this online.
