### ISSUE TITLE
[🐛] Android build fail due to minSdkVersion conflict

### ISSUE THREAD

**Issue by darron1217** [react-native-image-picker/react-native-image-picker#1560]
### Description
After install this package, I got build error on Android
```
Error: uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [:react-native-image-picker]
Suggestion: use a compatible library with a minSdk of at most 16,
       or increase this project's minSdk version to at least 21,
       or use tools:overrideLibrary="com.imagepicker" to force usage (may lead to runtime failures)
```

Should I have to increase `minSdkVersion` to use this package?

### How to repeat issue and example

- install package
- run `react-native run-android`

### Additional Information

- Image Picker version: 3.1.2
- React Native version: 0.63.3
- Platform: Android
- Development Operating System: MacOS
- Dev tools: Android SDK 29

**Comment by Hassanjankhan** [comment]
i face the same issue any solution

**Comment by darron1217** [comment]
@Hassanjankhan Currently the only solution I know is setting `minSdkVersion` to 21.
But this would drop support for users who uses SDK under 21.

**Comment by brendan1809** [comment]
android -> build.gradle
```
buildscript {
  ...
        minSdkVersion = 21
  ...
}
```

**Comment by ravirajn22** [comment]
0.63.3 does not support SDK less than 21. So only we also upgraded.

**Comment by ravirajn22** [comment]
So your only option is to upgrade.

**Comment by gauravshresthh** [comment]
> android -> build.gradle
> 
> ```
> buildscript {
>   ...
>         minSdkVersion = 21
>   ...
> }
> ```

thanks for the info bro

**Comment by tgreco** [comment]
Is this not part of master branch?

**Comment by AliYar-Khan** [comment]
facing the same error on react native 0.74
```

C:\Freelance\Meetkor\android\app\src\debug\AndroidManifest.xml Error:
        uses-sdk:minSdkVersion 21 cannot be smaller than version 23 declared in library [com.facebook.react:react-android:0.74.1] C:\Users\acer\.gradle\caches\transforms-3\817bf4b774b7361c46230e491303d01c\transformed\jetified-react-android-0.74.1-debug\AndroidManifest.xml as the library might be using APIs not available in 21
        Suggestion: use a compatible library with a minSdk of at most 21,
                or increase this project's minSdk version to at least 23,
                or use tools:overrideLibrary="com.facebook.react" to force usage (may lead to runtime failures)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 23 declared in library [com.facebook.react:react-android:0.74.1] C:\Users\acer\.gradle\caches\transforms-3\817bf4b774b7361c46230e491303d01c\transformed\jetified-react-android-0.74.1-debug\AndroidManifest.xml as the library might be using APIs not available in 21
        Suggestion: use a compatible library with a minSdk of at most 21,
                or increase this project's minSdk version to at least 23,
                or use tools:overrideLibrary="com.facebook.react" to force usage (may lead to runtime failures)
```

**Comment by brendan1809** [comment]
> facing the same error on react native 0.74
> 
> ```
> 
> C:\Freelance\Meetkor\android\app\src\debug\AndroidManifest.xml Error:
>         uses-sdk:minSdkVersion 21 cannot be smaller than version 23 declared in library [com.facebook.react:react-android:0.74.1] C:\Users\acer\.gradle\caches\transforms-3\817bf4b774b7361c46230e491303d01c\transformed\jetified-react-android-0.74.1-debug\AndroidManifest.xml as the library might be using APIs not available in 21
>         Suggestion: use a compatible library with a minSdk of at most 21,
>                 or increase this project's minSdk version to at least 23,
>                 or use tools:overrideLibrary="com.facebook.react" to force usage (may lead to runtime failures)
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:processDebugMainManifest'.
> > Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 23 declared in library [com.facebook.react:react-android:0.74.1] C:\Users\acer\.gradle\caches\transforms-3\817bf4b774b7361c46230e491303d01c\transformed\jetified-react-android-0.74.1-debug\AndroidManifest.xml as the library might be using APIs not available in 21
>         Suggestion: use a compatible library with a minSdk of at most 21,
>                 or increase this project's minSdk version to at least 23,
>                 or use tools:overrideLibrary="com.facebook.react" to force usage (may lead to runtime failures)
> ```

@AliYar-Khan 
In your android/build.gradle folder just modify your minSDK to 23 
```
buildscript {
  ...
        minSdkVersion = 23
  ...
}
```
