### ISSUE TITLE
Video URI on Android incorrect [🐛] 

### ISSUE THREAD

**Issue by arhmnsh** [react-native-image-picker/react-native-image-picker#1561]
### Description

When picking a video file from an Android device, the URI returned doesn't work, when I visit the returned URI in Chrome, it says file does not exist. 
Works fine on iOS

Sample response from the `launchImageLibrary`:
`{"fileName": "90510942_824331778088534_328930688839450624_n.mp4", "fileSize": 320924, "uri": "content://com.google.android.apps.photos.contentprovider/-1/2/content%3A%2F%2Fmedia%2Fexternal%2Fvideo%2Fmedia%2F48/ORIGINAL/NONE/2051731147"}`

### How to repeat issue and example

- step to reproduce the issue
- ...

### Solution

What needs to be done to address this issue?

### Additional Information

- Image Picker version: ^3.1.1
- React Native version: ^0.61.5
- Platform: Android
- Development Operating System: macOS
- Dev tools: Android Studio

**Comment by Janak-Nirmal** [comment]
Any solution for this ?

**Comment by sekizlipenguen** [comment]
> Any solution for this ?

+1

**Comment by sekizlipenguen** [comment]
this is a very serious problem and a solution is needed.

**Comment by sekizlipenguen** [comment]
> Any solution for this ?

I applied a temporary solution;

`yarn add react-native-fs`


```
import RNFS from 'react-native-fs';

async videoUrlCopy(uri, fileName) {
        const destPath = `${RNFS.TemporaryDirectoryPath}/${fileName}`;
        await RNFS.copyFile(uri, destPath);
        await RNFS.stat(destPath);
        return destPath;
    }
```

**Comment by ravirajn22** [comment]
I can't understand the problem you'r facing. For iOS and Android the image file you get is the copy of the original image after applying any width and height constraints.

For video file in iOS you get a compressed copy of the original file (default behaviour of the picker) where as on android we don't make a copy of the original file but give temporary access to the original file for that session via content URI. I can make a copy of the original video file in temp cache directory like I do for android images, but don't know if it's the right way to handle video files.

**Comment by sekizlipenguen** [comment]
> I can't understand the problem you'r facing. For iOS and Android the image file you get is the copy of the original image after applying any width and height constraints.
> 
> For video file in iOS you get a compressed copy of the original file (default behaviour of the picker) where as on android we don't make a copy of the original file but give temporary access to the original file for that session via content URI. I can make a copy of the original video file in temp cache directory like I do for android images, but don't know if it's the right way to handle video files.

The method(providers) used negatively affects many plugins. 

The method you(temp cache) suggested will be very helpful in this regard.
We will not need additional development.

**Comment by ravirajn22** [comment]
@sekizlipenguen @Janak-Nirmal @arhmnsh What do you want to do with the video file?
- Play it in your app? (Content URI will do for that)
- Upload to ur backend? (Content URI will do for that)
- Share it with other apps? (I don't know how share works)

@arhmnsh why do u enter the URI in chrome, thats not how it works.

Tell your use cases.

**Comment by luisfuertes** [comment]
I want use recorded video uri (example returned uri "content://com.xiaomi_app.imagepickerprovider/cacheDir/rn_image_picker_lib_temp_24ef6f34-5e12-45ef-b231-6b07f37b4870.mp4") with RNFS or react-native-ffmpeg, but if i do:
```
const fileStat = await RNFS.stat(res.uri)
```

RNFS return:
```
Error: File does not exist
```

Any idea to fix it? I have to save it first?

**Comment by HarshitMadhav** [comment]
+1 Same issue I am facing from today! Any quick fix?

**Comment by nyanev** [comment]
> @sekizlipenguen @Janak-Nirmal @arhmnsh What do you want to do with the video file?
> 
> * Play it in your app? (Content URI will do for that)
> * Upload to ur backend? (Content URI will do for that)
> * Share it with other apps? (I don't know how share works)
> 
> @arhmnsh why do u enter the URI in chrome, thats not how it works.
> 
> Tell your use cases.

How can I upload to a custom backend from contentUri?

**Comment by harshitsmt** [comment]
@ravirajn22  currently getting uri like this content://com.google.android.apps.photos.contentprovider/-1/2/content%3A%2F%2Fmedia%2Fexternal%2Fvideo%2Fmedia%2F124/ORIGINAL/NONE/1711542917

**Comment by arhmnsh** [comment]
> @sekizlipenguen @Janak-Nirmal @arhmnsh What do you want to do with the video file?
> 
> * Play it in your app? (Content URI will do for that)
> * Upload to ur backend? (Content URI will do for that)
> * Share it with other apps? (I don't know how share works)
> 
> @arhmnsh why do u enter the URI in chrome, thats not how it works.
> 
> Tell your use cases.

@ravirajn22 I just put it in chrome to check if the URI is valid, and it wasn't. If the URI is valid, it should play the video in chrome, as it does on iOS.

When uploading the URI to backend, it gives error on Android, whereas it works fine on iOS.

**Comment by lsyiverson** [comment]
Just curious about the implementation. I found there is a method `getAppSpecificStorageUri` to make a file copy inside the app specific storage for future use, but why it only applied to the photos rather than also include for the vidoes?

**Comment by DaScientist** [comment]
Any solution to how to upload the video using the content uri?

**Comment by codal-mpawar** [comment]
> > Any solution for this ?
> 
> I applied a temporary solution;
> 
> `yarn add react-native-fs`
> 
> ```
> import RNFS from 'react-native-fs';
> 
> async videoUrlCopy(uri, fileName) {
>         const destPath = `${RNFS.TemporaryDirectoryPath}/${fileName}`;
>         await RNFS.copyFile(uri, destPath);
>         await RNFS.stat(destPath);
>         return destPath;
>     }
> ```

Not working in android 9

**Comment by SiyabongaNzulwana** [comment]
@sekizlipenguen I am trying to implement your solution, but its not working for me, were you able to play the video from that path returned by your function? after implementing your solution I got the uri like this : `uri:  file://data/user/0/za.co.{appname}/cache/rn_image_picker_lib_temp_e4ef1c56-ca23-4f81-85f2-a11da9725138.mp4` should this be working or am I missing something?

**Comment by Hosar** [comment]
@ramos07 solution works for me but with a slightly change:
    ```
const { originalFilepath } = await stat(videoUri);
    const uri = `file://${originalFilepath}`
    return uri;
```

**Comment by afilp** [comment]
We also want to upload the file to server and the video uploads with "zero" bytes (using 'react-native-blob-util'). We assume this is because `react-native-blob-util` considers this as a link and does not get the proper bytes? Not sure about this.

**Comment by rdjuric** [comment]
> @sekizlipenguen @Janak-Nirmal @arhmnsh What do you want to do with the video file?
> 
> * Play it in your app? (Content URI will do for that)
> * Upload to ur backend? (Content URI will do for that)
> * Share it with other apps? (I don't know how share works)
> 
> @arhmnsh why do u enter the URI in chrome, thats not how it works.
> 
> Tell your use cases.

I don't think Content URI is enough to upload to our backend. When trying to upload the file to firebase storage, I get a `Permission Denial` error when using the Content URI.

Permission Denial: reading com.google.android.apps.photos.contentprovider.impl.MediaContentProvider uri content://com.google.android.apps.photos.contentprovider/-1/2/content:/media/external/video/media/36/ORIGINAL/NONE/video/mp4/1860530892 from pid=7391, uid=10154 requires the provider be exported, or grantUriPermission()

**Comment by UmarFarooqCA** [comment]
Any solution?

**Comment by rdjuric** [comment]
@UmarFarooqCA 

What we're doing is checking if the URI of the file starts with `content://`, if it does we use `RNFS` to create a temporary copy of that file. We make the upload using the URI of the temporary copy and delete it once we finishes.

**Comment by UmarFarooqCA** [comment]
@rdjuric 
Thanks for the reply. yes, I also tried `react-native-fs` but `exists(filepath: string): Promise<boolean>` returned `false` file does not exists!. work fine on images

**Comment by rdjuric** [comment]
@UmarFarooqCA 

No worries! Here's the piece of code we use in case it helps:


```
if (path.startsWith('content://')) path = await copyVideo(path, fileName);

// copyVideo is this
export async function copyVideo(uri, fileName) {
	const destPath = `${RNFS.TemporaryDirectoryPath}/temp_${fileName}.mp4`;
	await RNFS.copyFile(uri, destPath).catch((err) => console.log(err));
	const a = await RNFS.stat(destPath);
	return destPath;
}
```

**Comment by UmarFarooqCA** [comment]
@rdjuric 
I got an error!

`Possible Unhandled Promise Rejection (id: 0):
Error: File does not exist
promiseMethodWrapper@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.<my_app>&modulesOnly=false&runModule=true:5573:45
stat@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.<my_app>&modulesOnly=false&runModule=true:295180:30
copyVideo$@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.<my_app>&modulesOnly=false&runModule=true:294916:74
tryCatch@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.<my_app>&modulesOnly=false&runModule=true:1651:23
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.<my_app>&modulesOnly=false&runModule=true:1631:34
tryCatch@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.<my_app>&modulesOnly=false&runModule=true:1651:23
invoke@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.<my_app>&modulesOnly=false&runModule=true:1689:30
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.<my_app>&modulesOnly=false&runModule=true:1695:19
tryCallOne@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.<my_app>&modulesOnly=false&runModule=true:28890:16
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.<my_app>&modulesOnly=false&runModule=true:28991:27
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.<my_app>&modulesOnly=false&runModule=true:30165:26
_callTimer@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.<my_app>&modulesOnly=false&runModule=true:30065:17
_callReactNativeMicrotasksPass@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.<my_app>&modulesOnly=false&runModule=true:30100:17
callReactNativeMicrotasks@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.<my_app>&modulesOnly=false&runModule=true:30308:44
__callReactNativeMicrotasks@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.<my_app>&modulesOnly=false&runModule=true:5946:46
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.<my_app>&modulesOnly=false&runModule=true:5724:45
__guard@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.<my_app>&modulesOnly=false&runModule=true:5929:15
flushedQueue@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.<my_app>&modulesOnly=false&runModule=true:5723:21
flushedQueue@[native code]
invokeCallbackAndReturnFlushedQueue@[native code]`

**Comment by ckaznable** [comment]
I used [react-native-file-access](https://github.com/alpha0010/react-native-file-access) to solve `content://` problem.

**Comment by ntalakhadze** [comment]
> 

When I install version 5, I get this error while running app on android.

Execution failed for task ':react-native-image-picker:compileDebugJavaWithJavac'.

**Comment by Awaissk** [comment]
I was facing this issue on **Android 13** but other Android versions were working fine for me so I came up with a hack to solve it. I hope it may also help others.

The main problem I was facing was "fileName" did not have the file extension in it instead it was plain "file id". So I simply handled the file names with no extension using mimeType. E.g. these were the responses on Android 10 and Android 13 for me: 

**Android 10** 
`"fileObject": {"assets": [{"bitrate": 14752151, "duration": 11, "fileName": "raw:/storage/emulated/0/Download/1000000036.mp4", "fileSize": 20774041, "height": 1280, "type": "video/mp4", "uri": "content://com.android.providers.downloads.documents/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2F1000000036.mp4", "width": 720}]}`

**Android 13**
`"fileObject": {"assets": [{"bitrate": 14752151, "duration": 11, "fileName": "1000000036", "fileSize": 20774041, "height": 1280, "type": "video/mp4", "uri": "content://media/picker/0/com.android.providers.media.photopicker/media/1000000036", "width": 720}]}`

Android 10 fileName key had **.mp4** extension in the end Android 13 did not. So this is what I did

```      
     const options = {  
        mediaType: 'video',
        videoQuality: 'low',
        storageOptions: {
          skipBackup: true,
          path: 'images',
        }
      }
      launchImageLibrary(options, (response) => {
        console.log('Response launchImageLibrary: ', response);
        if (response.didCancel) {
          console.log('User cancelled');
        } else if (response.error) {
          console.log('Error: ', response.error);
        } else {
        let extension = '.mp4'
        let mimetype= response.assets[0].type
        if (mimetype.includes('video/x-msvideo')) { extension = '.avi' }
        if (mimetype.includes('video/mp4')) { extension = '.mp4' }
        if (mimetype.includes('video/mpeg')) { extension = '.mpeg' }
        if (mimetype.includes('video/ogg')) { extension = '.ogv' }
        if (mimetype.includes('video/mp2t')) { extension = '.ts' }
        if (mimetype.includes('video/webm')) { extension = '.webm' }
        if (mimetype.includes('video/3gpp')) { extension = '.3gp' }
        if (mimetype.includes('video/3gpp2')) { extension = '.3g2' }
        response.assets[0].fileName= response.assets[0].fileName + extension
        // call UPLOAD API here with response
        }
      })
```
Do note that my Backend API was using `fileName` key to save file so after this hack video uploads on Android 13 also started working fine for me. Hope it helps someone.
