### ISSUE TITLE
[🐛] Error: Unable to resolve module `./internal/nativeInterface` from `node_modules\react-native-image-picker\src\index.ts`

### ISSUE THREAD

**Issue by stevenjose1728** [react-native-image-picker/react-native-image-picker#1562]
### Description

Hey guys, since yesterday i have this problem running my app.

**Error: Unable to resolve module `./internal/nativeInterface` from `node_modules\react-native-image-picker\src\index.ts`:**

None of these files exist:
  * node_modules\react-native-image-picker\src\internal\nativeInterface(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules\react-native-image-picker\src\internal\nativeInterface\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (C:\wamp64\www\delivery\app\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:163:15)
    at ResolutionRequest.resolveDependency (C:\wamp64\www\delivery\app\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (C:\wamp64\www\delivery\app\node_modules\metro\src\node-haste\DependencyGraph.js:287:16)

im importing imagepicker like this: **import * as ImagePicker from 'react-native-image-picker/src/index';**

### How to repeat issue and example

When i run react-native run android or react-native start have this problem, but when i comment the import and fuctions of this import, the app can run normally and after discomment and wont have this problem until reinstall with react-native run android or after 20min have this problem again

### Additional Information

- Image Picker version: 3.1.1
- React Native version: 0.63.3
- Platform: Android 9
- Development Operating System: Windows

**Comment by ravirajn22** [comment]
restart packager by running `react-native start --reset-cache`.

**Comment by remi-cbd** [comment]
Hello ! I am having similar issue and these steps have not solved my problem :
`rm node_modules/ -rf`
`npm install`
`npx react-native start --reset-cache`

**Comment by masf4dhil** [comment]
> restart packager by running `react-native start --reset-cache`.

this work me thanks
