### ISSUE TITLE
[🐛] launchImageLibrary only invoke once on IOS

### ISSUE THREAD

**Issue by chj-damon** [react-native-image-picker/react-native-image-picker#1568]
### Description

I'm using `launchImageLibrary` method to select images from the album. It works for the first time. but then it doesn't work anymore.

### How to repeat issue and example

- step to reproduce the issue
- ...

### Solution

What needs to be done to address this issue?

### Additional Information

- Image Picker version: 3.1.2
- React Native version: 0.63.4
- Platform: IOS
- Development Operating System: MacOS
- Dev tools: xcode Version 12.2 (12B45b)

**Comment by abhilashdhone** [comment]
same here bro, if you get the solution, please let us know

**Comment by Johan-dutoit** [comment]
Are there any error messages in the console?

**Comment by abhilashdhone** [comment]
its happening to my tester for production build.

**Comment by ravirajn22** [comment]
see this thread to fix it, https://github.com/react-native-image-picker/react-native-image-picker/issues/1456

Still if you face the issue ping here, I will open
