### ISSUE TITLE
[🐛] Regression: iOS Linking issue on RN <=0.62 

### ISSUE THREAD

**Issue by ThePooN** [react-native-image-picker/react-native-image-picker#1570]
### Description

Following [this commit](https://github.com/react-native-image-picker/react-native-image-picker/commit/dc2e1cd5baa878df90e9f747ad0db1bf81f41731), `pod install` fails with:
> [!] Unable to find a specification for `React-Core` depended upon by `react-native-image-picker`

### How to repeat issue and example

- Bootstrap a React Native project, with RN version <0.63 and react-native-image-picker version 3.1.3
- `cd ios && pod install` fails

### Solution

The commit applied is correct according to https://github.com/facebook/react-native/issues/29633#issuecomment-694187116, but only on RN 0.63. Older versions should depend on `React/Core` instead (`/` instead of `-`).

### Additional Information

- Image Picker version: 3.1.3
- React Native version: RN<=0.62
- Platform: iOS
- Development Operating System: macOS Catalina
- Dev tools: Xcode 12.1, iOS 14.1

**Comment by ravirajn22** [comment]
@ThePooN where you able to solve your problem?

**Comment by ravirajn22** [comment]
Sorry @ThePooN we only support the latest version of react-native, I request you to fork this lib and make particular change and use in your project.

**Comment by ThePooN** [comment]
> @ThePooN where you able to solve your problem?

My current work-around is to stay on 3.1.2.

> Sorry @ThePooN we only support the latest version of react-native, I request you to fork this lib and make particular change and use in your project.

Sadly, we don't have the resources to maintain a fork. BTW, your README shows install instructions for versions way older than the latest - including RN<0.63 which 3.1.3 broke.
