### ISSUE TITLE
Return image + custom sized thumbnail

### ISSUE THREAD

**Issue by jbcullis** [react-native-image-picker/react-native-image-picker#1572]
** Feature Request
Support for returning resized image, plus thumbnail image.

**Comment by ravirajn22** [comment]
Explain clearly the use case and how providing this feature will help maintainers and library users. You'r the only person who have requested for this feature. So it is hard to support it. 

Closing it for now. Update here if you have any comments, I am happy to review it.

**Comment by afilp** [comment]
@ravirajn22 I am not the OP, I also have the need when picking a hi-res image (especially in iOS) to also have a "smaller size" thumbnail created.

The use case is that I want to show all picked images in `Flatlist` before uploading them, without the app crashing (it happened in iOS when I referenced 20 "hi-res" images that were picked and I scrolled down).
