### ISSUE TITLE
Camera and Gallery auto closes on iOS after a brief second [🐛] 

### ISSUE THREAD

**Issue by andordavoti** [react-native-image-picker/react-native-image-picker#1573]
### Description

When calling launchCamera or launchImageLibrary, the camera and the gallery is only shown for a brief second before it disappears on iOS. 

Same issue on v2.3.4 when using 

ImagePicker.launchCamera
or
ImagePicker.launchImageLibrary

Using 

[Video showing the issue.](https://drive.google.com/file/d/1pmk0pBcnGvTldH_TqJmtrudM7vi3f9kN/view?usp=sharing)

### How to repeat issue and example

- step to reproduce the issue:
- call launchCamera or launchImageLibrary

### Additional Information

- Image Picker version: 3.1.3
- React Native version: 0.63.4
- Platform: iOS
- Development Operating System: MacOS
- Dev tools: Xcode version: 12.3, iOS version: 14.2

**Comment by andordavoti** [comment]
Adding a setTimeout function that waits 200 milliseconds before opening the camera or gallery so the "react-native-actions-sheet" can close solved the issue:))

**Comment by Danushka96** [comment]
[https://github.com/react-native-image-picker/react-native-image-picker/issues/728#issuecomment-514295052](https://github.com/react-native-image-picker/react-native-image-picker/issues/728#issuecomment-514295052)
