### ISSUE TITLE
[🌟] Setting default camera

### ISSUE THREAD

**Issue by jbcullis** [react-native-image-picker/react-native-image-picker#1576]
It would be great to set the default camera when using launchCamera

I'm using an S9+ and an iPhone 11. The S9 defaults to selfie mode and the iPhone defaults to the back camera, in our use case it would be great to default to the back camera in all cases.

** Further Info
On android, it appears to be using the current preferred camera. So if you open up the phone camera app and change it to selfie, react-native-image-picker will open in selfie, however if you change the setting from RNIP then it does not seem to save the changed preference.
I'm looking into solutions at the moment but it looks like there isn't much beyond the following option that is reportedly unreliable:
action.putExtra("android.intent.extras.CAMERA_FACING", 1);

**Comment by ravirajn22** [comment]
Yes there is no proper API to open front or back camera via intents in android (iOS supports it). I also know few hacks exist, but that does work in all devices.

**Comment by ravirajn22** [comment]
I am closing this for now, if you have a solid code that works in most of devices without too much complexity. I am ready to commit it.
