### ISSUE TITLE
[🐛] This library does not require Manifest.permission.CAMERA, if you add this permission in manifest then you have to obtain the same

### ISSUE THREAD

**Issue by niloofarSadeghi76** [react-native-image-picker/react-native-image-picker#1577]
Hi,
I'm going to use the latest version of this library. and when i try to use it, it sent me this error:
**"This library does not require Manifest.permission.CAMERA, if you add this permission in manifest then you have to obtain the same."**

I need camera permission for another packages so i can not delete it, what am i suppose to do to solve this problem?

react native version: 0.61.5
image picker version: 3.1.3
thank you

**Comment by Johan-dutoit** [comment]
You'd have to request the permission using something like `react-native-permissions`.

**Comment by PendragonDevelopment** [comment]
I have this issue as well - we're getting the permissions just fine, but it's popping up an alert with that error message that I can't seem to turn off.

**Comment by LaVielle** [comment]
I'm getting the same issue when calling `launchImageLibrary` even though I removed the CAMERA permission from AndroidManifest. Any idea what could cause this, and how to fix it?
I tried `./gradlew clean` and reinstall the app in case there was some caching issue after I removed the permission, but no luck...

**Comment by nicolak** [comment]
Note: This library does not require Manifest.permission.CAMERA, if your app declares as using this permission in manifest then you have to obtain the permission before using `launchCamera`.

It worked for me.

`import { PermissionsAndroid } from 'react-native';`

```
const requestCameraPermission = async () => {
  try {
    const granted = await PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.CAMERA,
      {
        title: "App Camera Permission",
        message:"App needs access to your camera "
        buttonNeutral: "Ask Me Later",
        buttonNegative: "Cancel",
        buttonPositive: "OK"
      }
    );
    if (granted === PermissionsAndroid.RESULTS.GRANTED) {
      console.log("Camera permission given");
    } else {
      console.log("Camera permission denied");
    }
  } catch (err) {
    console.warn(err);
  }
};
```

Good job.

**Comment by ankitjaiswaldxc** [comment]
`import {launchCamera, launchImageLibrary} from 'react-native-image-picker';


const App = () => {

  const requestCameraPermission = async () => {
    try {
      const granted = await PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.CAMERA,
        {
          title: "App Camera Permission",
          message:"App needs access to your camera ",
          buttonNeutral: "Ask Me Later",
          buttonNegative: "Cancel",
          buttonPositive: "OK",
        }
      );
      if (granted === PermissionsAndroid.RESULTS.GRANTED) {
        console.log("Camera permission given");
        openCamera();
      } else {
        console.log("Camera permission denied");
      }
    } catch (err) {
      console.warn(err);
    }
  };


  const openCamera = () => {
    //Alert.alert('asdasd');
    const options = {
      storageOptions: {
        path: 'images',
        mediaType: 'photo',
      },
      includeBase64: true,
    };

    launchCamera(options, response => {
      console.log('Response =', response);
    });
  };

  return (
    <View>
      <Text>hello</Text>
      <Button title={'Open camera'} onPress={() => requestCameraPermission()} />
    </View>
  );
};

export default App;`
