### ISSUE TITLE
[🐛] App crashing after selecting image.

### ISSUE THREAD

**Issue by akshaykatale99** [react-native-image-picker/react-native-image-picker#1582]
### Description

Application crashing after selecting an image from the gallery.

### Additional Information

- Image Picker version: 3.1.3
- React Native version: 0.63.3
- Platform: Android
- Development Operating System: OS: Windows 10 10.0.19041
- Dev tools: Android Studio: Version  4.1.0.0 AI-201.8743.12.41.6953283

**Comment by sekizlipenguen** [comment]
There are too many problems.

**Comment by sekizlipenguen** [comment]
solution of this;

Options.java 

`durationLimit = 0;
        if (options.hasKey("durationLimit")) {
          durationLimit = options.getInt("durationLimit");
        }`

`package com.imagepicker;

import com.facebook.react.bridge.ReadableMap;
import android.text.TextUtils;

public class Options {
    Boolean pickVideo = false;
    Boolean includeBase64;
    int videoQuality = 1;
    int quality;
    int maxWidth;
    int maxHeight;
    Boolean saveToPhotos;
    int durationLimit;

    Options(ReadableMap options) {
        if (options.getString("mediaType").equals("video")) {
            pickVideo = true;
        }
        includeBase64 = options.getBoolean("includeBase64");
        String videoQualityString = options.getString("videoQuality");
        if(!TextUtils.isEmpty(videoQualityString) && !videoQualityString.toLowerCase().equals("high")) {
            videoQuality = 0;
        }
        quality = (int) (options.getDouble("quality") * 100);
        maxHeight = options.getInt("maxHeight");
        maxWidth = options.getInt("maxWidth");
        saveToPhotos = options.getBoolean("saveToPhotos");

        durationLimit = 0;
        if (options.hasKey("durationLimit")) {
          durationLimit = options.getInt("durationLimit");
        }
    }
}
`

**Comment by JohnTendik** [comment]
Are you passing any options? Pass null for the first argument

```
launchImageLibrary(null, (imageItem) => {
  console.log(imageItem);
});
```

@sekizlipenguen selam dostum ^^

**Comment by akshaykatale99** [comment]
I am using this code for image pick from the gallery.

    const pickImage = async () => {
            launchImageLibrary({
                mediaType: 'photo',
                quality: 0.2
            }, (e) => {
                console.log(e);
            })
        };

I am getting all image data in console.log after picking the image but the application still force closes after that.

		{
			"fileName": "rn_image_picker_lib_temp_0eb19742-54e3-4d8d-9aad-2fcff2132ce6.jpg", 
			"fileSize": 13581, 
			"height": 702, 
			"type": "image/jpeg", 
			"uri": "content://com.wadp.myvipni.imagepickerprovider/cacheDir/rn_image_picker_lib_temp_0eb19742-54e3-4d8d-9aad-2fcff2132ce6.jpg", 
			"width": 703
		}

**Comment by ravirajn22** [comment]
@sekizlipenguen show ur JS code.

**Comment by ravirajn22** [comment]
@akshaykatale99 create a simple react-native project and include only this library and check if this issue is reproducible.

**Comment by ravirajn22** [comment]
@sekizlipenguen and @akshaykatale99 ?

**Comment by ravirajn22** [comment]
Closing it, no info provided.

**Comment by amazingCoding** [comment]
the easy jod is 
```
launchImageLibrary({ mediaType: "photo", durationLimit: 0 } as any, launchCallBack)
```
