### ISSUE TITLE
Native Modules are not installing[🐛] 

### ISSUE THREAD

**Issue by Andrapyre** [react-native-image-picker/react-native-image-picker#1585]
### Description

Native Modules are not installing and this code is generating the following error:

Code: launchCamera({mediaType: 'photo'}, (response)=> {console.log(response)})

Error: TypeError: null is not an object (evaluating '_reactNative.NativeModules.ImagePickerManager.launchCamera')

### Additional Information

- Image Picker version: [3.1.4.]
- React Native version: [~0.63.4]
- Platform: [Both]
- Development Operating System: [Windows]
- Dev tools: [Android SDK version: 11]

**Comment by ravirajn22** [comment]
How do you import launchCamera? show that code.
You have to do like this `import {launchCamera, launchImageLibrary} from 'react-native-image-picker';`

**Comment by Andrapyre** [comment]
Yes, exactly.

import {launchCamera, launchImageLibrary} from 'react-native-image-picker';
launchCamera({mediaType: 'photo'}, (response)=> {console.log(response)})

**Comment by ravirajn22** [comment]
Make sure you have installed the library properly. Try deleting node_modules and reinstall. Remove all caches like metro, watchman etc.

**Comment by Andrapyre** [comment]
Just ran the following command and am still getting the same error.

`del %appdata%\Temp\react-native-* & cd android & gradlew clean & cd .. & del node_modules/ & npm cache clean --force & npm install & npm start -- --reset-cache`

**Comment by ravirajn22** [comment]
metro and watchman? clear those caches.

**Comment by ravirajn22** [comment]
Closing it for now. Update here if you have any comments, I am happy to review it.

**Comment by qchau97** [comment]
Hi, did you get any solution for this problem?
