### ISSUE TITLE
[🐛] LaunchCamera not working on One Plus devices

### ISSUE THREAD

**Issue by hardikmehta88999** [react-native-image-picker/react-native-image-picker#1586]
### Description

Explain the bug in as much detail as possible
It is working on Samsung, Mi but not working on all "One Plus" devices. 

### How to repeat issue and example

- step to reproduce the issue
- ...

### Solution

What needs to be done to address this issue?

### Additional Information

- Image Picker version: [FILL THIS OUT: Be specific, filling out "latest" here is not enough.]
- React Native version: [FILL THIS OUT: Be specific, filling out "latest" here is not enough.]
- Platform: [FILL THIS OUT: iOS, Android, or both?]
- Development Operating System: [FILL THIS OUT: Are you developing on MacOS, Linux, or Windows?]
- Dev tools: [FILL THIS OUT: Xcode or Android Studio version, iOS or Android SDK version, if applicable] navigation crash for Android

**Comment by Complex2Simple** [comment]
you can find the resolution  with issue #1587

**Comment by ravirajn22** [comment]
@hardikmehta88999 provide more details about the issue.

**Comment by ravirajn22** [comment]
As already mentioned @hardikmehta88999.
react-native-image-picker: 2.3.3 is not supported. So closing this.
