### ISSUE TITLE
[🐛] intent.resolveActivity return null on some Android 11 mobiles

### ISSUE THREAD

**Issue by Complex2Simple** [react-native-image-picker/react-native-image-picker#1587]
### Some Android 11 Phones cannot open camera or imagePicker

Because intent.resolveActivity return null 

### Solution

I suggest you use 
"activity.getPackageManager().hasSystemFeature(PackageManager.FEATURE_CAMERA_ANY)"
to replace
"if (cameraIntent.resolveActivity(getPackageManager()) == null)"
then you can close this bug.

### Additional Information

- Image Picker version: last version
- React Native version: last version
- Platform: Android
- Development Operating System: window
- Dev tools: 30
- Android : Android 11 ,xiaomi ,1+8t

**Comment by hardikmehta88999** [comment]
Could u elaborate more on which file should I made the changes?

**Comment by Complex2Simple** [comment]
in class ImagePickerModule line 88 ,you can change the code like below
```
    if (cameraIntent.resolveActivity(reactContext.getPackageManager()) == null)
    //change to 
    // if(reactContext.getPackageManager().hasSystemFeature(PackageManager.FEATURE_CAMERA_ANY))
```

**Comment by ravirajn22** [comment]
Hi, what is your `targetSdkVersion`?

**Comment by hardikmehta88999** [comment]
targetSdkVersion:29 
react-native: 0.62.2
react-native-image-picker: 2.3.3

**Comment by ravirajn22** [comment]
Sorry, react-native-image-picker: 2.3.3 is no longer supported upgrade to latest version, check breaking changes and tell if the issue persisit.

**Comment by Complex2Simple** [comment]
> Hi, what is your `targetSdkVersion`?
> 
> hardikmehta88999 and Complex2Simple can you provide more details, like does the app crash or if there is some error from the library etc.

targetSdkVersion:30
react-native: 0.62.2
react-native-image-picker: 3.1.3
And in class ImagePickerModule line 90 , the method resolveActivity return null then  error occured
i think u can fix it with the example
```
    if (cameraIntent.resolveActivity(reactContext.getPackageManager()) == null)
    //change to 
    // if(reactContext.getPackageManager().hasSystemFeature(PackageManager.FEATURE_CAMERA_ANY))
```

**Comment by ravirajn22** [comment]
Yes to target sdk30 there needs a change to be done in the lib. I will do that and commit.

**Comment by Complex2Simple** [comment]
Thank U

**Comment by TNicholson11** [comment]
Hi there, we're still seeing this issue. Is there still a plan to implement a fix? It appears the issue occurs on Pixel devices specifically (but works with Samsung, etc). We are happy to temporarily rollback our targetSdk to 29 temporarily but would like to progress to 30 whenever possible. Thank you!

targetSdkVersion: 30
react-native: 0.63.3
react-native-image-picker: 3.3.2
