### ISSUE TITLE
[🐛] 

### ISSUE THREAD

**Issue by zendevil** [react-native-image-picker/react-native-image-picker#1588]
### Description

When calling launchImageLibrary, I'm getting the following:
<img width="427" alt="Screen Shot 2021-01-22 at 7 44 43 AM" src="https://user-images.githubusercontent.com/30054030/105436718-b4e14500-5c85-11eb-811f-1b7e5012c64b.png">

### How to repeat issue and example
import {launchImageLibrary} from 'react-native-image-picker'
launchImageLibrary()

### Solution

The camera roll should show so that the user can pick photos and videos.

### Additional Information

- Image Picker version: 3.1.4
- React Native version: 0.63.4
- Platform: iOS 
- Development Operating System: macOS 
- Dev tools: Xcode

**Comment by ravirajn22** [comment]
Did you perform `cd ios && pod install` after installing the lib?

**Comment by zendevil** [comment]
The issue isn't solved. I did do ```cd ios && pod install```.

**Comment by ravirajn22** [comment]
Provide a reproducible demo,its working properly in my test

**Comment by ckalika** [comment]
@ravirajn22 The issue is that in the example, you're exporting *. Can I politely suggest adding the following to the index file:

```
export default {
  launchCamera,
  launchImageLibrary
}

```
This makes it so that you can do something like this:
```import ImagePicker from 'react-native-image-picker'```

instead of
```import * as ImagePicker from 'react-native-image-picker```

@zendevil

**Comment by ckalika** [comment]
@zendevil

```import * as ImagePicker from 'react-native-image-picker```

This should solve your issue.

**Comment by ravirajn22** [comment]
@ckalika @zendevil I am able to use this library by importing the way as mentioned in the docs.
`cd ios && pod install` make sure to reinstall the app after doing this.
