### ISSUE TITLE
[🐛] crash after click back button launchImageLibrary in android

### ISSUE THREAD

**Issue by votuan22** [react-native-image-picker/react-native-image-picker#1589]
### Description

after call launchImageLibrary and click button go back, app crash.

### Additional Information

- Image Picker version: 3.1.4
- React Native version: 0.63.2
- Platform: android

### Error logcat 

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=13002, result=0, data=null} to activity {jp.logmoni.ugoita/com.mo_sanka.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri android.content.Intent.getData()' on a null object reference

**Comment by ravirajn22** [comment]
@votuan22 does it happen in all devices or only for particular device.

**Comment by votuan22** [comment]
I test in simulator android

**Comment by ravirajn22** [comment]
Give the following details
1 Android version
2 The steps to follow to reproduce the issue, exact steps
3 Code to Reproduce (is possible)

**Comment by votuan22** [comment]
1. Android version 10
2. 
2.1 call function   launchImageLibrary(
        {
          mediaType: 'photo',
          includeBase64: false,
          maxHeight: 200,
          maxWidth: 200,
        })
2.2 Click back button
![Screenshot from 2021-01-22 17-35-45](https://user-images.githubusercontent.com/61284443/105480436-56918200-5cd8-11eb-82d0-ac30f909114c.png)

**Comment by ravirajn22** [comment]
I am not able to reproduce upload your sample project

**Comment by tboerc** [comment]
It is happening with me too on a real device.

**Information**
- Image Picker: 3.1.4
- React Native: 0.63.3
- Platform: Android 10

I'm calling this exact function:

```javascript
const onChangePicture = useCallback(() => {
    launchImageLibrary({mediaType: 'photo', includeBase64: false});
}, []);
```

The library opens normally, but if I press the top back button or hardware back button, the app crashes.

**Comment by ravirajn22** [comment]
Both of you people are using the API wrongly, 
The API is `launchImageLibrary(options, callBackFunction);`

**Comment by votuan22** [comment]
Java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri android.content.Intent.getData() 
I have same issue with code    
launchImageLibrary(
        {
          mediaType: 'photo',
          includeBase64: false,
        },
        (response) => {
          setImage(Object.assign(response));
        },
      );
