### ISSUE TITLE
[🐛] Android - response incorrect image width when capture photo on portrait mode

### ISSUE THREAD

**Issue by khanhdh-bp** [react-native-image-picker/react-native-image-picker#1590]
### Description

When I capture photo on portrait mode, the width of image always bigger than height.

### How to repeat issue and example

- call function launchCamera to open camera
- capture photo on portrait
- see the response object, width of image is bigger than height although we use portrait to capture

### Additional Information

- Image Picker version: 3.1.3
- React Native version: 0.63.4
- Platform: Android
- Development Operating System: MacOS
- Dev tools: Android Studio version 4.1, Android SDK version 24 (android 7)

**Comment by ravirajn22** [comment]
That is because the orientation of the image will be different, which you have to consider while checking if its portrait or landscape. For example, The `Image` component of react-native will consider orientation and present the image correctly. Try it. Read about orientation online.

**Comment by guytepper** [comment]
Hi @ravirajn22 - I'm not sure this is the problem. 

When I'm taking a portrait image - the actual image created changes it's orientation to landscape. 
Therefore the image dimensions are correct - but the created image is not aligned correctly. 

This happens only on android.
