### ISSUE TITLE
Display captured image from launch camera[🐛] 

### ISSUE THREAD

**Issue by ravi-poonia** [react-native-image-picker/react-native-image-picker#1592]
### Description

I'm trying to display the captured image using `launchCamera` .
the final image `uri` is like: `file:///content://com.test.imagepickerprovider/cacheDir/rn_image_picker_lib_temp_0dbf2b47-6b1d-4637-a860-c0e4dfbc4718.jpg`

When I try to render this image, I just shows blank space.

- Image Picker version: 3.1.4
- React Native version: 0.63.4
- Platform: android
- Development Operating System: macOs

**Comment by ravirajn22** [comment]
How come `file:///` is prepended. Give the exact response to the Image component.
