### ISSUE TITLE
[🐛] HUAWEI mate30 pro,  "系统服务 检测到  删除了图片，已成功拦截"

### ISSUE THREAD

**Issue by xclidongbo** [react-native-image-picker/react-native-image-picker#1594]
### Description

Explain the bug in as much detail as possible
`ImagePicker.showImagePicker`, when user tap camera cancel, `response.didCancel` execute,  notification center show "系统服务 检测到XXX删除了图片，已成功拦截"

### How to repeat issue and example

`ImagePicker.showImagePicker`, when user tap camera cancel, `response.didCancel` execute,  notification center show "系统服务 检测到XXX删除了图片，已成功拦截"

### Solution

How to clear up the notification message?

### Additional Information

- Image Picker version: [2.3.4]
- React Native version: [0.62]
- Platform: [Android]
- Development Operating System: [MacOS]
- Dev tools: [Android] navigation crash for Android

**Comment by ravirajn22** [comment]
Sorry we could not respond in time.
Version 2.x.x is not longer supported, please upgrade to 3.x.x
