### ISSUE TITLE
[🐛] 

### ISSUE THREAD

**Issue by jingyanXia** [react-native-image-picker/react-native-image-picker#1595]
Hello everyone, I encountered a problem when using react-native-image-picker.
I used <Modal /> to make a bottom selection. When I clicked to select the gallery or took a photo, I made the visible of <Modal/> false, but the gallery selection box disappeared. In the same way, the camera function is also fleeting.

**Comment by ravirajn22** [comment]
Is this issue only on iOS? then check this thread. https://github.com/react-native-image-picker/react-native-image-picker/issues/1456#issuecomment-742509611

I hope the issue is solved, if not reply here or create new issue with details I am happy to fix it.
