### ISSUE TITLE
Image size is getting bigger than real on iOS[🐛] 

### ISSUE THREAD

**Issue by Achilles718611** [react-native-image-picker/react-native-image-picker#1596]
Image size is getting bigger than actual image on iOS with the latest react-native-image-picker (3.x)

**Comment by matapo** [comment]
Same issue

**Comment by Achilles718611** [comment]
I checked other image pickers too.
It seems bug is related with react-native self.
When I use react-native-crop-image-picker if I don't compress image i.e if I use original image self, image size is getting bigger.

**Comment by chrisbobbe** [comment]
Hmm, someone posted on #1272 to suggest that this was a particular React Native bug: facebook/react-native#27099. Would that match the symptoms you're seeing?

**Comment by Achilles718611** [comment]
Yes, I think it's react-native bug.

**Comment by Johan-dutoit** [comment]
Going to close this issue for now. It's a good reference point for other facing the same issue.  If it is at some point determined to be a problem of the image picker, then we can open/create a new issue.

Thanks!
