### ISSUE TITLE
App crashes on android after selecting Image [🐛] 

### ISSUE THREAD

**Issue by ElChawich** [react-native-image-picker/react-native-image-picker#1599]
### Description

The app crashes only on android after selecting an image using "launchImageLibrary" without returning any response or any error.

### Additional Information

- Image Picker version: 3.1.4
- React Native version: 0.64.0-rc.1
- Platform: Android (real device)
- Development Operating System: MacOS

**Comment by ravirajn22** [comment]
Post your code and android error log to diagnose.
