### ISSUE TITLE
[🐛] Activity error

### ISSUE THREAD

**Issue by thiago-sants** [react-native-image-picker/react-native-image-picker#1600]
### Description

When I try to call launchCamera, I get an error. If I pass an option object as argument, it returns `Activity error` in response.errorMessage. If I don't pass an option object, it returns `Attempt to invoke interface method 'void.facebook.react.bridge.Callback.invoke(java.lang.Object[])' on a null object reference`. But launchMediaLibrary works as expected. 

### How to repeat issue and example

- calls launchCamera with or without options object

### Solution

No idea.

### Additional Information

- Image Picker version: 3.1.4
- React Native version: 0.61.5
- Platform: iOS and Android
- Development Operating System: MacOS

**Comment by ravirajn22** [comment]
Show your code, options and callback is compulsory in the API.

What is your android target SDK and in which version of android are u running the app?

**Comment by thiago-sants** [comment]
> What is your android target SDK and in which version of android are u running the app?

Target SDK is 29 and running on Android 10.

I tried other library and I'm getting this error as well.  So I think that isn't a problem with this library, but with something in my project. So I'm going to close this issue. Anyway, thanks for your attention.

**Comment by jakaria-acd** [comment]
It's happening for me too, it's not related to project i think. Because the same build/apk working fine in android 10, not working in android 11. tried 2 different android 11.  Both camera and gallery not working. Tried the latest version: 3.1.4

It throws error:
errorMessage: "Activity error"
errorCode: "others"

**Comment by JakariaAmin** [comment]
It's happening for me too, it's not related to project i think. Because the same build/apk working fine in android 10, not working in android 11. tried 2 different android 11. Both camera and gallery not working. Tried the latest version: 3.1.4

It throws error:
errorMessage: "Activity error"
errorCode: "others"

**Comment by ravirajn22** [comment]
@JakariaAmin 
Target SDK 30 not supported change to 29.
Read this thread https://github.com/react-native-image-picker/react-native-image-picker/issues/1587

**Comment by thiago-sants** [comment]
> It's happening for me too, it's not related to project i think. Because the same build/apk working fine in android 10, not working in android 11. tried 2 different android 11. Both camera and gallery not working. Tried the latest version: 3.1.4

It's happening even on Android 10 for me. But only with camera option. Gallery opens without any problem. I tried other libraries, but without success. Same error.

**Comment by darkworks** [comment]
> @JakariaAmin
> Target SDK 30 not supported change to 29.
> Read this thread #1587

i have target SDK 29 but am  getting same issue , min SDK is 21
am testing on device with Android 7.0

**Comment by calitb** [comment]
Getting the same error with this:
```
        buildToolsVersion = "29.0.2"
        minSdkVersion = 23
        compileSdkVersion = 29
        targetSdkVersion = 29
```

launchCamera(
      {
        mediaType: 'photo',
        maxHeight: 1024,
        maxWidth: 1024,
        quality: 0.5,
      },
      ()=>{}
    );

using version 3.2.1

**Comment by Jsbarcenas** [comment]
anyone has find a fix for this problem?

**Comment by calitb** [comment]
on my case this only presents when the android device didn't have a Camera app installed. still, this error message could be improved

**Comment by pmontury** [comment]
Got it working with
        buildToolsVersion = "31.0.0-rc3"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30

And a virtual device running with API level 29
But not working with a virtual device running with API level 30

**Comment by cody-wingert** [comment]
I had to downgrade the `compileSdkVersion` and `targetSdkVersion` from 30 to 29 and the errors magically stopped. I tested on a physical device - Google Pixel 2. Upgrading the `buildToolsVersion` to 31 did not work for me. Camera and Gallery are both working fine now.

_Before_

ext {
        buildToolsVersion = "30.0.3"
        minSdkVersion = 21
        compileSdkVersion = 30
        targetSdkVersion = 30
    }

_After_

ext {
        buildToolsVersion = "30.0.3"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
    }

**Comment by thiago-sants** [comment]
I think there's something to do with this [issue](https://github.com/react-native-image-picker/react-native-image-picker/issues/1393#issuecomment-713299590), but I'm not sure.
