### ISSUE TITLE
[🐛]  Unable to resolve module `./types` from `node_modules\react-native-image-picker\src\index.ts`:

### ISSUE THREAD

**Issue by Yandamuri** [react-native-image-picker/react-native-image-picker#1601]
### Description
I have done installation as per docs and implemented in my app. As soon as i ran the app got this error.
 `Unable to resolve module `./types` from `node_modules\react-native-image-picker\src\index.ts`:`

### How to repeat issue

just install the package as per docs and ran the app then you can encounter this error. Please be notified that error is coming in command prompt not in emulator

### Solution

I am not sure about it

### Additional Information

- Image Picker version: 2.3.3
- React Native version: "0.63.4"
- Platform: Android
- Development Operating System: Windows
- Dev tools: Android Studio version: 4.1.2

**Comment by Johan-dutoit** [comment]
Version 2.x.x is no longer supported, please update to 3.x.x.

**Comment by Yandamuri** [comment]
Thank you @Johan-dutoit . issue resolved
