### ISSUE TITLE
Cannot get path to photo[🌟] 

### ISSUE THREAD

**Issue by Anytram** [react-native-image-picker/react-native-image-picker#1607]
Hi, 
I need to get path to photo because I want to use lib react-photo-editor on this photo.
In version 1 of your lib was field named path and for android it worked well but ios doesn't returned this field. So I needed to change version to newer - 3 and now I don't have any path.
There is only uri:
for ios: "file:///Users/xxx/Library/Developer/CoreSimulator/Devices/7A8C2707-E343-4C0A-AF6E-5A4568B9F41C/data/Containers/Data/Application/217E9969-67DC-4553-AF33-6B4A42C6764C/tmp/EAF129AA-FE3E-4B69-8857-0798F7879F9B.jpg"
for android: 
content://com.xxxxx.imagepickerprovider/cacheDir/rn_image_picker_lib_temp_762823e4-4953-4703-bca5-d26821377653.jpg
and I can't do anything with it. :(
Moreover on Android when I pick image it starts to dowanload it...

**Comment by ravirajn22** [comment]
I hope ur using https://github.com/prscX/react-native-photo-editor, just send the URI directly to the library. Because the selected image is temporarily copied inside ur application and its URI is provided.

The URI provided is in standard format and all libraries should support it, else the problem is in their side.

**Comment by Anytram** [comment]
Thank you for quick response, it is indeed the library I'am using. 
I wonder why field named path from previos version worked, but uri doesn't :/ But you are right this is their problem.

**Comment by Anytram** [comment]
And one more question - when I downgraded version to 1
uri looks like that: "content://com.miui.gallery.open/raw/%2Fstorage%2Femulated%2F0%2FDCIM%2FCamera%2FIMG_20201122_112044.jpg"
and path: "/storage/emulated/0/DCIM/Camera/IMG_20201122_112044.jpg"
which is totally different than in version 3.

**Comment by ravirajn22** [comment]
Path field is no longer supported. Is sending URI working with the library?

**Comment by Anytram** [comment]
No, it doesn't work...

**Comment by ravirajn22** [comment]
Show your code where u call react-native-photo-editor? what error are you getting? need more info

**Comment by Anytram** [comment]
pickImage fuction calls onPick function in which photo-editor is called.

```
export function pickImage(onPick: (path: string) => void, permissionError: string): void {
    if (Platform.OS === 'ios') {
        launchImageLibrary(
            {
                mediaType: 'photo',
                includeBase64: false
            },
            (response: ImagePickerResponse) => {
                console.log('---------------');
                console.log(response);
                console.log('---------------');
                const { didCancel, errorMessage, uri } = response;
                if (didCancel) {
                    console.warn('User cancelled image picker');
                } else if (errorMessage) {
                    console.warn('ImagePicker Error: ', errorMessage);
                } else if (typeof uri === 'string' && uri.trim().length > 0) {
                    onPick(uri);
                }
            }
        );
}
```


```
export function editPhoto(path: string, onDone: () => void): void {
	if (Platform.OS === 'ios') {
		PhotoEditor.Edit({
			hiddenControls: ['save'],
			stickers: [
				'bleeding',
				'bruising',
				'circle',
				'damaged',
				'mold',
				'rect',
				'russet',
				'square'
			],
			path,
			onDone
		});
}

```

The funniest think is that no error is thrown.

**Comment by ravirajn22** [comment]
What is happening on iOS? try this lib https://github.com/ivpusic/react-native-image-crop-picker, check if it works.

**Comment by Anytram** [comment]
On ios there is no error, Editor just doesn't open. 
Give me a minute I will try this lib.

**Comment by nathancheung22** [comment]
I seem to be having this problem too. The uri in my response object seems to be some kind of temporary uri `content://com.iaia.imagepickerprovider/cacheDir/rn_image_picker_lib_temp_0dac2354-6765-4169-bf81-91e216d84b91.jpg` that my external library, tflite-react-native, can't seem to understand

**Comment by workpebojot** [comment]
By the way, what is the use of **uri**?

**Comment by workpebojot** [comment]
I think I get it; I don't get the device's actual local file path, but content:/ seems to work well with me so I don't need to get the device's actual local file path; instead, a copy of the picture or video is stored in the caching layer, which you can then use to get the file path using the uri.

**Comment by ravirajn22** [comment]
Latest version provides file uri to images.
I hope the issue is solved, if not reply here or create new issue with details I am happy to fix it.
