### ISSUE TITLE
Timestamp to be included in response, like in previous versions. [🌟] 

### ISSUE THREAD

**Issue by IceDev-xyz** [react-native-image-picker/react-native-image-picker#1610]
### Description

Not sure why it was dropped, but I think was a good thing to have it when loading from gallery.

**Comment by Johan-dutoit** [comment]
Just for clarity, are you referring to the timestamp of when the image/video was taken?

**Comment by IceDev-xyz** [comment]
Yes timestamp of when image/video was taken.
