### ISSUE TITLE
[🐛] Options parameter, optional or not?

### ISSUE THREAD

**Issue by majugurci** [react-native-image-picker/react-native-image-picker#1611]
Is the options parameter which is provided to the launchCamera or launchImageLibrary optional or not? In the documentation it says it is optional but in the code it says it is required.

Documentation:
![Doc image](https://i.imgur.com/lK4Ylqc.png)
![Code image](https://i.imgur.com/nH2Bp94.png)

**Comment by ravirajn22** [comment]
I will update the docs, options is required.
