### ISSUE TITLE
[🌟] Expose image compression method

### ISSUE THREAD

**Issue by majugurci** [react-native-image-picker/react-native-image-picker#1612]
Would it be possible to expose method which you are using for image compression (when quality option is provided)?
I have this app where user can upload all sort of documents. I'm using react-native-image-picker to allow him to capture or pick photo and react-native-document-picker to allow him to pick any kind of document. So the user can pick photos also through document-picker. Now if user picks a photo through document-pricker I would also like to compress it before upload. I can add another dependency just for this but is there a chance you could expose method of a image-picker so we can also manually use it for situations like these?

**Comment by ravirajn22** [comment]
What u mean by image compression? Already there is an option to provide image quality which will compress the image.

**Comment by ravirajn22** [comment]
Exposing it as a separate function is not possible right now.
