### ISSUE TITLE
[🐛] Fatal crash when picking video in mediaType=photo mode in Huawei Gallery

### ISSUE THREAD

**Issue by bracketsberlin** [react-native-image-picker/react-native-image-picker#1613]
### Description

Huawei's Gallery app (10.1.1.531) also shows videos when mediaType = 'photo'

### How to repeat issue and example
1. Launch image library in photo mode:

```
let photoOptions = {
      mediaType: 'photo',
    };

launchImageLibrary(photoOptions, (response) => {
      if (response.didCancel) {
        console.log('Image Picker: Picking/capturing photo cancelled');
      } else if (response.errorCode) {
        console.error('ImagePicker Error Code: ', response.errorCode, response.errorMessage);
      } else {
        // do something
      }
    });
```

2. Open Huawei's Gallery App, select a video (which is wrongly shown in photo mode here)
3. App crashes without any error message

### Solution
Handle error / prevent fatal app crashes.

**Comment by ravirajn22** [comment]
Library version? Does videos show while in 'photo' mode?

**Comment by ravirajn22** [comment]
@bracketsberlin have created a PR check if it fixes your issue. #1615

**Comment by bracketsberlin** [comment]
Great - thanks a lot!
