### ISSUE TITLE
Picking video takes time and freeze gallery  [🐛] 

### ISSUE THREAD

**Issue by Pcartau** [react-native-image-picker/react-native-image-picker#1619]
### Description

When I try to get video from gallery, image picker freeze by time proportional to the file size
(1min video is like 5-10 sec to unfreeze and get informations about it)
Is there something that I don't understand or that I'm doing wrong ?

### How to repeat issue and example

-Launch `launchImageLibrary ` method
-Pick video

`launchImageLibrary({
      mediaType: 'video',
      storageOptions: {
        skipBackup: true,
      },
    }, (res) => {...});`

### Solution

I have the impression that the lib generates a temporary file?
The longer the video, the longer it takes (tested with `includeBase64: false`)

The Graal would be to get the information from the video instantly.

### Additional Information

- Image Picker version: [^3.1.4]
- React Native version: [react-native-cli: 2.0.1 - react-native: 0.63.4]
- Platform: [Android]
- Development Operating System: [MacOS]
- Dev tools: [Xcode, Android] navigation crash for Android

**Comment by ravirajn22** [comment]
Image picker 3.x.x version does not have `storageOptions`.  So make sure you'r using the correct version, in v3.x.x only image files are copied to app specific temp folder, videos are not.

**Comment by Pcartau** [comment]
I also tried without `storageOptions `, doesn't change anything :(.

**Comment by ravirajn22** [comment]
I have no idea, create a new react-native project and try, check if the issue is on the device or any particular video file etc.

**Comment by Pcartau** [comment]
Yup I'll try.
Just to get sure before closing issue, is normal business of the library is to instantly get video information ?

**Comment by ravirajn22** [comment]
Yes

**Comment by Pcartau** [comment]
Thx !
