### ISSUE TITLE
Selfies are rotated in -90º and photos with back camera are rotated in 90º[🐛] 

### ISSUE THREAD

**Issue by Cnilton** [react-native-image-picker/react-native-image-picker#1623]
### Description

Just updated from version 2.3.4 and encountered this issue. When taking a selfie (vertically) the image becomes sideways (rotated in -90º or 270º), and when taking a photo with the back camera, the image becomes sideways (rotated in 90º).

What needs to be done to address this issue?

### Additional Information

- Image Picker version: [3.2.1]
- React Native version: [0.63.3]
- Platform: [Android]
- Development Operating System: [Windows]

**Comment by ravirajn22** [comment]
read https://github.com/react-native-image-picker/react-native-image-picker/issues/1493

comment if you have any issue

**Comment by Cnilton** [comment]
It is actually right, my bad. I tried displaying it before sending it to the backend and everything was ok.
