### ISSUE TITLE
[🐛] Property quality property not working with launchImageLibrary

### ISSUE THREAD

**Issue by tuneerclixlogix** [react-native-image-picker/react-native-image-picker#1624]
quality property not working with launchImageLibrary

I added quality in my options
const options = {
  quality: 0.2,
  storageOptions: {
    skipBackup: true,
    path: "images",
  },
};
then i made call to launchImageLibrary(options, async (response) => {})
but still i am getting the same image size on selecting the image from library , i want the quality of image to be reduced so the filesize is less

**Comment by ravirajn22** [comment]
I am unable to reproduce in latest version. What version are u using and provide more details, like the original image size and image size in the response.

**Comment by GolfredoPerezFernandez** [comment]
same here

**Comment by ChrisMarlier** [comment]
Same problem here. Tested on Android. If quality is the only params, their is no change on the image, which will be the same size. If I have other params like maxWidth, the quality can be changed.

**Comment by Johan-dutoit** [comment]
Going to close the issue.  No information on the platform, picker version, etc.
