### ISSUE TITLE
Bug report [🐛] 

### ISSUE THREAD

**Issue by MortezaHeydari97** [react-native-image-picker/react-native-image-picker#1629]
## Error Text

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not find androidx.core:core:1.3.1.
     Searched in the following locations:
       - file:/C:/Users/morte/.m2/repository/androidx/core/core/1.3.1/core-1.3.1.pom
       - file:/C:/projects/saimaan/Shukul/node_modules/react-native/android/androidx/core/core/1.3.1/core-1.3.1.pom
       - file:/C:/projects/saimaan/Shukul/node_modules/jsc-android/dist/androidx/core/core/1.3.1/core-1.3.1.pom
       - https://dl.google.com/dl/android/maven2/androidx/core/core/1.3.1/core-1.3.1.pom
       - https://jcenter.bintray.com/androidx/core/core/1.3.1/core-1.3.1.pom
       - https://www.jitpack.io/androidx/core/core/1.3.1/core-1.3.1.pom
     Required by:
         project :app > androidx.swiperefreshlayout:swiperefreshlayout:1.0.0
         project :app > com.facebook.flipper:flipper:0.54.0 > androidx.appcompat:appcompat:1.1.0 > androidx.drawerlayout:drawerlayout:1.0.0     
         project :app > project :react-native-screens > androidx.fragment:fragment:1.2.1 > androidx.viewpager:viewpager:1.0.0
         project :app > project :react-native-screens > androidx.fragment:fragment:1.2.1 > androidx.loader:loader:1.0.0
         project :app > project :react-native-screens > androidx.coordinatorlayout:coordinatorlayout:1.1.0 > androidx.customview:customview:1.0.0
   > Could not find androidx.core:core:1.3.1.
     Searched in the following locations:
       - file:/C:/Users/morte/.m2/repository/androidx/core/core/1.3.1/core-1.3.1.pom
       - file:/C:/projects/saimaan/Shukul/node_modules/react-native/android/androidx/core/core/1.3.1/core-1.3.1.pom
       - file:/C:/projects/saimaan/Shukul/node_modules/jsc-android/dist/androidx/core/core/1.3.1/core-1.3.1.pom
       - https://dl.google.com/dl/android/maven2/androidx/core/core/1.3.1/core-1.3.1.pom
       - https://jcenter.bintray.com/androidx/core/core/1.3.1/core-1.3.1.pom
       - https://www.jitpack.io/androidx/core/core/1.3.1/core-1.3.1.pom
     Required by:
         project :app > project :react-native-image-picker
   > Could not find androidx.exifinterface:exifinterface:1.3.1.
     Searched in the following locations:
       - file:/C:/Users/morte/.m2/repository/androidx/exifinterface/exifinterface/1.3.1/exifinterface-1.3.1.pom
       - file:/C:/projects/saimaan/Shukul/node_modules/react-native/android/androidx/exifinterface/exifinterface/1.3.1/exifinterface-1.3.1.pom  
       - file:/C:/projects/saimaan/Shukul/node_modules/jsc-android/dist/androidx/exifinterface/exifinterface/1.3.1/exifinterface-1.3.1.pom      
       - https://dl.google.com/dl/android/maven2/androidx/exifinterface/exifinterface/1.3.1/exifinterface-1.3.1.pom
       - https://jcenter.bintray.com/androidx/exifinterface/exifinterface/1.3.1/exifinterface-1.3.1.pom
       - https://www.jitpack.io/androidx/exifinterface/exifinterface/1.3.1/exifinterface-1.3.1.pom
     Required by:
         project :app > project :react-native-image-picker
   > Could not find androidx.core:core:1.3.1.
     Searched in the following locations:
       - file:/C:/Users/morte/.m2/repository/androidx/core/core/1.3.1/core-1.3.1.pom
       - file:/C:/projects/saimaan/Shukul/node_modules/react-native/android/androidx/core/core/1.3.1/core-1.3.1.pom
       - file:/C:/projects/saimaan/Shukul/node_modules/jsc-android/dist/androidx/core/core/1.3.1/core-1.3.1.pom
       - https://dl.google.com/dl/android/maven2/androidx/core/core/1.3.1/core-1.3.1.pom
       - https://jcenter.bintray.com/androidx/core/core/1.3.1/core-1.3.1.pom
       - https://www.jitpack.io/androidx/core/core/1.3.1/core-1.3.1.pom
     Required by:
         project :app > com.facebook.flipper:flipper:0.54.0 > androidx.appcompat:appcompat:1.1.0
         project :app > project :react-native-screens > androidx.fragment:fragment:1.2.1
         project :app > project :react-native-screens > androidx.coordinatorlayout:coordinatorlayout:1.1.0
         project :app > project :react-native-screens > com.google.android.material:material:1.1.0
         project :app > project :react-native-screens > androidx.fragment:fragment:1.2.1 > androidx.activity:activity:1.1.0
         project :app > project :react-native-screens > com.google.android.material:material:1.1.0 > androidx.vectordrawable:vectordrawable:1.1.0
         project :app > project :react-native-screens > com.google.android.material:material:1.1.0 > androidx.viewpager2:viewpager2:1.0.0       
         project :app > project :react-native-screens > com.google.android.material:material:1.1.0 > androidx.recyclerview:recyclerview:1.1.0   
   > Could not find androidx.core:core:1.3.1.
     Searched in the following locations:
       - file:/C:/Users/morte/.m2/repository/androidx/core/core/1.3.1/core-1.3.1.pom
       - file:/C:/projects/saimaan/Shukul/node_modules/react-native/android/androidx/core/core/1.3.1/core-1.3.1.pom
       - file:/C:/projects/saimaan/Shukul/node_modules/jsc-android/dist/androidx/core/core/1.3.1/core-1.3.1.pom
       - https://dl.google.com/dl/android/maven2/androidx/core/core/1.3.1/core-1.3.1.pom
       - https://jcenter.bintray.com/androidx/core/core/1.3.1/core-1.3.1.pom
       - https://www.jitpack.io/androidx/core/core/1.3.1/core-1.3.1.pom
     Required by:
         project :app > com.facebook.flipper:flipper:0.54.0 > androidx.appcompat:appcompat:1.1.0 > androidx.appcompat:appcompat-resources:1.1.0 
         project :app > project :react-native-reanimated > androidx.transition:transition:1.2.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. 
Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

How can I to fix this ?

**Comment by cardremi** [comment]
i have a same problem too

**Comment by MortezaHeydari97** [comment]
Please mention the contributors bro.
@marcshilling
@yfuks
@cardremi

**Comment by hassanhossini2** [comment]
i have a same problem too

**Comment by hassanhossini2** [comment]
My problem was solved
Activate your VPN!
