### ISSUE TITLE
[🌟] Way to store more than one image at one

### ISSUE THREAD

**Issue by diego-ensolvers** [react-native-image-picker/react-native-image-picker#1630]
### Description

Hi, i use this library to get two images (opening the picker for each image) and then upload this images to the cloud. As follows:
open the picker
pick an image
save the image uri in the state
open the picker again
pick an image
save the image uri in state
upload the two files in a multipart-file request

But i noticed that the library persist one image at once. so the request fails because cant read one of the two files

### Proposed Solution

Implement a way to store more than 1 file at once.

### Test Solution

Pick two images in separated sessions (open the picker for each image).
Check that the two image uris exists in the file system

**Comment by Johan-dutoit** [comment]
Not sure this will be implemented, but as a workaround, create your own copy of the image after a user selects it.

**Comment by diego-ensolvers** [comment]
@Johan-dutoit Thanks for your reply. Do you have an example that works? I tried with [RNFS](https://github.com/itinance/react-native-fs) but it gives me an error that the file cannot be found.

**Comment by sathiralamal** [comment]
This can be help [hear](https://github.com/react-native-image-picker/react-native-image-picker/issues/1632#issuecomment-816003102)

**Comment by diego-ensolvers** [comment]
Done!
