### ISSUE TITLE
[🐛] No variants found for 'react-native-image-picker'. Check build files to ensure at least one variant exists.

### ISSUE THREAD

**Issue by twaframework** [react-native-image-picker/react-native-image-picker#1635]
### Description

After upgrading to v3.2.1, I am unable to Sync Gradle Project or Build Android project.   When I sync, I get the error 'No variants found for 'react-native-image-picker'. Check build files to ensure at least one variant exists.'

When I try to build the project, it says com.imagepicker not found.

### How to repeat issue and example

Here is how my build.gradle looks like

`android {
    compileSdkVersion 30
    buildToolsVersion "30.0.3"
    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }

    defaultConfig {
        multiDexEnabled true
        minSdkVersion 24
        targetSdkVersion 30
        versionCode 18
        versionName "1.1.3"
        ...
    }
...`

### Solution

I have tried cleaning the project, re-installing all packages but nothing seems to work. 

### Additional Information

- Image Picker version: v3.2.1
- React Native version: 0.63.3
- Platform: Android
- Development Operating System: MacOS
- Dev tools: Android Studio Version: 4.1.2

**Comment by ravirajn22** [comment]
Target SDK 30 not yet supported

**Comment by ravirajn22** [comment]
I hope the issue is solved, if not reply here or create new issue with details I am happy to fix it. Thanks

**Comment by pmrzygweb** [comment]
@ravirajn22 I am also having same issue and even target SDK 29 doesn't work either. Do you have any idea why?

**Comment by MayoudP** [comment]
Same over here for SDK 29 :/

**Comment by mohan1361** [comment]
I am facing the same issue with the newer version of Installing react-native-image-picker **5.6.0** so I installed the previous version  5.4.2 which is stable and working for me.
