### ISSUE TITLE
[🐛] launchImageLibrary doesn't return the data file when it is called

### ISSUE THREAD

**Issue by ajen010** [react-native-image-picker/react-native-image-picker#1640]
### Description

When I call the launchImageLibrary I am successfully shown the images from my library and an empty array {} is returned to my function call.

When I click on an image I can see the details of the image in console.log no data is returned from my function. Later on the console log displays the image data.

### How to repeat issue and example
selectFile = () => {
    console.log("at the selectFile");
    const options = {
      title: 'Select Image',
      customButtons: [
        {
          name: 'customOptionKey',
          title: 'Choose file from Custom Option'
        },
      ],
      storageOptions: {
        skipBackup: true,
        path: 'images'
      }
    }

    launchImageLibrary(options, res => {
      console.log('Response = ', res);

      if (res.didCancel) {
        console.log('User cancelled image picker');
      } else if (res.error) {
        console.log('ImagePicker Error: ', res.error);
      } else if (res.customButton) {
        console.log('User tapped custom button: ', res.customButton);
        alert(res.customButton);
      } else {
        console.log("got to the else launchImageLibrary");
        //sendURI(res.uri);
        return res;
      }
    })
  }
- step to reproduce the issue
- ...

### Solution
When launchImageLibrary runs it should wait and return the image from the launchImageLibrary call.

### Additional Information

- Image Picker version: [FILL THIS OUT: ^3.2.1]
- React Native version: [FILL THIS OUT: 0.63.4]
- Platform: [iOS]
- Development Operating System: [FILL THIS OUT:  MacOS]
- Dev tools: [FILL THIS OUT: Xcode and atom]

**Comment by Johan-dutoit** [comment]
The callback shouldn't be called until an image is selected.  If it is in your instance, I recommend you create a reproducible example and share that for investigation.
