### ISSUE TITLE
[🐛] After capturing photo or selecting image from library not returning to the component it was called.

### ISSUE THREAD

**Issue by Imran-cse** [react-native-image-picker/react-native-image-picker#1641]
### Description

After launching the camera with `launchCamera()` function when then photo is taken and tick mark clicked, it does not take me to the component from where it was called rater than the App gets reload. Same thing happens when I use `launchImageLibrary()` function.

There is no log shown. Immediately the app gets reloaded 

### Solution

What needs to be done to address this issue?

### Additional Information

- Image Picker version: [^3.2.1]
- React Native version: [0.63.4]
- Platform: [Android]
- Development Operating System: [Linux]
- Dev tools: buildToolsVersion = "29.0.2"
                   minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29

**Comment by KubilayKerim** [comment]
Same here It works normal on many devices but some devices keep getting this

**Comment by ravirajn22** [comment]
duplicate #1502
