### ISSUE TITLE
[Question] JPG filesize on iOS

### ISSUE THREAD

**Issue by troZee** [react-native-image-picker/react-native-image-picker#1643]
### Description

Hello everyone 👋 
Thank you for providing a great library. I have a question about the image size on iOS. In the gallery, the photo has in my case 1.9 MB, but when it is loaded by native module, file size increase dramatically (in my case 4,5 MB). Does anyone know, why it happens ? on Android everything works fine. 

### SS

![158969286_1928474840634563_472442440711527943_n](https://user-images.githubusercontent.com/12766071/111297287-bd367a80-864d-11eb-8b42-86a658106e0d.png)

**Comment by troZee** [comment]
Image used to the tests
![image00001](https://user-images.githubusercontent.com/12766071/111297634-1ef6e480-864e-11eb-8b61-c0f9561357d1.jpg)

**Comment by ravirajn22** [comment]
I don't know the exact version you'r using but all the versions code should behave the same. The issue is we get the Image raw bitmap data and save it as jpg, png or gif based on its original file type. In your case its jpg which is a lossy compression format, so it takes compression quality which can be anything from 0 to 1. This lib provides default as 1, which can increase the size of the file. Try providing a value of 0.8 (Not sure but read some where iOS uses default 0.8 internally)

**Comment by troZee** [comment]
> This lib provides default as 1, which can increase the size of the file. Try providing a value of 0.8 (Not sure but read some where iOS uses default 0.8 internally)

Probably this is the answer on my question. I was not able to find any information in documentation about it.

**Comment by momolafrooo** [comment]
Hello @troZee did you fix the issue ? I got the same probleme. i think on ios it doesn't give the right filesize

**Comment by troZee** [comment]
@momolafrooo 

```
/**
 * We encountered an issue on iOS for JPG files. Our solution is to iterate over an array of potential
 * options (height / width / quality) and check the response file size is within our file size limit.
 * If it's too big, then we try again with the next set of options at a lower quality.
 * It may not be the 'max file size' but it will attempt to preserve some quality where possible.
 */
export async function imageToBlob(image: ImageType): Promise<Blob> {
  const { uri, width, height } = image;
  let resizedImage: Response = await ImageResizer.createResizedImage(
    uri,
    width,
    height,
    'JPEG',
    100
  );

  if (Platform.OS === 'ios' && resizedImage.size > MAX_FILE_SIZE) {
    const resized = await getResizedBlob(image, resizedImage.size);
    if (resized) {
      resizedImage = resized;
    }
  }

  return {
    //@ts-ignore
    name: resizedImage.name || image.filename || 'image.jpg',
    uri: resizedImage.uri.replace(
      'file://',
      Platform.OS === 'android' ? 'file://' : ''
    ),
    type: 'image/jpeg',
    size: resizedImage.size,
  };
}
```
