### ISSUE TITLE
[🐛] 

### ISSUE THREAD

**Issue by pippoBe** [react-native-image-picker/react-native-image-picker#1646]
### Description

launchCamera() works in debug, but fails only in the release, I have already added all permissions for the storage and the camera

### Example

```
launchCamera(options, (response) => {
                if (response.didCancel) {
                    console.log('User cancelled image picker');
                } else if (response.error) {
                    console.log('ImagePicker Error: ', response.error);
                } else if (response.customButton) {
                    console.log('User tapped custom button: ', response.customButton);
                    alert(response.customButton);
                } else {
                    const source = {uri: response.uri};
                    // console.log('response', JSON.stringify(response));
                    setExDiFileTitle(response.fileName);
                    setExDiFile(response);
                }
            });
```
executes the else code, ignoring the other if

### Additional Information

- Image Picker version: ["react-native-image-picker": "^3.3.2"]
- React Native version: ["react-native": "^0.63.3",]
- Platform: [Android]
- Development Operating System: [Linux]

**Comment by ravirajn22** [comment]
Please check 3.3.2 documentation, it does not have custonButton. I don't get what your exact issue is?

**Comment by pippoBe** [comment]
I sorted out, i ask the grant to the camera manually and now it is working, i did not see your documentation earlier, sorry.
