### ISSUE TITLE
[🌟] Where is the allow crop feature?

### ISSUE THREAD

**Issue by ngtrungt** [react-native-image-picker/react-native-image-picker#1649]
### Description

For the older version, we can still use this option. But for the latest version, we can't use it. 

### Proposed Solution

Please take it to come back.

**Comment by ravirajn22** [comment]
This library never had crop feature, I think your messaging in wrong library.

**Comment by lsdimagine** [comment]
There's `allowsEditing` prop for basic crop before. Not sure why it's removed. iOS `UIImagePickerController` still has `allowsEditing`.

**Comment by nica0012** [comment]
I'm on the same page as @lsdimagine
