### ISSUE TITLE
[🐛] Error when create thumbnail from the compressed uri

### ISSUE THREAD

**Issue by idoor88** [react-native-image-picker/react-native-image-picker#1653]
### Description

Hi all,
I need to get a thumbnail of a video:

`
    ImagePicker.launchImageLibrary(
          {
               mediaType: 'video', 
         },
            async (response) => {
                if (response.didCancel) {
                    console.log('User cancelled image picker');
                }else if (response.error) {
                    console.log('ImagePicker Error: ', response.error); 
                }else {
                     console.log(' response: ', response); 
              
                let uri = response.uri; 
              let vwidth = 0; let vheight = 0; let thumbnail = "blank";
              try{ 
                  let response2 = await createThumbnail({
                      url: uri,
                      timeStamp: 120000,
                    });
                  thumbnail = response2.path;
                  vheight = response2.height;
                  vwidth = response2.width;

                  if(__DEV__)  console.log("response2: ", response2); 
              }catch(err) {
                  if(__DEV__)  console.log("err: ", err); 
              } 

        }
      },
    )`
This code will generate error from the line createThumbnail:
Error: setDataSource failed:
The response looks like:
fileName: "933731831"
fileSize: 14625193
uri: "content://com.google.android.apps.photos.contentprovider/-1/2/content%3A%2F%2Fmedia%2Fexternal%2Fvideo%2Fmedia%2F149/ORIGINAL/NONE/video%2Fmp4/933731831"

Apparently, the uri will not be taken by createThumbnail from react-native-create-thumbnail.
Any idea how to solve this issue?
Thanks

**Comment by bwaghmare** [comment]
I am also facing the same issue

**Comment by priyankapc31** [comment]
Does somebody has solution

**Comment by Hermanyo** [comment]
Try it:

```
 const checkIfExists = await RNFS.exists(`${RNFS.CachesDirectoryPath}/${data.fileName}`);
    if (!checkIfExists) {
      await RNFS.copyFile(data.uri, `${RNFS.CachesDirectoryPath}/${data.fileName}`);
    }
    
    const thumb = await createThumbnail({
      url: Platform.OS === 'android' ? `file:///${RNFS.CachesDirectoryPath}/${data.fileName}` : data.uri,
      timeStamp: 500,
    });
```
