### ISSUE TITLE
[🐛] durationLimit ignored by launchImageLibrary

### ISSUE THREAD

**Issue by pedromarta** [react-native-image-picker/react-native-image-picker#1655]
### Description

`launchImageLibrary` ignores the `durationLimit` option.

### How to repeat issue and example

- Record video over 30 seconds with the devices' camera (can be done outside the app, it doesn't matter)
- Pass the following options object when calling `launchImageLibrary`
```
let options = {
  mediaType: 'video',
  videoQuality: 'high',
  durationLimit: 30,
};
```
- Check how the previously recorded video shows up, although the same has over 30 seconds in length.

### Solution

Is there a way to filter the videos listed in the gallery using duration limit? Could duration get returned in the callback, if not?

### Additional Information

- Image Picker version: 3.2.2
- React Native version: 0.63.4
- Platform: iOS

**Comment by ravirajn22** [comment]
durationLimit applies only to launchCamera not launchImageLibrary. Will update the wordings in docs.

> Is there a way to filter the videos listed in the gallery using duration limit? Could duration get returned in the callback, if not?

Not available right now, may be I will check if the feature can be added in future versions.

**Comment by ravirajn22** [comment]
Adding in latest version
