### ISSUE TITLE
deprecated version 2.4.0 is pulled from npm instead of 2.3.4[🐛] 

### ISSUE THREAD

**Issue by idomaz00** [react-native-image-picker/react-native-image-picker#1657]
### Description

I have an app that uses 2.x.x. version of this package with `package.json`: 
`"react-native-image-picker": "^2.3.3"`

But instead of downloading 2.3.4. package that is that latest with 2.x.x. major version (at least per documentation and release notes) it installs 2.4.0. and that version has breaking api changes.
I [see in npm repository](https://www.npmjs.com/package/react-native-image-picker/v/2.4.0) that it is deprecated but why does it still install?

### How to repeat issue and example

- in `package.json` write dependency as: `"react-native-image-picker": "^2.3.3"`

### Solution

- I have fixed this by removing ^ and writing `"react-native-image-picker": "2.3.4"` with a plan to upgrade to 3.x.x

If you cannot influence what is installed with yarn/npm then maybe you should add this as known issue in documentation for 2.x.x.

### Additional Information

- Image Picker version: [N/A]
- React Native version: [N/A]
- Platform: [N/A]
- Development Operating System: [MacOS]
- Dev tools: [N/A]

**Comment by ravirajn22** [comment]
Sorry for the issue, v2.4.0 was a wrong release due to some issue in CI, it should have been 3.x.x. Can we delete a published NPM version @Johan-dutoit ? I don't think adding it in docs will help, Ideally we should delete the version from NPM.

**Comment by Johan-dutoit** [comment]
Apologies for the late response.  2.4.0 has been removed from NPM.
