### ISSUE TITLE
[🐛] Cannot launchCamera

### ISSUE THREAD

**Issue by pksolutionsdev** [react-native-image-picker/react-native-image-picker#1662]
### Description

Call ImagePicker.launchCamera({ mediaType: 'photo'}, cb).

You'll see error:

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference         at com.imagepicker.Options.<init>(Options.java:29)

### How to repeat issue and example

Install 3.3.2
Call launchCamera without passing an option for `cameraType`.
Error appears and cannot use camera.

### Solution

Options.java, line 29:
`        if (options.getString("cameraType").equals("front")) {
            useFrontCamera = true;
        }
`
Needs to have a null check.

### Additional Information

- Image Picker version: 3.3.2
- React Native version: 0.63.4
- Platform: Android
- Development Operating System: Windows
- Dev tools: Android Studio 4.1

**Comment by ravirajn22** [comment]
Why is that I am unable to reproduce this issue, can some one enlighten. If you don't send `cameraType`, the default `back` is sent from JS. You can check the JS part of lib. 

Also not everyone has this issue only very few.

**Comment by applegb** [comment]
Huh, yea I see that now. will have to take a look later at why that doesn't seem to be getting added as the default. Cause when I add it on the react native side, it works fine.

**Comment by ravirajn22** [comment]
Only probable cause could be, you'r upgrading to latest version and the metro bundler uses the cache version of JS library. So just clear metro cache and restart packager. It should work.

If you can reproduce, just ping here I am happy to fix.
