### ISSUE TITLE
[🐛] Expo Issue?

### ISSUE THREAD

**Issue by EduardoGit-1** [react-native-image-picker/react-native-image-picker#1667]
### Description

Hi! I am using Expo CLI and I saw there is no need to link this module as it says nothing about it on the installation tutorial. Anyway. I have this error while I'm trying to use the launchImageLibrary API.  "TypeError: null is not an object (evaluating '_reactNative.NativeModules.ImagePickerManager.launchImageLibrary')"
This is my code: 
![image](https://user-images.githubusercontent.com/43757415/115070450-dea8b180-9eec-11eb-9e49-875d488ea306.png)

Is there somehting i'm doing wrong or this package is just not compatible with Expo?

### Additional Information

- Image Picker version: 3.3.2
- React Native version: 0.63
- Platform: Android

- Development Operating System: Windows
- Dev tools: Android Studio 4.1.3

**Comment by cainaleaouk** [comment]
I have the same error without Expo. It works fine in the simulator but won't work on the device

**Comment by Johan-dutoit** [comment]
Expo has its own image picker, don't use this package for expo.

**Comment by Johan-dutoit** [comment]
> I have the same error without Expo. It works fine in the simulator but won't work on the device

You need to rebuild your application (and ideally restart your packager) after installing native packages.
