### ISSUE TITLE
[🌟] fileName property on Response object for iOS videos

### ISSUE THREAD

**Issue by yerevin** [react-native-image-picker/react-native-image-picker#1670]
### Description

fileName property is available only for Android photos/videos and photos in iOS, on iOS video fileName is undefined, so it would be cool to add it also for iOS videos.

### Proposed Solution

Return fileName property with proper value on iOS video response object from onVideoObtained method
https://github.com/react-native-image-picker/react-native-image-picker/blob/main/ios/ImagePickerManager.m#L151
` self.response[@"fileName"] = fileName;`

### Test Solution

Check if fileName property returned from launchCamera and launchImageLibrary (type: 'video') on iOS device has value

**Comment by ravirajn22** [comment]
Its a bug, I will check and fix.

**Comment by plgrazon** [comment]
Having this bug too, made a temporary solution by finding the last index of the forward-slash and creating a substring from there. Will there be a fix for this soon?

**Comment by chrisbobbe** [comment]
I've just sent #1880.
