### ISSUE TITLE
[🐛] Getting TypeError : null is not an object (evaluating '_reactNative.NativeModules.ImagePickerManager.launchImageLibrary')

### ISSUE THREAD

**Issue by desertfox123** [react-native-image-picker/react-native-image-picker#1675]
### Description

I tried to use this library and using the latest version (3.3.3), but when launching the library always failed and get this message in log : 
"null is not an object (evaluating '_reactNative.NativeModules.ImagePickerManager.launchImageLibrary')"

I already import the lib as shown in the docs and #1531 but still getting that error

`import {launchImageLibrary} from 'react-native-image-picker';`

and call the function like this :
`launchImageLibrary({mediaType:'photo',cameraType:'front'},(res)=>{
                console.log('my result is',res)
            })`

### How to repeat issue and example

- step to reproduce the issue
- ...

### Solution

What needs to be done to address this issue?

### Additional Information

- Image Picker version: 3.3.3
- React Native version: 0.63.3
- Platform: Android
- Development Operating System: Windows
- Dev tools: [FILL THIS OUT: Xcode or Android Studio version, iOS or Android SDK version, if applicable] navigation crash for Android

**Comment by octaviopareja** [comment]
I have the same problem! Exactly the same!

**Comment by josesanchis16** [comment]
downgrading module to version 3.3.2 is working for me.
Just `npm install react-native-image-picker@3.3.2` and restart node server

**Comment by desertfox123** [comment]
> downgrading module to version 3.3.2 is working for me.
> Just `npm install react-native-image-picker@3.3.2` and restart node server

I tried to downgrade it but same issue still happening

**Comment by Johan-dutoit** [comment]
After installing, you'll need to rebuild your application.

**Comment by NoahVandy** [comment]
I am still having the same problem after installing the later version and restarting the node server. Can this be reopened?

**Comment by Niout** [comment]
I also have this problem after downgrading module and restarting the node server.

**Comment by taymeric** [comment]
Same issue. I tried downgrading to 3.3.2 but then it won't even build (some minSdk error).

**Comment by Johan-dutoit** [comment]
Restarting the node server is only half the solution.  You need to rebuild your application, as you would after installing any native module.
