### ISSUE TITLE
[🐛] wrong behaviour in dark mode on android

### ISSUE THREAD

**Issue by whitestranger7** [react-native-image-picker/react-native-image-picker#1677]
### Description

When launch image picker on Android in native dark mode, buttons became not visible for user and only highlights when user click on it.

### How to repeat issue and example

- create bare rn project with [dark mode support](https://www.npmjs.com/package/react-native-dark-mode)
- configure basic image picker config and launch it
- buttons will be not visible on white background (cuz it obviously white too )

https://user-images.githubusercontent.com/36364993/115892315-b4f90880-a45f-11eb-83d4-65950d6763c6.mov

### Solution

Dark mode on android support. Or create props for buttons & bg styling

### Additional Information

- Image Picker version: 2.3.3
- React Native version: ^0.63.2
- Platform: Android
- Development Operating System: MacOS
- Dev tools: Android Studio 4.1.1

**Comment by ravirajn22** [comment]
Sorry v2.x.x no longer supported.

**Comment by 2b-dev** [comment]
PS. I'm not good in English

- In node_modules > react-native-image-picker > android > src > main > res > layout > list_item.xml
- In line : android:textColor="change color this"

I do this work :)
