### ISSUE TITLE
[🐛] No apps can perform this action on some android devices

### ISSUE THREAD

**Issue by NitinTayal007** [react-native-image-picker/react-native-image-picker#1678]
### Description

I am using the library react-native-image-picker for image uploading through phone storage.

Below is my device
Device info:
Nokia 6.1 plus
android one. Version 10

Explain the bug in as much detail as possible

I am getting the message "no apps can perform this action" as soon as i reached the screen where i implemented this.

### How to repeat issue and example

- step to reproduce the issue
- Just run it on below device
- 
Device info:
Nokia 6.1 plus
android one. Version 10

### Solution

What needs to be done to address this issue?

### Additional Information

- Image Picker version: [3.3.2]
- React Native version: [0.64.0-rc.2]
- Platform: [Android one. Version 10]
- Development Operating System: [MacOS]
- Dev tools: [Not applicable]
- 
![Nokia](https://user-images.githubusercontent.com/36164809/115987757-ff02fb00-a5d3-11eb-9614-009ed065542d.png)

**Comment by ravirajn22** [comment]
If you ur using launchImageLibrary make sure the phone has installed gallery or photos app.

**Comment by NitinTayal007** [comment]
> If you ur using launchImageLibrary make sure the phone has installed gallery or photos app.

if a device do not have the gallery or photos app, then what options we have using this library? How we can upload from that device?

**Comment by ravirajn22** [comment]
All devices will come with some default gallery or photos app, android one has it.

**Comment by NitinTayal007** [comment]
Hi guys, this issue has been resolved. It was due to we were installing our app in device's work profile which were creating issues for us. Thanks for the help!!!

**Comment by StrPython** [comment]
Please provide your solution, what actions do i need to do.

**Comment by john79nl** [comment]
i have the same issue, how did you solve? is it from android side, or can be solved via code?

**Comment by NitinTayal007** [comment]
Did nothing, it was just due to we were having two profiles in our device one is personal and other one is work profile. so we were installing the app on work profile where don't have any photos/gallery app. Please check if this is the case with you as well.
