### ISSUE TITLE
launchImageLibrary issue for pickup file in Android

### ISSUE THREAD

**Issue by dhananjay23** [react-native-image-picker/react-native-image-picker#1679]
`react-native-image-picker` facing issue in `launchImageLibrary` for uploading an image to server throw error `Network request failed `in iOS it's working fine it happens in Android

- **Tried below all solutions but not working**
     1. uesCleartextTraffic="true" to the AndroidManifest.xml file found inside the dir android/app/src/main/AndroidManifest.xml
     2. Commented this line // initializeFlipper(this, getReactNativeHost().getReactInstanceManager());  
         in this file /android/app/src/main/java/com/{your_project}/MainApplication.java
     3. Commented this line // builder.addNetworkInterceptor(new FlipperOkhttpInterceptor(networkFlipperPlugin));
         in his file android/app/src/debug/java/com/{your_project}/ReactNativeFlipper.java
     4.  Updating FLIPPER version to `FLIPPER_VERSION=0.82.0`
     5. React native version `"react-native": "0.63.3"`
         
- **launchImageLibrary method options**

```
        let options = {
            title: 'Update Profile'
            allowsEditing: false,
            quality: 1,
            noData: true,
            mediaType: "photo",
            saveToPhotos:true,
            storageOptions: {
                skipBackup: true,
                cameraRoll: false
            },
        };

  launchImageLibrary(options, (response) => {
       const mediaPath = Platform.OS == "android" ? { uri: response.uri } : response.uri;
  
                  if (response.didCancel) {
                      console.log('User cancelled photo picker');
                  }
                  else if (response.error) {
                      console.log('ImagePicker Error: ', response.error);
                  }
                  else {
                       setUserProfile(mediaPath)
                  }
              });
```
- **API call Method**
  ```
   let formDataRequest = new FormData()
      formDataRequest.append("image",  { uri: response.uri, name: 'fileName;, type: 'image/jpg'})
   
      Api.updateProfileMedia(formDataRequest)
            .then(jsonResponse => {
       if (jsonResponse.status == true || jsonResponse.status == "true") {

      }else{
        }
      }) .catch(error => {
        console.log("Error",error);
      })
```

**Comment by harshshaw** [comment]
**I have similar problem with launchImageLibrary 
Error:-**
```TypeError: null is not an object (evaluating '_reactNative.NativeModules.ImagePickerManager.launchImageLibrary')
```
**code**
```
 function selectImage() {
        let options = {
            title: 'You can choose one image',
            maxWidth: 256,
            maxHeight: 256,
            storageOptions: {
                skipBackup: true
            }
        };

        ImagePicker.launchImageLibrary(options, response => {
            console.log({ response });

            if (response.didCancel) {
                console.log('User cancelled photo picker');
                Alert.alert('You did not select any image');
            } else if (response.error) {
                console.log('ImagePicker Error: ', response.error);
            } else if (response.customButton) {
                console.log('User tapped custom button: ', response.customButton);
            } else {
                let source = { uri: response.uri };
                console.log({ source });
            }
        });
    }
```

**Comment by frenberg** [comment]
@harshshaw what does your import statement look like? when migrating from v2 to v3 I hade to change from `import * as ImagePicker from 'react-native-image-picker';` to `import { launchImageLibrary } from 'react-native-image-picker';` And then you use it without the `ImagePicker.`-part

**Comment by frenberg** [comment]
@dhananjay23 maybe a long shot, but you don't happen to have "network inspection" active in react-native-debugger? Then uploads usually fails for me.

**Comment by Johan-dutoit** [comment]
Uploading of images is outside of scope for this library.
All we aim to do is get an image to your code base (via either gallery or camera), after that, it's in your hands what happens.

**Comment by dhananjay23** [comment]
@Johan-dutoit Yes you are right but the concern is which result provides by the library throws network request exceptions
