### ISSUE TITLE
[🐛] Cannot read property 'launchImageLibrary' of undefined react-native-image-picker

### ISSUE THREAD

**Issue by larearruda** [react-native-image-picker/react-native-image-picker#1680]
### Description

Not able to properly use plugin because is throwing error undefined when calling `launchCamera` or `launchImageLibrary`

### How to repeat issue and example
- Added plugin thru `yarn add react-native-image-picker`
- Perfomed `pod install` @ `ios` directory
- Add configs to Info.plist as described in plugin's docs.
- Code written as below
```

import React from 'react';
import {
    StyleSheet,
    Image,
    TouchableOpacity,
    Alert
} from 'react-native';
import { launchImageLibrary, launchCamera }  from 'react-native-image-picker';


const ImageUpload: React.FC<any> = ({}) => {
    const [response, setResponse] = React.useState(null);

    function showMessage() {
        Alert.alert("Alert", "Choose an option", [
            {
                text: 'Back',
                onPress: () => {},
            },
            {
                text: 'Camera',
                onPress: () => openCamera(),
            },
            {
                text: 'Library',
                onPress: () => openLibrary()
            },
        ]);
    }

    const openLibrary = () => {
        launchImageLibrary(
            {
              mediaType: 'photo',
              includeBase64: false,
              maxHeight: 200,
              maxWidth: 200,
            },
            (response) => {
                console.log(response);
            //   setResponse(response);
            },
          )
    }

    const openCamera = () => {
        launchCamera(
            {
              mediaType: 'photo',
              includeBase64: false,
              maxHeight: 200,
              maxWidth: 200,
            },
            (response) => {
                console.log(response);
            //   setResponse(response);
            },
          )
    }

    return(
        <>
            <TouchableOpacity onPress={()=>showMessage()}>
                <Image source={require('./picture.png')} style={{ width: 70, height: 70 }}/>
            </TouchableOpacity>
        </>
     );
};

const style = StyleSheet.create({
    ImageIcon: {
        justifyContent: "center",
        alignItems: "center",
    }
});

export default ImageUpload;
```

### Solution

Clarification on steps to properly install plugin.

### Additional Information

- Image Picker version: `"react-native-image-picker": "^3.3.4"`
- React Native version: `"react-native": "0.63.2"`
- Platform: iOS
- Development Operating System: Mac OS Catalina
- Dev tools: [Xcode 12.1]

**Comment by annajun1224** [comment]
Same issue here. I'm using typescript

**Comment by Johan-dutoit** [comment]
As with all native modules, after an install, you'll have to rebuild your project (sometimes even restart the packager).

i.e. `react-native run-ios` or `react-native run-android`

Alternatively open your project in xcode/android studio and run it from therre.

**Comment by Arkan4ik** [comment]
I dont know why, but on some project, react-native-image-picker does not want to link and need to link it manually. 

If you get this error, also try to check if this package is linking in xcode:
<img src="https://user-images.githubusercontent.com/23438777/124438337-b9577100-dd80-11eb-861c-e4abf4622a43.png" width="300" /> 

If no - link it manually. I add code in Podfile even though I have 0.60.4 react native version on this project.

![image](https://user-images.githubusercontent.com/23438777/124438536-fa4f8580-dd80-11eb-9813-f7d7138b7a6f.png)

This answer helped me https://github.com/react-native-image-picker/react-native-image-picker/issues/1627#issuecomment-790801724

**Comment by mcxu** [comment]
I'm running into this error. What is the fix for this for android?

**Comment by timurcatakli** [comment]
I fixed it by changing the import to `import * as ImagePicker from "expo-image-picker";`

**Comment by gurbela** [comment]
any news?
