### ISSUE TITLE
[🐛] - Setup issue Android (Linking ?) - com.imagepicker does not exist

### ISSUE THREAD

**Issue by MayoudP** [react-native-image-picker/react-native-image-picker#1688]
### Description

I wanted to upgrade from v 2.X.X to 3.X.X... But whatever version I'm upgrading to, I'm getting this error when running on Android : 
`/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:130: error: cannot find symbol`
`PackageList.java error: package com.imagepicker does not exist
import com.imagepicker.ImagePickerPackage`
`error: cannot find symbol
      new ImagePickerPackage()`

I don't really understand since I'm using react native > 0.60 and linking should be automatic on Android. 
`rm -rf node modules && yarn install `
`./gradlew clean`
`restart packager`

None of these above fixed this problem...
Thx for the help !

### How to repeat issue and example

- yarn add react-native-image-picker
- running android

### Solution

setup issue 

### Additional Information

- Image Picker version: 3.5.0 but all of them after when testing
- React Native version: 0.63.3
- Platform:  Android
- Development Operating System: MacOS

**Comment by abdullahizzuddiin** [comment]
HI, have you find the solution?

**Comment by GuoguoDad** [comment]
HI, have you find the solution?

**Comment by GuoguoDad** [comment]
anybody find the solution ?

**Comment by GuoguoDad** [comment]
I soluted by manual link:

1、settings.gradle
```
include ':react-native-image-picker'
project(':react-native-image-picker').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-image-picker/android')
```


2、app/build.gradle

`implementation project(':react-native-image-picker')`

3、MainApplication

 ```
protected List<ReactPackage> getPackages() {
  @SuppressWarnings("UnnecessaryLocalVariable")
  List<ReactPackage> packages = new PackageList(this).getPackages();
 
  packages.add(new ImagePickerPackage());
  return packages;
}
```

**Comment by cj-hansom** [comment]
hi, 
i am facing the same issue for more than a week now. 
i tried the manual linking but still no changes.
i am using react-native v0.68.2
and imagePicker v5.6
i keep geting this error message 
// react-native-image-picker
import undefined.ImagePickerPackage;
please help. thanks in advance

**Comment by cj-hansom** [comment]
Not yet @charlyBerthet

**Comment by charlyBerthet** [comment]
@cj-hansom I have figured out how to fix it, here the PR : https://github.com/react-native-image-picker/react-native-image-picker/pull/2193
