### ISSUE TITLE
[🐛How to use setBadge and getBadge with new firebase API ('@react-native-firebase/messaging' && '@react-native-firebase/app')

### ISSUE THREAD

**Issue by ravi123saxena** [react-native-image-picker/react-native-image-picker#1692]
Hi ,

I am stuck on updating badge in new firebase API . Please Provide the code to set and get badge.

 "@react-native-firebase/app": "^11.4.1",
 "@react-native-firebase/messaging": "^11.4.1",

**Comment by ravirajn22** [comment]
wrong repo
