### ISSUE TITLE
[🌟] Multiple image selection

### ISSUE THREAD

**Issue by rpander93** [react-native-image-picker/react-native-image-picker#1695]
### Description

Now that #1654 is merged I'd like to add support for multiple image picking as part of a project I'm on.

Previous requests were rejected because UIImagePickerController doesnt support this, but the PHPickerViewController does. Android supports it natively too afaik. So it seems to me that this can be added now.

### Proposed Solution

I'm creating this issue because I wanted to get some input on how the API should look like. Specifically the response object only supports 1 image. Any thoughts on how this should be done?

**Comment by rpander93** [comment]
Started working on this today. For now I settled on adding an `assets` array in the response that holds a list of objects containing all image/video-related values from the current response.

**Comment by Johan-dutoit** [comment]
Hi @rpander93, great stuff.

I have a couple of questions, which may help you with the design of the API.
- Would it be a flag to enable multi select?
- Would you be able to limit the number of items selected?
- How would image/video (one type) work?

I'll add more questions here when I think about them!

**Comment by rpander93** [comment]
Hi, thanks for getting back to me!

* added a bool `allowsMultiple` for the options. 
* no. this is not available on Android. taking it as the lowest common denominator, the only cross-platform option we can give is single/ multiple
* i guess you're referring to the mixed media type PR? havent looked into it fully, but i imagine that you'll be able to select multiple videos/ photo's in one go

I finished the Android implementation today and will look at iOS soon (but objective-c is not my strong suit). Here's what I made of the JS api now:

```typescript
export interface Asset {
  base64?: string;
  uri?: string;
  width?: number;
  height?: number;
  fileSize?: number;
  type?: string; //TODO
  fileName?: string;
  duration?: number;
}

export interface ImagePickerResponse {
  didCancel?: boolean;
  errorCode?: ErrorCode;
  errorMessage?: string;
  assets: Asset[];
}
```

**Comment by Johan-dutoit** [comment]
Lowest common denominator makes sense, good shout!

The above response type makes sense.  Having a unified response type between selecting one or multiple is good in my eyes to.  This will be marked as a breaking change.

**Comment by thuydao** [comment]
> Hi, thanks for getting back to me!
> 
> * added a bool `allowsMultiple` for the options.
> * no. this is not available on Android. taking it as the lowest common denominator, the only cross-platform option we can give is single/ multiple
> * i guess you're referring to the mixed media type PR? havent looked into it fully, but i imagine that you'll be able to select multiple videos/ photo's in one go
> 
> I finished the Android implementation today and will look at iOS soon (but objective-c is not my strong suit). Here's what I made of the JS api now:
> 
> ```ts
> export interface Asset {
>   base64?: string;
>   uri?: string;
>   width?: number;
>   height?: number;
>   fileSize?: number;
>   type?: string; //TODO
>   fileName?: string;
>   duration?: number;
> }
> 
> export interface ImagePickerResponse {
>   didCancel?: boolean;
>   errorCode?: ErrorCode;
>   errorMessage?: string;
>   assets: Asset[];
> }
> ```

How do i get it?

**Comment by KubilayKerim** [comment]
When it's going to be released ?

**Comment by rpander93** [comment]
@KubilayKerim you can help by testing #1706 to see if it works for you

**Comment by hlaporthein** [comment]
Waiting for release :) to use in my current project.
