### ISSUE TITLE
Cannot find protocol declaration for 'PHPickerViewControllerDelegate' [🐛] 

### ISSUE THREAD

**Issue by ruanblima** [react-native-image-picker/react-native-image-picker#1698]
### Description

I am trying to run an application that has ImagePicker, but when trying to run the application, the application does not compile and give an error in ImagePicker. The error is:

Cannot find protocol declaration for 'PHPickerViewControllerDelegate' 

Can anybody help me ?

### Additional Information

- Image Picker version: 3.6.0;
- React Native version: 0.61.2;
- Platform: iOS;
- Development Operating System: MacOS;
- Dev tools: xCode 11;

**Comment by maksimuchhh** [comment]
The same issue!

**Comment by subinsuresh** [comment]
@ruanblima getting the same issue.. Any updates?

**Comment by ravirajn22** [comment]
Please update to xcode 12, phpicker requires it. If you can't for now, then you have to stick with 3.5.0
