### ISSUE TITLE
[🐛] NullPointerException: android.net.Uri.getLastPathSegment(), from getResponseMap(Utils.java:339)

### ISSUE THREAD

**Issue by thanakij** [react-native-image-picker/react-native-image-picker#1699]
### Description

Crashlytics has reported an issue related to NullPointerException on **Utils.java (line 339)**

`String fileName = uri.getLastPathSegment();`

```
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=13002, result=-1, data=Intent { dat=content://com.sec.android.gallery3d.provider/union/image/item/15652 flg=0x1 (has extras) }} to activity {com.x/com.x.MainActivity}:
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getLastPathSegment()' on a null object reference
```

### How to repeat issue and example

I didn't find this error myself. Testing on my local Android devices always work fine but some portion of our users found errors according to Crashlytics report.

### Solution

Crashlytics revealed that the crash is from devices running **Android 8.1.0**. I have gone through the code and am convinced that there is an exception somewhere in `resizeImage()` as this method has a big try-catch wrapped around it. So it would return null and cause the crash in the next following line in `getResponseMap()`.

### Additional Information

- Image Picker version: 3.5.0
- React Native version: 0.62.2
- Platform: Android
- Development Operating System: MacOS
- Dev tools: N/A

**Comment by SumantaBee** [comment]
Having same issue
`{"errorCode": "others", "errorMessage": "Attempt to invoke virtual method 'java.lang.String android.net.Uri.getLastPathSegment()' on a null object reference"}
`
