### ISSUE TITLE
[🐛] Bug while building react-native-image-picker

### ISSUE THREAD

**Issue by caifu92** [react-native-image-picker/react-native-image-picker#1703]
Currently, I installed this package in my existing project to implement 'take profile photo' feature.
After I installed, I try to build the project and simulate on iOS simulator but failed during build.

It shows 10 issues in react-native-image-picker.
![image](https://user-images.githubusercontent.com/66729340/118178412-324ae400-b434-11eb-9ef0-4a341657dde4.png)

### How to repeat issue and example

- step to reproduce the issue
- react-native init example --version 0.63.4
- npm install react-native-image-picker
- cd ios & pod install
- build app

### Additional Information

- Image Picker version: 3.6.0
- React Native version: 0.63.4
- Platform: iOS
- Development Operating System: MacOS
- Dev tools: Xcode 11.6

**Comment by Johan-dutoit** [comment]
For curiosity's sake, what's your deployment target set to?

**Comment by caifu92** [comment]
> For curiosity's sake, what's your deployment target set to?

Deployment target is 'iOS11.0 iPhone'

**Comment by caifu92** [comment]
Please give me a solution

**Comment by caifu92** [comment]
I can't update to xcode12 as I'm working in Catalina on VM.
I've tried expo-image-picker instead of this package and achieve what I want.
