### ISSUE TITLE
[🐛] Add back allowsEditing like v2?

### ISSUE THREAD

**Issue by lsdimagine** [react-native-image-picker/react-native-image-picker#1718]
### Description

In v3 we can use allowsEditing prop in `launchImageLibrary` and it will return the image data directly. Maybe adding it back so we can edit image before actually posting it.

### How to repeat issue and example

Try use `launchImageLibrary` and `allowsEditing` is not supported.

### Solution

Add back `allowsEditing`

### Additional Information

- Image Picker version: 3.7.0
- React Native version: 64.0
- Platform: iOS
- Development Operating System: MacOS
- Dev tools: XCode

**Comment by ravirajn22** [comment]
Unfortunately latest PHPicker API provided by iOS does not support editing, so its not possible to add.

**Comment by nica0012** [comment]
This really sucks for this package unfortunately :(
