### ISSUE TITLE
[🐛] When pick video from gallery, the URI looks like: 'content://' instead of 'file://' (ANDROID)

### ISSUE THREAD

**Issue by Deodes** [react-native-image-picker/react-native-image-picker#1724]
### Description

When i try to pick video from gallery, i get uri: 'content://', but when i'm picking photo or taking it directly from camera(both photo and video), i get uri: 'file://' (in general, as I need). I would be grateful for any information!

### How to repeat issue and example

- select video from gallery
- in response get uri: 'content://xxx'

### Solution

Just need explanation how to get valid file path

### Additional Information

- Image Picker version: [3.8.0]
- React Native version: [0.63.3]
- Platform: [Android]
- Development Operating System: [MacOS]

**Comment by ravirajn22** [comment]
Yes, this is how its works. You can read more on this in the docs.

**Comment by Shik1997** [comment]
@ravirajn22 hey man,i have some problem that i can't get suffix in Response uri   when  i select video with android , how do i get it ?
