### ISSUE TITLE
[🐛] Use of undeclared identifier `PHPickerFilter`AND Property 'filter' cannot be found in class object `PHPickerConfiguration`.. AND More...

### ISSUE THREAD

**Issue by farhankassam2** [react-native-image-picker/react-native-image-picker#1730]
### Description

The bug occurred to me recently when I was trying to compile my React Native TS application on an iOS Simulator. I am using the following version of `react-native-image-picker`: `^3.2.1`.

Below is a screenshot of the compile time error when I tried compiling my RN App on the Xcode workspace (after running `pod install`):
<img width="1504" alt="Screen Shot 2021-05-30 at 10 08 14 PM" src="https://user-images.githubusercontent.com/22672953/120134921-c0dd9600-c194-11eb-8d99-f53ab8a575c1.png">

### How to repeat issue and example

- `npm install --save react-native-image-picker`
- Follow instructions on adding the package appropriately onto an RN app that runs RN >=0.60, as in this link: https://www.npmjs.com/package/react-native-image-picker#options
- `cd ios && rm -rf Pods Podfile.lock <project-name>.xcworkspace`: removes files re-created when installing new pods
- run `pod cache clean --all`: removes cached pods associated to the project
- run `pod install && cd ..`: installs package-associate pods
- run `. ~/.nvm/nvm.sh` and then `react-native bundle --entry-file='index.js' --bundle-output='./ios/main.jsbundle' --dev=false --platform='ios'`: rebuilds the project's `main.jsbundle` file.
- start the app by doing: `react-native-start` (starts the RN bundle) and then `react-native run-ios --simulator "iPhone X"` (starts iPhoneX simulator and builds the app onto it).
- Or instead of the above, if. you want to see the above build time error only (in the image above), open `<project_name>.xcworkspace`, go to `Product` > `Clean Build Folder` and then press on the triangle to run the <project_name> target on an `iPhone X` simulator.

### Solution

NO IDEA

I have tried running the following commands in sequence:

```
# recursively delete packages and runtime lockfile and previous project build
echo "Recursively deleting packages, lockfile and previous project build..."
rm -rf build node_modules package-lock.json
# install and update all packages defined in package.json
echo "clearing npm cache"
npm cache clear --force
echo "Installing all packages defined in package.json..."
npm install
#cd into iOS directory of the project
cd ios
# delete the previous build's compiled pods that may be causing trouble when trying to build in the iOS simulator.
echo "deleting previous build's iOS xcworkspace and pods and Podfile.lock..."
rm -rf <project_name>.xcworkspace Podfile.lock Pods
# update the pods based on new build with updated packages
echo "re-installing iOS pods..."
pod cache clean --all
pod install
# move back root project directory
cd ..
# re-creating main.jsbundle within /ios directory
#echo "re-creating main.jsbundle within /ios directory..."
. ~/.nvm/nvm.sh
npm run build:ios
```

And then running the app. I have tried using also the related package: `react-native-community/react-native-image-picker`.

### Additional Information

- Image Picker version: `^3.2.1`
- React Native version: `^0.63.3`
- Platform: `iOS`
- Development Operating System: `macOS Catalina 10.15.5`
- Dev tools: `Xcode 11.4` (both workspace and xcodeproject), `WebStorm`, `UNIX terminal`

**Comment by ravirajn22** [comment]
Use fixed version `3.2.1` instead of `^3.2.1` or upgrade to xcode 12 to support phpicker.
