### ISSUE TITLE
[🐛] errorMessage: 'Attempt to invoke virtual method \'boolean java.lang.String.contains(java.lang.CharSequence)\' on a null object reference on launchImageLibrary

### ISSUE THREAD

**Issue by priyankagaikwad** [react-native-image-picker/react-native-image-picker#1734]
### Description

on launchImageLibrary after selecting video getting error
{ errorMessage: 'Attempt to invoke virtual method \'boolean java.lang.String.contains(java.lang.CharSequence)\' on a null object reference', errorCode: 'others' }

Works fine on Android 30

### Additional Information
- Image Picker version: 4.0.3
- React Native version: 0.64
- Platform: Android 29

**Comment by chri-heri** [comment]
same here

**Comment by obirije** [comment]
Any fixes yet?

**Comment by Johan-dutoit** [comment]
Please share a reproducible example that causes the above.

**Comment by leeratyou** [comment]
same

**Comment by vinayakb73** [comment]
I am also facing this issue when selecting a video. the result shows like below  

```
{ errorMessage: 'Attempt to invoke virtual method \'boolean java.lang.String.contains(java.lang.CharSequence)\' on a null object reference',
      errorCode: 'others' }
```

**Comment by tanersener** [comment]
I see the same issue. It happens when I apply the steps below on the `example` app provided in this repo.

1. `git clone https://github.com/react-native-image-picker/react-native-image-picker`
2. `cd react-native-image-picker/example`
3. `yarn install`
4. `npm start --reset-cache`
5. start Android Pixel 2 Emulator which uses an x86 image using API 29
6. `npx react-native run-android`
7. Click `Select Video` button and select a video from the `Photos`

The panel below the buttons show the following error.
`
{ errorMessage: 'Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference', errorCode: 'others' }
`

**Comment by jtarmitage** [comment]
Seeing the same error in an app after upgrading from v3.3.4 to v4.0.5.

**Comment by vinayakb73** [comment]
I found the issue. This is the problem with google photo app. Please update google photo app in your emulator. I don't get any issue after that.

> I am also facing this issue when selecting a video. the result shows like below
> 
> ```
> java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
>     at com.imagepicker.Utils.isImageType(Utils.java:355)
>    at com.imagepicker.Utils.getResponseMap(Utils.java:420)
>     at com.imagepicker.ImagePickerModule.onAssetsObtained(ImagePickerModule.java:164)
>     at com.imagepicker.ImagePickerModule.onActivityResult(ImagePickerModule.java:199)
>     at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:305)
>   at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:762)
>    at com.facebook.react.ReactDelegate.onActivityResult(ReactDelegate.java:90)
>     at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:112)
>     at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:68)
>     at com.appapp.MainActivity.onActivityResult(MainActivity.java:86)
>      at android.app.Activity.dispatchActivityResult(Activity.java:8110)
>     at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
>     at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
>     at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
>      at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
>     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
>     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
>     at android.os.Handler.dispatchMessage(Handler.java:107)
>      at android.os.Looper.loop(Looper.java:214)
>     at android.app.ActivityThread.main(ActivityThread.java:7356)
>     at java.lang.reflect.Method.invoke(Native Method)
>    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
>    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
> ```

I found the issue. This is the problem with google photo app. Please update google photo app in your emulator. I don't get any issues after that.

**Comment by K-Leon** [comment]
Sadly it isn't only related to Emulator Devices - it also happens on old Devices with Low Android Versions. Anyone has an Idea where to look for this bug?

**Comment by harshilJs** [comment]
updating google photos in play store fixed this issue!!!

**Comment by saputross** [comment]
still getting this error while selecting video on android 29. any update?

**Comment by harshilJs** [comment]
> still getting this error while selecting video on android 29. any update?

Did you updated your google photos in playstore?
