### ISSUE TITLE
[🐛] Images uploading from gallery is working in debugging mode and not working in releasing mode.

### ISSUE THREAD

**Issue by AwaisIbrar8** [react-native-image-picker/react-native-image-picker#1737]
### Description

When I try to upload image from gallery its giving me response like this

 Response =  {"fileName": "0_(1).jpeg", "fileSize": 34297, "height": 564, "type": "image/jpeg", "uri": "content://media/external/images/media/230", "width": 564}

Its not include image exact path which need to display an image. Its working in debug mode but not working in releasing mode as its not complete image path.

### How to repeat issue and example

The response of image uploading through gallery is 
 Response =  {"fileName": "0_(1).jpeg", "fileSize": 34297, "height": 564, "type": "image/jpeg", "uri": "content://media/external/images/media/230", "width": 564}

### Solution

We need to create image whole path which will show the image correctly. Currently its not giving us in response.

### Additional Information

- Image Picker version: "^2.3.3"
- React Native version: "0.63.2"
- Platform: Android and IOS
- Development Operating System: MacOS
- Dev tools:Android Studio and Xcode

**Comment by ravirajn22** [comment]
Sorry v2.xx are no longer supported. You have to debug the issue on you'r own.
