### ISSUE TITLE
[🐛] React Native Image Picker: Duration Limit prop is not working in android when we upload an existing video

### ISSUE THREAD

**Issue by SyedShehrozSohail** [react-native-image-picker/react-native-image-picker#1738]
### Description

I want to restrict a user to upload a video of duration more than 300 s? Either the bigger videos should be trimmed to 300s or the videos more than 300s should be disabled. I use durationLimit prop which is not working for android. When we record a video, this props **durationLimit** works fine and when we upload a video this does not filters properly. I have used the following versions of this library:

"react-native-image-picker": "^2.3.4"
"react-native-image-picker": "^3.5.0",
"react-native-image-picker": "^4.0.2",
Neither working for me

### Example
Kindly consider the following example in which ideally it should trim any bigger video to 300 seconds. But it's not trimming
`const createVideo = async () => {
    activateKeepAwake();
    let option = {
      title: "Select video",
      takePhotoButtonTitle: null,
      mediaType: "video",
      path: "video",
      quality: 1,
      videoQuality: Platform.OS === "android" ? "low": "normal",
      durationLimit: 300,
      allowsEditing: true,
    };
    ImagePicker.showImagePicker(option, async (response) => {
      if (response.didCancel) {
        console.log("User cancelled image picker");
      } else if (response.error) {
        console.log("ImagePicker Error: ", response.error);
      } else if (response.customButton) {
        console.log("User tapped custom button: ", response.customButton);
      } else {
        if (response && response.uri) {
          let selectedUri;
          let videoFilePath;
          let selectedFileUri = response.uri;
          setVideoLoader(true);
          setModalAddVisible(false);

          if (
            Platform.OS === "ios" &&
            (selectedFileUri.includes(".mov") ||
              selectedFileUri.includes(".MOV"))
          ) {
            videoFilePath = await handleConvertToMP4(selectedFileUri);
            selectedUri = "file://" + videoFilePath.path;
          } else {
            selectedUri =
              Platform.os === "ios"
                ? selectedFileUri
                : "file://" + response.path;
          }
          setVideoSource(null);
          setVideoSource(selectedUri);
          if (Platform.OS === "android") 
            createThumbnailForVideos(selectedUri, 1);
          else 
           await createThumbnailForVideos(selectedUri, 1);

          var filename = selectedUri.substring(
            selectedUri.lastIndexOf("/") + 1,
            selectedUri.length
          );
          const file = {
            uri: selectedUri,
            name: selectedGroup.id + "-dev-" + filename,
          };
          uploadVideoOnS3(file, "video");
        }
      }
    });
  };`
### Solution

Can we do something like disabling the video whose length is more than 300 s or the video bigger than 300 s should be trimmed to 300 sec?
### Additional Information

- Image Picker version: 3.5.0 (tried 2.3.4 and 4.0.2) as well
- React Native version: 0.63.2
- Platform: Android

**Comment by ravirajn22** [comment]
durationLimit only works for videos taken from camera, we do not have the option to show only videos less some secs in gallery.
