### ISSUE TITLE
[🐛] Multiple image selection not working on Samsung devices.

### ISSUE THREAD

**Issue by Alaaeddine-chakroun** [react-native-image-picker/react-native-image-picker#1739]
### Description

Setting selectionLimit has no effect on file selection on Samsung devices when choosing the Samsung Gallery App. Works as expected in iOS, Google photos and every other brand gallery.

### How to repeat issue and example

- Call launchImageLibrary({mediaType: 'photo', selectionLimit: 0}) on a Samsung device
- Choose Gallery when prompted.
- Try to select multiple files.

### Solution

Behaviour should be no different from other brands of devices.

### Additional Information

- Image Picker version: 4.0.3
- React Native version: 0.64.0
- Platform: Android
- Development Operating System: MacOS Big Sur 11.4
- Dev tools: Tested on Samsung Galaxy S9+ running Android 10 / One UI 2.5 and Samsung A20 Running Android 10 / One UI 2.0

**Comment by ravirajn22** [comment]
Can u add more info, does long pressing work?

**Comment by Alaaeddine-chakroun** [comment]
> Can u add more info, does long pressing work?

Neither long pressing or dragging works to select multiple images. Upon tapping the first picture the callback fires with the picture's information (same behaviour as selectionLimit : 1 on other platforms). Tried to dig a bit deeper and apparently the Samsung Gallery App does not respect the EXTRA_ALLOW_MULTIPLE Intent and this has been an issue for a while.

**Comment by ravirajn22** [comment]
If you can find a solution, send a PR.

**Comment by aborile** [comment]
Same Issue on LG devices!
Is there any progress? I wonder if it is android issue or not.

**Comment by Johan-dutoit** [comment]
According to [this SO post](https://stackoverflow.com/questions/46016971/trying-to-pick-images-from-samsungs-gallery), we should change `ACTION_PICK` to `ACTION_GET_CONTENT` here https://github.com/react-native-image-picker/react-native-image-picker/blob/c8f8481eb2c08e8f160ae80177e51c693e887969/android/src/main/java/com/imagepicker/ImagePickerModule.java#L134

**Comment by ravirajn22** [comment]
@Johan-dutoit we should change this to  `ACTION_GET_CONTENT` for multi selection and leave it to `ACTION_PICK` for single selection.
