### ISSUE TITLE
[🐛] App crashed after select Video from Library in iOS 13

### ISSUE THREAD

**Issue by vivianlys90** [react-native-image-picker/react-native-image-picker#1742]
### Description

Getting this error after select Video from Library in iOS 13. App crashed at function didFinishPickingMediaWithInfo.

"Error returned from daemon: Error Domain=com.apple.accounts Code=7 "(null)""

<img width="1127" alt="Screenshot 2021-06-08 at 10 29 11 AM" src="https://user-images.githubusercontent.com/22317616/121113476-aebec000-c844-11eb-8c54-00affdf0cbfd.png">

### How to repeat issue and example

- Use this options for Video selection:
{
    "durationLimit": 600,
    "maxHeight": 1000,
    "maxWidth": 1000,
    "mediaType": "video",
    "quality": 1,
    "videoQuality": "low"
}
- Choose Video from Library
- Showing Video viewer screen
- Tap on 'Choose' and compress video
- App crashed

### Additional Information

- Image Picker version: 4.0.3
- React Native version: 0.63
- Platform: iOS
- Development Operating System: MacOS
- Dev tools: Xcode 12.4

**Comment by m3rlin94** [comment]
Happening this to me as well.

**Comment by m3rlin94** [comment]
Can confirm this is happening on v4.0.4

**Comment by vivianlys90** [comment]
Hi Naveen,
I have submitted my fixes and now still waiting for code review.You can check this pull request #1743
Have a good day.
Best Regards,Vivian Lee


    On Tuesday, 29 June 2021, 09:42:29 am MYT, Naveen Cooray ***@***.***> wrote:  
 
 


Happening this to me as well.

**Comment by m3rlin94** [comment]
> Hi Naveen, I have submitted my fixes and now still waiting for code review.You can check this pull request #1743 Have a good day. Best Regards,Vivian Lee On Tuesday, 29 June 2021, 09:42:29 am MYT, Naveen Cooray ***@***.***> wrote: Happening this to me as well. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks @vivianlys90! Will check that out

**Comment by Muffles** [comment]
Same here, can confirm this is happening on 4.0.4

**Comment by klakshman8** [comment]
I am still having issue any solution

**Comment by vivianlys90** [comment]
I have submitted PR for this issue, but still waiting for code merge. #1743

**Comment by musesfish** [comment]
when I picked a video in Android 
APP crashed in recently
react–native 0.59.1
react–native–image–picker 0.28.1
so I set option mediaType:'photo' 
but I still can choose video 
I try to make the most simple option
and I find remove the option 'quality' 
that can solve crash
but no 'quality' upload image is too slow 
hope having a best solution

**Comment by musesfish** [comment]
when I picked a video in Android 
APP crashed in recently
react–native 0.59.1
react–native–image–picker 0.28.1
so I set option mediaType:'photo' 
but I still can choose video 
I try to make the most simple option
and I find remove the option 'quality' 
that can solve crash
but no 'quality' upload image is too slow 
hope having a best solution
