### ISSUE TITLE
[🐛] Can't get video extension and it's required to upload to cloudinary

### ISSUE THREAD

**Issue by mohamed2m2018** [react-native-image-picker/react-native-image-picker#1744]
The response comes as the following for videos on android
 {"assets": [{"duration": 4, "fileName": "video:90011", "fileSize": 6508528, "uri": "content://com.android.providers.media.documents/document/video%3A90011"}]}

I need to have the video extension to upload it to cloudinary.

How can I get it?

**Comment by nero2009** [comment]
Did you find a solution?

This might point you in the right direction [https://github.com/itinance/react-native-fs/pull/833](https://github.com/itinance/react-native-fs/pull/833)

**Comment by Shik1997** [comment]
@mohamed2m2018  i see you closed this issue,now i meet the same problem,can you tell me how to solve it ?

**Comment by Subiyel** [comment]
+1 any solutions?

**Comment by nero2009** [comment]
https://github.com/itinance/react-native-fs/pull/833/files
