### ISSUE TITLE
[BUG] Keyboard opening after picking an image on iOS

### ISSUE THREAD

**Issue by kopax-polyconseil** [react-native-image-picker/react-native-image-picker#1745]
### Description

We have the same issue as in #1442 in our project. We do not have any input, we are just uploading an identity document.

When document is uploading, we render a `<Loader />` component, on top of it, we have erratically the keyboard showing up:

![image](https://user-images.githubusercontent.com/77674046/121383043-705df980-c947-11eb-9601-27be2e3252c2.png)

Could this be reopened? It seems I am not the only one either https://stackoverflow.com/questions/64276843/react-native-image-picker-opens-keyboard-after-selecting-the-image

### How to repeat issue and example

- Download on the iOS store the app pass culture, register as someone born in is eighteen years old, got to the identity verification check, upload document from library.

### Solution

We have none so far, and we may have to change the uploading library if we can't find a solution.

### Additional Information

- Image Picker version: 2.3.4
- React Native version: 0.63.3
- Platform: iOS
- Development Operating System: Mac OS Big Sur 11.2.3
- Dev tools: Xcode 12.4 (12D4e)

**Comment by Johan-dutoit** [comment]
Can you create a reproducible example for us to debug this please?

**Comment by ravirajn22** [comment]
version 2.x.x is no longer supported. Update to latest version and test.

**Comment by kopax-polyconseil** [comment]
We just did to solve the issue, now we still had this, so far only on iPhone 7. and systematically.
