### ISSUE TITLE
[🐛] TypeError:undefined is not a function(near'...imagePicker.showImagePicker...')

### ISSUE THREAD

**Issue by kmkz-69** [react-native-image-picker/react-native-image-picker#1746]
### Description
![Capture](https://user-images.githubusercontent.com/67412667/121501808-dac27880-c9df-11eb-8b7f-dbb2ad495159.PNG)

### ****
Explain the bug in as much detail as possible
I've installed react-native-image-picker successfully, for a fresh react native app, linked it and given right permissions via the info.plist file to access camera, photos etc...

When attempting to openGallery() I get the following warning and no image library opens:

TypeError: undefined is not a function (near '...ImagePicker.showImagePicker...')
### How to repeat issue and example
![import](https://user-images.githubusercontent.com/67412667/121492463-31778480-c9d7-11eb-85f7-ccfa8baf16ee.PNG)

![picker](https://user-images.githubusercontent.com/67412667/121492321-1147c580-c9d7-11eb-8ee2-1d3cb8e048ad.PNG)

**Comment by Johan-dutoit** [comment]
Hi, did you rebuild after installing it?

**Comment by kmkz-69** [comment]
Thanks I replace showImagePicker and it works

**Comment by talhashafique12** [comment]
> `showImagePicker` no longer exists. Check the docs.

whats the alternate to showImagePicker to show native picker modal ?
