### ISSUE TITLE
Android Video upload issue

### ISSUE THREAD

**Issue by codal-mpawar** [react-native-image-picker/react-native-image-picker#1758]
1. /data/user/0/com.example/cache/rn_image_picker_lib_temp_92be7bbb-cdec-4495-99b4-ac6a4c98ac92.mp4
2. file://data/user/0/com.example/cache/rn_image_picker_lib_temp_92be7bbb-cdec-4495-99b4-ac6a4c98ac92.mp4

try with both url
Hey guys I have one blocker

When i capture video from library and get response and got uri
then i upload video on s3 bucket and got error like video is corrupted.

**Comment by Johan-dutoit** [comment]
I personally upload files to both S3 and Firebase storage with no issues.  Without seeing your code it's hard to determine what's wrong.

**Comment by prabhakardude** [comment]
> I personally upload files to both S3 and Firebase storage with no issues. Without seeing your code it's hard to determine what's wrong/where the issue is.

Can you tell me how to convert video to base64 uri. I am facing issues.

**Comment by lukebrandonfarrell** [comment]
Video being corrupted has to do with your upload method, you want to do something like this:

```
FileSystem.createUploadTask(
          presignedUrl,
          fileUrl,
          {
            httpMethod: 'PUT',
            uploadType: ExpoFileSystem.FileSystemUploadType.BINARY_CONTENT,
            headers: {
              'Content-Type': mimeType,
              Accept: 'application/json',
            },
          },
```

This is using `expo-file-system`. Also you need to make sure your file is saved as `file://` and not `content://` or `asset-library://`.
