### ISSUE TITLE
[🐛] Camera does not open in apk with android 10

### ISSUE THREAD

**Issue by huandrey** [react-native-image-picker/react-native-image-picker#1768]
### Description

The camera by the emulator works perfectly, however, when generating the apk and putting it in the store, it stops working. I tested it with a cell phone that has android 8 and it worked perfectly. However, when testing with a cell phone running android 10 the camera does not open. I would like to know if this problem has already been fixed in any specific new version.
The version I'm currently using is 3.3.3
I already followed the instructions for issue #1213 but it didn't solve the problem.

- Image Picker version: [3.3.3]

**Comment by huandrey** [comment]
Trecho de código no qual eu chamo a função launchCamera. Acredito que não tenha nada errado nesse codigo já que ele funciona em uma determinada versão do android e outra não. 

![image](https://user-images.githubusercontent.com/62030386/124367903-e9442e80-dc31-11eb-9eb8-2897161738a9.png)

**Comment by valin0k** [comment]
<img width="363" alt="Снимок экрана 2021-07-05 в 14 01 27" src="https://user-images.githubusercontent.com/8665687/124430709-b321be80-dd99-11eb-9afb-953c2ab2289e.png">

also not working with 4.0.4 version on android

**Comment by ravirajn22** [comment]
In release what is happening? 
- is the app crashing
- Camera opening but no response
- Nothing is happening when calling launchCamera?
- If possbile try it emulator on version 10 and check the error status

**Dont use #1213, its outdated.**

**Comment by axeljeremy7** [comment]
the. ImagePicker is undefined, so it fails
selectImage()
 undefined
[TypeError: undefined is not an object (evaluating '_reactNativeImagePicker.default.launchImageLibrary')]
{"message": "undefined is not an object (evaluating '_reactNativeImagePicker.default.launchImageLibrary')", "title": "selectImage()"}

**Comment by huandrey** [comment]
I updated the lib to version 4.0.4 but the problem persists. I made the necessary modifications for the lib to work correctly in the emulator but the problem persists in the apk running on the physical phone.
However, I was curious to know if the issue was a permission issue, so I manually modified the phone settings to allow access to the camera and it worked.
**The question: How do I open a popup asking the user to allow this access?** Since issue #1213 is out of date.

![image](https://user-images.githubusercontent.com/62030386/124509843-fdf70280-dda8-11eb-92fe-a8bfc9d3d9f6.png)

**Comment by huandrey** [comment]
Problem solved! I just called this function. I found this solution [aqui](https://developerplus.com.br/react-native-permissionsandroid-como-pedir-permissao-no-android/#:~:text=Faremos%20um%20bot%C3%A3o%20no%20centro,%7B%20const%20granted%20%3D%20await%20PermissionsAndroid.)
Basically it asks for camera permission at runtime.

![image](https://user-images.githubusercontent.com/62030386/124520608-4d4a2c80-ddc3-11eb-8dba-ee219fcf1a26.png)
