### ISSUE TITLE
[🐛]  selectionLimit not working on Android

### ISSUE THREAD

**Issue by hugod-g** [react-native-image-picker/react-native-image-picker#1769]
### Description

I want to limit the user in the number of pictures he can choose. It's working properly on iOS but on Android, the limit is not working and the user can choose an unlimited number of pictures.

Here are my options for the picker : 

`{
            title: 'Images',
            storageOptions: {
                skipBackup: true,
                path: 'images',
            },
            selectionLimit: 5,
            mediaType: 'photo',
}`

**Comment by ravirajn22** [comment]
Yes, thats how it works. Please go through the docs. There is no option in android to do that.

**Comment by changzhanpeng** [comment]
I also encountered this problem when using it. So, will you consider fixing this problem in the future? IOS and Android don't agree and that's embarrassing.

**Comment by Johan-dutoit** [comment]
If I understand what @ravirajn22 is saying, it's a problem with Android itself, and not this library (correct me if I'm wrong).  Which means it's outside of the scope of this library.
