### ISSUE TITLE
Android auto cancelling launchCamera after 2-3 minutes 

### ISSUE THREAD

**Issue by rgbedin** [react-native-image-picker/react-native-image-picker#1773]
I am not sure if that is being observed by any other developer or if I am using the library in a non-standard way. I am calling `launchCamera` using the piece of code below:

```javascript
  const cameraOptions: CameraOptions = {
    mediaType: 'photo',
    saveToPhotos: true,
    quality: args?.quality || 1.0,
    includeBase64: args?.includeBase64 || false,
    maxHeight: args?.maxHeight || 4000,
    maxWidth: args?.maxWidth || 4000
  };

  const cameraPicker = useCallback(
    async (callback: PickerCallback): Promise<void> => {
      const permissionsToCheck =
        Platform.OS === 'android'
          ? [
              PERMISSIONS.ANDROID.CAMERA,
              PERMISSIONS.ANDROID.WRITE_EXTERNAL_STORAGE
            ]
          : [PERMISSIONS.IOS.CAMERA];

      const hasPermissions = await assertPermissions(permissionsToCheck);
      if (!hasPermissions) return callback();

      launchCamera(cameraOptions, (res) => {
        Log.debug(
          'useFilePicker: camera res:',
          JSON.stringify(res).substring(0, 100)
        );
        parseResponse('camera', res, callback);
      });
    },
    [cameraOptions]
  );
```

Everything works fine if the user takes their action in less than 2 minutes or so. However if I just leave the app open it is automatically dismissing the screen and giving me the following `res` reply: `LOG  11:55:31 a.m. | DEBUG | useFilePicker: camera res: {"didCancel":true}`. The only thing I do is firing the `cameraPicker()` code above and leaving the app idle.

I tried double checking if my component is getting unmounted for some reason, but that does not seem to be the case. The app is not changing any of its states either.

Any leads on what might be causing this issue?

Here's my package info:

```
"react-native": "0.64.2"
"react-native-image-picker": "4.0.6"
```

**Comment by Johan-dutoit** [comment]
Based on a quick google, this seems to be because the sensor gets hot and shuts down.

i.e. https://www.reddit.com/r/galaxynote10/comments/djmjy9/camera_app_closes_automatically_after_23_minutes/

Might be worth feeling your phone/camera area after it closes.

**Comment by rgbedin** [comment]
It should be fine, since I am in Canada and the temperature is actually very cool most of the time. Anyone else getting this?

**Comment by Johan-dutoit** [comment]
I'd say if you can reproduce this with your phones camera app, then it's a safety feature either built into android or the camera app.  If not, feel free to reopen the issue.
