### ISSUE TITLE
Cannot read property 'launchImageLibrary' of null, js engine: hermes[🐛] 

### ISSUE THREAD

**Issue by pbic999** [react-native-image-picker/react-native-image-picker#1774]
import React, { useRef, useState } from 'react'
import { View, Text, StyleSheet, Animated } from 'react-native'
import { ScrollView } from 'react-native-gesture-handler'
import {launchCamera,launchImageLibrary} from 'react-native-image-picker'

const AddProducts = () => {
    const [height,setHeight] = useState(new Animated.Value(-250)) 
    let height0 = true

    const AnimateView = () => {
        Animated.timing(height,{
            toValue: height0 ? 0 : -250,
            duration: 800,
            useNativeDriver: false
        }).start()
        height0 = !height0  
        console.log(height0);
    }
    
    const openCamera = () => {
        launchCamera({mediaType: 'photo',
        quality:1,includeBase64:true}, (res)=>{
            console.log(res);
        });
    }

    const openLibrary = () => {
        launchImageLibrary({mediaType: 'photo',
        quality:1,includeBase64:true}, (res)=>{
            console.log(res);
        });
    }

    return <View style={{width:'100%',height:'100%'}}>
        <Text style={styles.button}
            onPress={AnimateView}
        >
            Open
        </Text>
        <Animated.View
            style={[{bottom:height,position:'absolute',width:'100%'}]}
        >
            <View style={styles.ButtonSheet}>
                <Text style={styles.header}>Upload Photo</Text>
            <Text style={styles.button} onPress={openCamera}> TakePhoto </Text>
            <Text style={styles.button} onPress={openLibrary}> Choose From Library </Text>
            <Text style={styles.button} onPress={AnimateView}> Cancel </Text>
            </View>
        </Animated.View>
    </View>
}

const styles = StyleSheet.create({
    button: {
        fontSize: 20,
        fontWeight: "bold",
        color: "#fff",
        backgroundColor: "#4a3680",
        textAlign: "center",
        padding: 10,
        marginTop: 10,
        borderRadius: 10
    },
    ButtonSheet: {
        shadowColor: "#000",
        shadowOffset: 
        {
            width: 0,
            height: 1,
        },
        shadowOpacity: 0.22,
        shadowRadius: 2.22,
        elevation: 2,
        padding:15,
        borderTopRightRadius:10,
        borderTopLeftRadius: 10
    },
    header: {
        fontSize:22,
        fontFamily:'sans-serif-medium',
        color: '#000',
        alignSelf:'center',
        marginTop:10
    }
})
export default AddProducts

**Comment by Badrouu17** [comment]
Am having the same issue. any solution?
