### ISSUE TITLE
[🐛] videoQuality not working

### ISSUE THREAD

**Issue by Liqiankun** [react-native-image-picker/react-native-image-picker#1775]
### Description
<img width="540" alt="截屏2021-07-20 14 29 59" src="https://user-images.githubusercontent.com/11532418/126273330-1c49fbb6-59c4-4157-a43d-08fa8f8b9080.png">

```
const videoOptions = {
  title: '请选择',
  cancelButtonTitle: '取消',
  takePhotoButtonTitle: '拍照',
  chooseFromLibraryButtonTitle: '从相册选取',
  selectionLimit: 1,
  mediaType: 'video',
  videoQuality: 'low',
  durationLimit: 1
};
```
Original video size is 5.7M, picked vide size is still 5.7M.

### Additional Information

- Image Picker version: 4.0.5
- React Native version: 0.62.0
- Platform: iOS
- Development Operating System: MacOS

**Comment by Johan-dutoit** [comment]
Do you know if this is on iOS only? or both platforms?

**Comment by Liqiankun** [comment]
@Johan-dutoit I just tested it on iOS.

**Comment by Johan-dutoit** [comment]
Just had a look at the code and videoQuality is only for recording new videos.

**Comment by Johan-dutoit** [comment]
I'll submit a PR with the changes, if you don't mind testing @Liqiankun.

**Comment by Johan-dutoit** [comment]
Keep in mind, that if the video quality is already low, then it won't change anything.

**Comment by Liqiankun** [comment]
@Johan-dutoit What about android?

**Comment by Johan-dutoit** [comment]
If you have the same issue on Android, it can be looked at.

**Comment by Liqiankun** [comment]
let me check it out

**Comment by hkhan6916** [comment]
videoQuality doesn't do anything. The video is always high resolution.

**Comment by mattlewer** [comment]
@Johan-dutoit This doesn't seem to work for me either, always the same size no matter what videoQuality is passed when using the picker
