### ISSUE TITLE
With Expo, get this error: [TypeError: null is not an object (evaluating '_reactNative.NativeModules.ImagePickerManager.launchImageLibrary')][🐛] 

### ISSUE THREAD

**Issue by Sigfried95** [react-native-image-picker/react-native-image-picker#1786]
Hello! 
I am using react-native-image-picker with Expo and when run function (launchCamera or launchImageLibrary) get this error:

error: [TypeError: null is not an object (evaluating '_reactNative.NativeModules.ImagePickerManager.launchImageLibrary')]

error [TypeError: null is not an object (evaluating '_reactNative.NativeModules.ImagePickerManager.launchCamera')]

code: 

import { launchCamera, launchImageLibrary } from 'react-native-image-picker';

  const pickImage = () => {
    try {
      launchImageLibrary({ mediaType: 'photo' }, resp => {
        console.log(resp);
      });
    } catch (error) {
      console.log('error', error);
    }
  }

  const camera= () => {
    try {
      launchCamera({ mediaType: 'photo' }, resp => {
        console.log(resp);
      });
    } catch (error) {
      console.log('error', error);
    }
  }

version:
"react-native-image-picker": "^4.0.6",

Any help please, thanks.

**Comment by abdouthetif** [comment]
Same issue here ! Any solution please !

**Comment by mooglemoogle** [comment]
I'm having this issue but only when I run in expo-go. When I run from xcode in the simulator or on-device it works fine. I've cleaned and rebuilt in xcode and run `expo start --clear` a hundred times and I'm still getting this. I've also installed other libraries that work fine.

**Comment by maelthi** [comment]
Same issue on android

**Comment by lukehali** [comment]
Getting the exact same issue here on android

**Comment by lukehali** [comment]
Just managed to fix this for my project. I needed to add two things to MainApplication.java

Add this to the top with your imports:
`import com.imagepicker.ImagePickerPackage;`

And add this ImagePickerPackage() where your MainReactPackage is:
```
protected List<ReactPackage> getPackages() {
          return Arrays.<ReactPackage>asList(
            new MainReactPackage(),
...
            new ImagePickerPackage()
);
}
```

**Comment by Flooooooooooorian** [comment]
this helped me https://docs.expo.dev/versions/v42.0.0/sdk/imagepicker/

**Comment by Sigfried95** [comment]
@lukehali  Searching your option, I understand that this is possible only if detach expo project, because in my expo project  not found this files. And detach expo project it would be my last option.

@Flooooooooooorian yes, by the moment I'm using expo-image-picker, but this library no support select multiples images and that is what I need.

-- I create a new application with React Native without Expo and the library works without problems, will it be some incompatibility with expo?
-- someone knows similar library with multiple select images and run with expo?

**Comment by owenashurst** [comment]
Having the same issue. Any ideas?

**Comment by phuquoc164** [comment]
Hello, I have the same issue. Anybody can help me, please ? Thank you

**Comment by aza777p** [comment]
HI 

IF YOU HAVE THIS PROBLEM

FIRST GO https://docs.expo.dev/versions/latest/sdk/imagepicker/

AFTER INSTALL IN YOUR CMD

expo install expo-image-picker

AND COPY AND PASTE THIS

import React, { useState, useEffect } from 'react';
import { Button, Image, View, Platform } from 'react-native';
import * as ImagePicker from 'expo-image-picker';

export default function ImagePickerExample() {
  const [image, setImage] = useState(null);

  const pickImage = async () => {
    // No permissions request is necessary for launching the image library
    let result = await ImagePicker.launchImageLibraryAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.All,
      allowsEditing: true,
      aspect: [4, 3],
      quality: 1,
    });

    console.log(result);

    if (!result.cancelled) {
      setImage(result.uri);
    }
  };

  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Button title="Pick an image from camera roll" onPress={pickImage} />
      {image && <Image source={{ uri: image }} style={{ width: 200, height: 200 }} />}
    </View>
  );
}

AND RELOADING YOUR APP

**Comment by audteyebaris** [comment]
```ts
import React, { useState, useEffect } from 'react';
import { Button, Image, View, Platform } from 'react-native';
import * as ImagePicker from 'expo-image-picker';  // not react-image-picker

export default function ImagePickerExample() {
  const [image, setImage] = useState(null);

  const pickImage = async () => {
    // No permissions request is necessary for launching the image library
    let result = await ImagePicker.launchImageLibraryAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.All,
      allowsEditing: true,
      aspect: [4, 3],
      quality: 1,
    });

    console.log(result);



    if (!result.cancelled) {
      setImage(result.uri);
    }
  };

  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Button title="Pick an image from camera roll" onPress={pickImage} />
      {image && <Image source={{ uri: image }} style={{ width: 200, height: 200 }} />}
    </View>
  );
}
```

**Comment by EKOzkan** [comment]
> Just managed to fix this for my project. I needed to add two things to MainApplication.java
> 
> Add this to the top with your imports: `import com.imagepicker.ImagePickerPackage;`
> 
> And add this ImagePickerPackage() where your MainReactPackage is:
> 
> ```
> protected List<ReactPackage> getPackages() {
>           return Arrays.<ReactPackage>asList(
>             new MainReactPackage(),
> ...
>             new ImagePickerPackage()
> );
> }
> ```

I am using expo expo-dev-client with eas build in my project. Got the same error and this solution solved my problem. I just edited MainApplication.java. Added the import part to top and edited the other part like this:
`        protected List<ReactPackage> getPackages() {
          @SuppressWarnings("UnnecessaryLocalVariable")
          List<ReactPackage> packages = new PackageList(this).getPackages();
          packages.add(new MainReactPackage());
          packages.add(new ImagePickerPackage());
          return packages;
        }`

Then I rebuild my app and its working right now.

**Comment by shiffananazeema** [comment]
@audteyebaris 

Finally It Worked 

Using

npx expo install expo-image-picker
