### ISSUE TITLE
[🐛] 

### ISSUE THREAD

**Issue by Mothilal-AuthorSelvi** [react-native-image-picker/react-native-image-picker#1799]
### Description

selectionLimit on launchImageLibrary >=2 it allows all photos to be selected,
in launchCamera i can able to take multiple images

### How to repeat issue and example

- selectionLimit on launchImageLibrary >=2 it allows all photos to be selected
-selectionLimit on launchCamera, it allows only one photo to take at time
- eg: selectionLimit : 3,  even the limit is 3 i can able to select 60 images

### Solution

help to solve the issue

### Additional Information

- Image Picker version: 4.0.6
- React Native version: 0.64.2
- Platform:  Android-11
- Development Operating System: Linux
- Dev tools: SDK-Android API - 30

**Comment by lukebrandonfarrell** [comment]
This is expected on Android, you either have `multiselect` enabled or not, I suggest you just grab the first two photos from the results array.
