### ISSUE TITLE
[🐛] xiaomi Red4A多次拍照崩溃问题

### ISSUE THREAD

**Issue by guojiabin** [react-native-image-picker/react-native-image-picker#1807]
### Description

Explain the bug in as much detail as possible

### How to repeat issue and example

- step to reproduce the issue
- ...

### Solution

What needs to be done to address this issue?

### Additional Information

- Image Picker version: [FILL THIS OUT: Be specific, filling out "latest" here is not enough.]
- React Native version: [FILL THIS OUT: Be specific, filling out "latest" here is not enough.]
- Platform: [FILL THIS OUT: iOS, Android, or both?]
- Development Operating System: [FILL THIS OUT: Are you developing on MacOS, Linux, or Windows?]
- Dev tools: [FILL THIS OUT: Xcode or Android Studio version, iOS or Android SDK version, if applicable] navigation crash for Android
![IMG_20210826_145854](https://user-images.githubusercontent.com/16753842/130916677-17729ceb-7522-42b3-b4b5-2ff5120dac36.jpg)

**Comment by lukebrandonfarrell** [comment]
Not enough details, please be more clear about the specific bug you are experiencing
