### ISSUE TITLE
[🌟] How about making a gallery selectable with the default app?

### ISSUE THREAD

**Issue by bitdessert** [react-native-image-picker/react-native-image-picker#1809]
### Description

Explain the feature request in as much detail as possible.

The version I originally applied was 2.3.4.

`mediaType: Platform.OS === 'android' ? 'photo' : 'mixed',`

The launchImageLibrary method allows me to select a gallery app or a photo library app.

![image](https://user-images.githubusercontent.com/42505950/131443941-8bae3b73-ed88-4dbe-b23e-a54f5d2f076e.png)

I've tested version 4.0.6 now. 

I cannot select the default app, and the library runs immediately.

So, it would be nice to have the ability to select Android's gallery app.
Selecting captured images in the Gallery app is easier.

### Proposed Solution

What needs to be done to make it happen?

### Test Solution

How would we test & validate the feature?

**Comment by lukebrandonfarrell** [comment]
This seems system related. Please re-open with more details if you want a discussion around solution for this. Thanks
