### ISSUE TITLE
[🌟] Return `asset.type` for videos on iOS

### ISSUE THREAD

**Issue by dylanpyle** [react-native-image-picker/react-native-image-picker#1823]
### Description

Probably related to https://github.com/react-native-image-picker/react-native-image-picker/issues/1670

When you select a photo from the library or camera, `response.assets` includes an array of assets and metadata e.g:

```
[
    {
        "type": "image/jpg",
        "fileName": "8F471139-AB15-457B-A817-EF41BF621231.jpg",
        "width": 3024,
        "height": 4032,
        "uri": "file:///var/mobile/Containers/Data/Application/CA9B8D34-12F7-41A6-9364-FEBF5C536BAD/tmp/8F471139-AB15-457B-A817-EF41BF621231.jpg",
        "fileSize": 6718368
    }
]
```

However, when you select a video, the response is much shorter:
```
[
    {
        "uri": "file:///var/mobile/Containers/Data/Application/CA9B8D34-12F7-41A6-9364-FEBF5C536BAD/tmp/65342717611__C9361CAE-D68A-44ED-9DDB-22B3AE58C0EA.MOV",
        "duration": 0
    }
]
```

I'm not sure if I should open a separate feature request for each field I'd like here, but `type` would be very useful info to have, rather than having to reverse-engineer it from the file name.

### Proposed Solution

Return a valid mime type (e.g. `video/quicktime`) in the `asset.type` field

### Test Solution

See description

**Comment by Johan-dutoit** [comment]
Is this solved by https://github.com/react-native-image-picker/react-native-image-picker/pull/1808/files ?

**Comment by dylanpyle** [comment]
@Johan-dutoit it looks like it would be, yeah! i haven't tested that branch on device but seems like that would fix it

**Comment by Johan-dutoit** [comment]
@dylanpyle if you can grab that branch and let us know how it goes, then we can merge it in and release it.

**Comment by dylanpyle** [comment]
@Johan-dutoit confirmed - that PR solves this issue for me 😄 . Here's a sample response:

```
{
    "type": "video/quicktime",
    "duration": 2,
    "uri": "file:///Users/dylan/Library/Developer/CoreSimulator/Devices/68EAE109-0984-4262-A888-56540F8A36BC/data/Containers/Data/Application/080903F0-6932-4661-A443-ACA5ECD20283/tmp/www.mov"
}
```

**Comment by Hermont76** [comment]
Working for me.
