### ISSUE TITLE
[🐛] Cannot pick video with launchImageLibrary mediaType: 'mixed'  on Android

### ISSUE THREAD

**Issue by taitran2512** [react-native-image-picker/react-native-image-picker#1834]
### Description
"react-native-image-picker": "^4.1.1",
"react-native": "0.64.1",
Platform: Android,
AndroidVersion: 11,
DeviceBrand: Xiaomi.

I'm using launchImageLibrary with option mediaType: 'mixed' to pick video and images, on IOS it's ok but on my android (Xiaomi) it didn't show any video in the library

Thanks

**Comment by Johan-dutoit** [comment]
Are you able to reproduce this with the example app?
