### ISSUE TITLE
[🌟] Preserve millisecond resolution when reporting video duration

### ISSUE THREAD

**Issue by davidisaaclee** [react-native-image-picker/react-native-image-picker#1842]
### Description

When reporting a picked video's `duration`, this library rounds the value to the nearest whole second (e.g. a 3.5 second video will be reported as `duration: 3`). There is higher resolution available on iOS, and it seems like there is higher resolution available on Android as well.

### Proposed Solution

There is an explicit call to round the native subsecond duration in both Android and iOS code, which was included in the original PR which added the duration field https://github.com/react-native-image-picker/react-native-image-picker/pull/1676 without rationale:

https://github.com/react-native-image-picker/react-native-image-picker/blob/383c1230caa13e4503455ba8f142afd3f235c4a6/ios/ImagePickerManager.m#L181
https://github.com/react-native-image-picker/react-native-image-picker/blob/383c1230caa13e4503455ba8f142afd3f235c4a6/android/src/main/java/com/imagepicker/Utils.java#L268

**I think this rounding should be removed, and this library should pass along the full resolution reported by the native [`CMTime.seconds`](https://developer.apple.com/documentation/coremedia/cmtime/1489443-seconds) or [`METADATA_KEY_DURATION`](https://stuff.mit.edu/afs/sipb/project/android/docs/reference/android/media/MediaMetadataRetriever.html#METADATA_KEY_DURATION)** (e.g. a 3.5 second video should be reported as `duration: 3.5`).

I'm using a fork of this library to give full resolution `duration` on iOS, which works by simply removing the call to `roundf`. Not knowing much about Java, it looks like the Android code will need to be explicit about the int value changing to a float, but it also seems like those values are being stuck in a heterogeneous `WritableMap` ¯\\\_(ツ)\_/¯ I could give the Android change a shot, but would need help verifying the change.

I think this will unfortunately be a breaking change, since the `duration`s reported by the library for a given video file will be different after this change is applied.

### Test Solution

Not sure – there is no test solution for https://github.com/react-native-image-picker/react-native-image-picker/pull/1676 – open to suggestions.

**Comment by davidisaaclee** [comment]
@pierroo I think https://github.com/react-native-image-picker/react-native-image-picker/pull/1849 should be providing the duration to the millisecond without rounding on iOS - is it not doing that for you?

**Comment by pierroo** [comment]
Thank you for the link @davidisaaclee ! :)
I only tried on android so far; maybe the fix is only for iOS?
That means on iOS it will be working natively with the right duration without me doing anything else?
And regarding android, any plan on adding the same fix? That would be awesome :)
