### ISSUE TITLE
[🐛] 

### ISSUE THREAD

**Issue by musesfish** [react-native-image-picker/react-native-image-picker#1868]
when I picked a video in Android
APP crashed in recently
react–native 0.59.1
react–native–image–picker 0.28.1
so I set option mediaType:'photo'
but I still can choose video
I try to make the most simple option
and I find remove the option 'quality'
that can solve crash
but no 'quality' upload image is too slow
hope having a best solution

**Comment by lukebrandonfarrell** [comment]
Going to close this. Please open with more details such as: title for the issue, a video of what is happening, any crash reports attached from Android Logcat or iOS xCode debug. Thanks
