### ISSUE TITLE
Limit number of Images selected by user[🌟] 

### ISSUE THREAD

**Issue by mehdi-developer** [react-native-image-picker/react-native-image-picker#1871]
### Description

Please provide the option to select how many photos user can select from their gallery not just 1 or how many they want to .
For example accept only 3 photos like this :

 launchImageLibrary(
            {
              mediaType: 'photo',
              selectionLimit: 3,
            },
            res => {
              console.log(res);
            },
          );

### Proposed Solution

selectionLimit: 3

**Comment by lukebrandonfarrell** [comment]
For Android there is no possibility with Intent.EXTRA_ALLOW_MULTIPLE. For iOS we already provide this API. If you need to limit the images on Android then do a `.slice` on the results.
