### ISSUE TITLE
[🐛] when trying to launchImageLibrary return includeExtra exception

### ISSUE THREAD

**Issue by sunilnirania98** [react-native-image-picker/react-native-image-picker#1878]
### Description
my app show error incluydeExtra and stuck on this step.

"react": "17.0.2",
"react-native": "0.65.1"
"react-native-image-picker": "^4.3.0"
"Platform": "Android"
"OS": "Windows"

### Configured Options
`launchImageLibrary({
            compressImageQuality: 0.7,
            mediaType: 'photo',
            maxWidth: 1024,
            maxHeight: 1024,
            selectionLimit: 0
        }, (response) => { console.log(response) 
});`

I also tried with
`launchImageLibrary({
            compressImageQuality: 0.7,
            mediaType: 'photo',
            maxWidth: 1024,
            maxHeight: 1024,
            selectionLimit: 0,
            includeExtra:true,
        }, (response) => { console.log(response) 
});`

and

`launchImageLibrary({
            compressImageQuality: 0.7,
            mediaType: 'photo',
            maxWidth: 1024,
            maxHeight: 1024,
            selectionLimit: 0,
            includeExtra:false,
        }, (response) => { console.log(response) 
});`

![Screenshot_1638151354](https://user-images.githubusercontent.com/70876826/143798787-9c54c112-285f-460c-a313-1575b10b974e.png)

**Comment by sunilnirania98** [comment]
this issue resolved when i created release build and after that debug mode also working fine.

**Comment by lukebrandonfarrell** [comment]
Good to know @sunilnirania98
