### ISSUE TITLE
[🌟] 

### ISSUE THREAD

**Issue by jbcullis** [react-native-image-picker/react-native-image-picker#1882]
### Description

Add support for react-native-macos & react-native-windows

### Proposed Solution

launchImageLibrary opens a file picker.
Sample image picker with resize:

RCT_EXPORT_METHOD(Upload:(float)maxWidth
                  maxHeight:(float)maxHeight
                  resolver:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)
{
  dispatch_sync(dispatch_get_main_queue(), ^{

    NSMutableDictionary *output = [NSMutableDictionary dictionary];
    
    NSArray  * fileTypes = [NSArray arrayWithObjects:@"png",@"heic",@"jpeg",@"jpg",nil];
    
    // Create the File Open Dialog class.
    NSOpenPanel* openDlg = [NSOpenPanel openPanel];

    // Enable the selection of files in the dialog.
    [openDlg setCanChooseFiles:YES];

    // Filter file types
    [openDlg setAllowedFileTypes:fileTypes];
    
    // Multiple files not allowed
    [openDlg setAllowsMultipleSelection:NO];

    // Can't select a directory
    [openDlg setCanChooseDirectories:NO];

    // Display the dialog. If the OK button was pressed,
    // process the files.
    if ( [openDlg runModal] == NSModalResponseOK ) {
        // Get an array containing the full filenames of all
        // files and directories selected.
        NSArray* urls = [openDlg URLs];

        // Loop through all the files and process them.
        for(int i = 0; i < [urls count]; i++ )
        {
          
          //Include file name
          NSString * path = [urls objectAtIndex:i];
          [output setObject: path.lastPathComponent forKey: @"fileName"];
                    
          NSData *imageData = [NSData dataWithContentsOfFile:path];
          NSImage *sourceImage = [[NSImage alloc] initWithData:imageData];
          if ((maxWidth == 0) || (maxHeight == 0) || (sourceImage.size.width <= maxWidth && sourceImage.size.height <= maxHeight)) {
            NSData * fileData = [NSData dataWithContentsOfFile:path];
            NSString * base64 = [fileData base64EncodedStringWithOptions:NSDataBase64EncodingEndLineWithLineFeed];
            [output setObject: base64 forKey: @"base64"];
            NSString * fileSize = [NSString stringWithFormat:@"%lu", (unsigned long)base64.length];
            [output setObject: fileSize forKey: @"fileSize"];
          } else {
            
            CGSize newSize = CGSizeMake(sourceImage.size.width, sourceImage.size.height);
            if (maxWidth < newSize.width) {
                newSize = CGSizeMake(maxWidth, (maxWidth / newSize.width) * newSize.height);
            }
            if (maxHeight < newSize.height) {
                newSize = CGSizeMake((maxHeight / newSize.height) * newSize.width, maxHeight);
            }

            newSize.width = (int)newSize.width;
            newSize.height = (int)newSize.height;

            //Report an error if the source isn't a valid image
            if (![sourceImage isValid]){
              reject(@"ENOENT", @"ENOENT: Invalid Image", nil);
            } else {
              
              NSLog(@"New Width:  {%f}", (float)newSize.width);
              
              NSImage *smallImage = [[NSImage alloc] initWithSize: newSize];
              [smallImage lockFocus];
              [sourceImage setSize: newSize];
              [[NSGraphicsContext currentContext] setImageInterpolation:NSImageInterpolationHigh];
              [sourceImage drawAtPoint:NSZeroPoint fromRect:CGRectMake(0, 0, newSize.width, newSize.height) operation:NSCompositingOperationCopy fraction:1.0];
              [smallImage unlockFocus];

              NSData * smallData = [smallImage TIFFRepresentation];
              NSBitmapImageRep *imageRep = [NSBitmapImageRep imageRepWithData:smallData];
              NSNumber *compressionFactor = [NSNumber numberWithFloat:0.9];
              NSDictionary *imageProps = [NSDictionary dictionaryWithObject:compressionFactor
                                                       forKey:NSImageCompressionFactor];
              smallData = [imageRep representationUsingType:NSBitmapImageFileTypeJPEG properties:imageProps];
              NSString * base64 = [smallData base64EncodedStringWithOptions:NSDataBase64EncodingEndLineWithLineFeed];
              [output setObject: base64 forKey: @"base64"];
              NSString * fileSize = [NSString stringWithFormat:@"%lu", (unsigned long)base64.length];
              [output setObject: fileSize forKey: @"fileSize"];

            }

          }
          
        }
      
      resolve(output);
    } else {
      reject(@"ENOENT", @"ENOENT: no file selected", nil);
    }

  });

}

### Test Solution

How would we test & validate the feature?

**Comment by lukebrandonfarrell** [comment]
Make a PR. Closed due to lack of coherent details.
