### ISSUE TITLE
[🐛] App crashes

### ISSUE THREAD

**Issue by jbrainz** [react-native-image-picker/react-native-image-picker#1897]
### Description

When i try to select an image or use the camera, once i click on the image or select the snapshot from the camera, the app automatically crashes.

### How to repeat issue and example

- step to reproduce the issue
- ...

### Solution

What needs to be done to address this issue?

### Additional Information

- Image Picker version: [FILL THIS OUT: Be specific, filling out "latest" here is not enough.] 4.6.0
- React Native version: [FILL THIS OUT: Be specific, filling out "latest" here is not enough.]  0.65.1
- Platform: [FILL THIS OUT: iOS, Android, or both?] Android
- Development Operating System: [FILL THIS OUT: Are you developing on MacO Linux, or Windows?] Linux
- Dev tools: [FILL THIS OUT: Xcode or Android Studio version, iOS or Android SDK version, if applicable] navigation crash for Android

**Comment by alenseferovic1** [comment]
same

**Comment by jbrainz** [comment]
I used `adb logcat` to trace the log and I discovered the crash was related to a library I am using. after I removed the library everything seems to work fine

**Comment by Sargnec** [comment]
> I used `adb logcat` to trace the log and I discovered the crash was related to a library I am using. after I removed the library everything seems to work fine

Which library? I'm gettin same issue no problem on debug mode but in release it crashes immediately

`MIUIInput: [MotionEvent] publisher action=0x0, ....MainActivity (server)'
12-29 12:02:38.793  1757  2241 D MIUIInput: [MotionEvent] publisher action=0x1, ....MainActivity (server)'
12-29 12:02:38.850 19133 19182 E AndroidRuntime: Process:..., PID: 19133
12-29 12:02:38.865  1757  4691 W ActivityTaskManager:   Force finishing activity .../.MainActivity`
