### ISSUE TITLE
launchCamera crashes on Android 11[🐛] 

### ISSUE THREAD

**Issue by Tobinho07** [react-native-image-picker/react-native-image-picker#1898]
### Description

On Android 10 or lower it works. For Android 11 or higher the launchCamera Function crashes in Release Version. In Debug Version it works. No error appears, the App crashes.

Code:
 openCamera = () => {
    const options = {
      mediaType: 'photo',
      selectionLimit: imageLimit,
      maxHeight: 800,
      maxWidth: 600,
      includeBase64: true,
      includeExtra: false,
    };

    launchCamera(options, response => {

    })
  }

### How to repeat issue and example

- Package Version is 4.6.0.
- we tried to add the queries section in Android Manifest.xml, but doesnt working.
- ...

### Solution

Has anyone a solution idea? In which Manifest.xml I have to add the queries? Or other ideas?

### Additional Information

- Image Picker version: 4.6.0.
- React Native version: 2.0.1
- Platform: Android 11

**Comment by Tobinho07** [comment]
Remove the permissions in manifest XML 👍

**Comment by nikhil-tayal** [comment]
After removing permissions still not working
