### ISSUE TITLE
[🐛] wrong height and width in android real device

### ISSUE THREAD

**Issue by ansarikhurshid786** [react-native-image-picker/react-native-image-picker#1901]
### Description

This is library is perfect and growing. It is working perfectly in iOS and android simulator. 

In Android real device facing following issue: 
Capure or pick from gallery images getting wrong height and width(reverse) when i set maxHeight and maxWidth properties. 

### How to repeat issue and example

In Android real device facing following issue: 
Capure or pick from gallery images getting wrong height and width(reverse) when i set maxHeight and maxWidth properties and portrait mode image.

```
launchCamera({
            includeExtra: false,
            mediaType: "photo",
            saveToPhotos: false,
            cameraType: "back",
            quality: 1,
            maxWidth: 1000,
            maxHeight: 1500
        }, this.commonCameraGalleryRespone);
```
response:
```
height: 1000
width: 750
```
### Additional Information

- Image Picker version: 4.6.0
- React Native version: 0.63.4
- Platform: Android (real device)
- Development Operating System: MacOS Big Sur

**Comment by Levino** [comment]
I guess this is because of exif rotation of the image. I am struggling to get the exif orientation after the user has taken a photo. But  the behavior you are seeing is correct: Android devices always takes portrait pictures but adds a rotation property to the exif data.

**Comment by Komal7209** [comment]
Could this bug assigned to me , I can try solving this, and also pls do provide me with that code file link, where I can change the code

**Comment by Komal7209** [comment]
@ansarikhurshid786  Could you assign this bug to me

**Comment by ansarikhurshid786** [comment]
I don't have rights to assign you bug. could you please and update repo.

**Comment by nica0012** [comment]
Any updates here? This is also happening to me on IOS. (videos taken from phone that are selected from the gallery)

**Comment by ArkanRomanPango** [comment]
response when you try to take photo from real android device. I got width and height from asset. Made photo with horizontal and vertical orientation but got the same response
![image](https://user-images.githubusercontent.com/61008762/196689575-dad5a5a8-556e-4a31-90ba-4d6b11599fcb.png)

**Comment by alariej** [comment]
Same issue on Android (test device is a Samsung Galaxy S7). Portrait photos picked from the Gallery have the width and height mixed up. Landscape photos are OK. No problem on iOS.

**Comment by 80prozent** [comment]
i am facing the same issue.

Just tried the fix provided by @GiovanniVisentiniCasavo 

Seem to work correctly now, width and height are now correct on my samsung S9 for both Portrait and Landscape.

Would be great if someone could review the PR, so that it can be merged!

**Comment by Lizcq11** [comment]
Can someone please review the PR and aprove it, seems like there is the solution, just need to be merged

**Comment by raminious** [comment]
I'm facing this issue with the version 7.1.0 and a real device (Samsung Galaxy S21 Plus)

**Comment by dibyendu** [comment]
Adding comment with reference to PR #2259.

On Android, the returned width and height are still swapped for images containing EXIF orientation 5([ORIENTATION_TRANSPOSE](https://developer.android.com/reference/android/media/ExifInterface#ORIENTATION_TRANSPOSE)) and 7([ORIENTATION_TRANSVERSE](https://developer.android.com/reference/android/media/ExifInterface#ORIENTATION_TRANSVERSE)).

Can be verified with the following test images:
  - [Landscape_5.jpg](https://github.com/recurser/exif-orientation-examples/blob/master/Landscape_5.jpg)
  - [Landscape_7.jpg](https://github.com/recurser/exif-orientation-examples/blob/master/Landscape_7.jpg)
