### ISSUE TITLE
didCancel get true after selecting a photo ANDROID

### ISSUE THREAD

**Issue by AmirDoreh** [react-native-image-picker/react-native-image-picker#1907]
i am using `launchImageLibrary` like this  
```
launchImageLibrary({mediaType:"photo"},(res09)=>{
        console.log(res09)
    });
```

and always i get `didCancel:true` as result.

<img width="1055" alt="Screen Shot 2021-12-30 at 4 24 01 PM" src="https://user-images.githubusercontent.com/45465967/147756070-28d4620e-4dc1-4f02-9a1e-1047abf9e045.png">

**Comment by rizshivalli** [comment]
+1

**Comment by afilp** [comment]
+1 Same problem.

Using Android 11.

Is there a solution please? Thanks!

**Comment by afilp** [comment]
+1 Same problem, our app is not functional due to this bug.

Using Android 11.

@lukebrandonfarrell Is there a solution please? Thanks a lot!

**Comment by afilp** [comment]
@lukebrandonfarrell 

Similar problem here, on the other library:
https://github.com/ivpusic/react-native-image-crop-picker/issues/675

It appears that most users have problems with the Xiaomi devices. I have Android 11, Xiaomi 9T Pro.

What is so special with Xiaomi implementations?

In "Samsung Galaxy A31" it works fine, without any changes.

**Comment by marcinkolos** [comment]
+1, same problem 
using xiaomi redmi note 8t, Android 11, miui global 12.5.2

**Comment by lukebrandonfarrell** [comment]
See: https://github.com/react-native-image-picker/react-native-image-picker/pull/1928

**Comment by slolkunchik** [comment]
seems that fix helped to fix the problem on Android 11 only. The issue repeats on Android 12

**Comment by vignesh-pibase** [comment]
+1 Xiaomi redmi note 7 pro/Android-10

**Comment by Norcy** [comment]
bump
