### ISSUE TITLE
Need image croping and rotating features(Editing features).[🌟] 

### ISSUE THREAD

**Issue by champikamendis** [react-native-image-picker/react-native-image-picker#1911]
### Description

Need image croping and rotating features(Editing features). That will make this library perfect.

**Comment by kristinadarroch** [comment]
You might want to try this library instead @champikamendis https://github.com/ivpusic/react-native-image-crop-picker#readme

**Comment by champikamendis** [comment]
@kristinadarroch Thanks for your reply. But I need some more features like limiting video duration which is not in the react-native-image-crop-picker.

**Comment by lukebrandonfarrell** [comment]
https://img.ly/video-sdk
