### ISSUE TITLE
video Duration Limit is not working in iOS 14 and image editing also not working.[🐛] 

### ISSUE THREAD

**Issue by avrutisavaliya-logistic** [react-native-image-picker/react-native-image-picker#1916]
### Description

video Duration Limit is not working in iOS 14 and image editing also not working.

### How to repeat issue and example

const options = {
mediaType: 'video',
videoQuality: 'medium',
durationLimit: 30,
allowsEditing: true,
};
launchImageLibrary(options, async res => {

    });
    
    this code doesn't allow durationLimit filter.

### Additional Information

Image Picker version: 4.6.0
React Native version: 0.66.3
Platform: iOS
Development Operating System: MacOS
Dev tools: Xcode, iOS

**Comment by lukebrandonfarrell** [comment]
Please provide more details. Saying X is "not working" is not enough. If you want this to get addressed provide a video of it not working, the data you are getting returned, the image / video you are picking. Also `allowsEditing` isn't an option in this library.

**Comment by arsingh-chicmic** [comment]
Yes It's not working because the options are not managed in case of iOS 14 PHPickerViewController. Options are just managed in case of UIImageViewController.
