### ISSUE TITLE
Is there any way to get the native camera inside container in my app?

### ISSUE THREAD

**Issue by champikamendis** [react-native-image-picker/react-native-image-picker#1919]
### Discussed in https://github.com/react-native-image-picker/react-native-image-picker/discussions/1918

<div type='discussions-op-text'>

<sup>Originally posted by **champikamendis** January 12, 2022</sup>
I want to open the camera inside a component or container in the app. Can I is there any way to do that with this library?</div>

**Comment by Johan-dutoit** [comment]
Answered in dicussion
