### ISSUE TITLE
[🌟] Extract first frame of video as "preview"

### ISSUE THREAD

**Issue by pierroo** [react-native-image-picker/react-native-image-picker#1962]
### Description

Is there any way to extract the first frame of a video as an image, in order to have a preview display before clicking "play"?

**Comment by rdjuric** [comment]
You can use ffmpeg-kit to do this:

`-y -i ${destPath} -vframes 1 -an -s 720x1280 -ss ${timeToGetPosterFrom} ${posterPath}`

**Comment by lukebrandonfarrell** [comment]
We use expo video thumbnails for this: https://docs.expo.dev/versions/latest/sdk/video-thumbnails/ hope that helps
