### ISSUE TITLE
[🐛] Backend returns "File extension and mime type mismatch" but all seems to work

### ISSUE THREAD

**Issue by oguzydz** [react-native-image-picker/react-native-image-picker#1971]
### Description

When we are sending that includes a image after picking from the picker on ios. The fetch request returns me a response which has a message that "File extension and mime type mismatch". It does not do properly but one image we have received this. The image has ".PNG" mime type.   

I had a look, then tried sth on this [issue](https://github.com/react-native-image-picker/react-native-image-picker/pull/1890).
I cannot debug anything because it seems to work.

### How to repeat issue and example

- step to reproduce the issue
- ...

### Solution

What needs to be done to address this issue?

### Additional Information

- Image Picker version: "^4.7.3"
- React Native version: "0.67.1"
- Platform: "iOS"
- Development Operating System: "macOS"
- Dev tools: "iOS Side"

**Comment by lukebrandonfarrell** [comment]
Seems related to your consumer code i.e. the method you are using for sending a file. We send 1000 of images a day, and haven't encountered this error. If you provide a reproducible example I can re-open. Thanks

**Comment by oguzydz** [comment]
Hey @lukebrandonfarrell, I solved my problem with compressing file with using [react-native-compressor](https://www.npmjs.com/package/react-native-compressor) module. The module is converting all type of images to the JPG file. Then, the all files are being standardized and easily sent without any issue. Thanks!
