### ISSUE TITLE
Can anyone please tell me how to save Image in Gallery using  Image picker this is my code its not throwing any error but its also not saving Image in Gallery

### ISSUE THREAD

**Issue by malikhamza0546** [react-native-image-picker/react-native-image-picker#1975]
### Description

Can anyone please tell me how to save Image in Gallery using  Image picker this is my code its not throwing any error but its also not saving Image in Gallery
 launchCamera = () => {
    let options = {
      storageOptions: {
        skipBackup: true,
        path: 'images',
        saveToPhotos: true,
        waitUntilSaved: true,
        cameraRoll: true,
      },
    };
    ImagePicker.launchCamera(options, response => {
      console.log('Response = ', response);

      if (response.didCancel) {
        console.log('User cancelled image picker');
      } else if (response.error) {
        console.log('ImagePicker Error: ', response.error);
      } else if (response.customButton) {
        console.log('User tapped custom button: ', response.customButton);
        alert(response.customButton);
      } else {
        const source = {uri: response.uri};
        console.log('response', JSON.stringify(response));
        this.setState({
          filePath: response,
          fileData: response.data,
          fileUri: response.uri,
        });
      }
    });
  };

**Comment by lukebrandonfarrell** [comment]
You need to request `WRITE_EXTERNAL_STORAGE` on Android.

**Comment by malikhamza0546** [comment]
Thanks :)
