### ISSUE TITLE
[🐛] when i click picture in the image gallery, screen go back to previous page automatically

### ISSUE THREAD

**Issue by taehyun-kim-tenuto** [react-native-image-picker/react-native-image-picker#1979]
### Description

Explain the bug in as much detail as possible

### How to repeat issue and example

1. get permission using react-native-permissions
2. open image library
3. select picture
4. go back to previous page
 
### Solution

What needs to be done to address this issue?

### Additional Information

is this because of react-native-permissions or react-native-image-picker?

- Image Picker version: [FILL THIS OUT: Be specific, filling out "latest" here is not enough.]
- React Native version: [FILL THIS OUT: Be specific, filling out "latest" here is not enough.]
- Platform: [FILL THIS OUT: iOS, Android, or both?]
- Development Operating System: [FILL THIS OUT: Are you developing on MacOS, Linux, or Windows?]
- Dev tools: [FILL THIS OUT: Xcode or Android Studio version, iOS or Android SDK version, if applicable] navigation crash for Android

**Comment by lukebrandonfarrell** [comment]
There is not enough information to address this. It seems related to your app setup. I can reopen if you provide a reproducible example.

**Comment by SamiAltuncu** [comment]
is there any solution?
