### ISSUE TITLE
[🐛] [Android] Is QUERY_ALL_PACKAGES necessary for the package to work on Android?

### ISSUE THREAD

**Issue by jamie-phlo** [react-native-image-picker/react-native-image-picker#1990]
### Description

As per Google's [documentation](https://support.google.com/googleplay/android-developer/answer/10158779?hl=en&ref_topic=2364761#zippy=%2Cpermitted-uses-of-the-query-all-packages-permission%2Cexceptions%2Cinvalid-uses), the QUERY_ALL_PACKAGES permission will soon require a declaration provided for use.

We do not use this permission in our manifest so after searching our repo discovered a reference to this in our manifest logs

ADDED from [:react-native-image-picker] /node_modules/react-native-image-picker/android/build/intermediates/merged_manifest/debug/AndroidManifest.xml:16:17-67
uses-permission#android.permission.QUERY_ALL_PACKAGES

Is this permission required for the package to run on Android or are there alternatives that could be used instead?

### How to repeat issue and example

- Install latest version (4.8.4)
- Build for Android
- Should see android.permission.QUERY_ALL_PACKAGES in manifest-merger-debug-report.txt

### Solution

Perhaps switching for a less elevated permission would also work?

### Additional Information

- Image Picker version: 4.8.4
- React Native version: 0.66.3
- Platform: Android
- Development Operating System: MacOS
- Dev tools: Android 31

**Comment by ouraios** [comment]
Mea culpa, we found the problem is related to this library : https://github.com/proyecto26/react-native-inappbrowser/issues/363
And not to the image picker package.

The log were the following : 

```
ADDED from [:react-native-image-picker] C:\Users\myuser\app\myapp\node_modules\react-native-image-picker\android\build\intermediates\library_manifest\release\AndroidManifest.xml:17:13-19:70
   android:resource
      ADDED from [:react-native-image-picker] C:\Users\myuser\app\myapp\node_modules\react-native-image-picker\android\build\intermediates\library_manifest\release\AndroidManifest.xml:19:17-67
   android:name
      ADDED from [:react-native-image-picker] C:\Users\myuser\app\myapp\node_modules\react-native-image-picker\android\build\intermediates\library_manifest\release\AndroidManifest.xml:18:17-67
uses-permission#android.permission.QUERY_ALL_PACKAGES
ADDED from [:react-native-inappbrowser-reborn] C:\Users\myuser\app\myapp\node_modules\react-native-inappbrowser-reborn\android\build\intermediates\library_manifest\release\AndroidManifest.xml:12:5-77
   android:name
      ADDED from [:react-native-inappbrowser-reborn] C:\Users\myuser\app\myapp\node_modules\react-native-inappbrowser-reborn\android\build\intermediates\library_manifest\release\AndroidManifest.xml:12:22-74
queries
```

We though it was the upper package in this log that was the culprit but it was the lower one !

**Comment by lukebrandonfarrell** [comment]
Seems like this isn't an issue, and it related to https://github.com/proyecto26/react-native-inappbrowser/issues/363, if that isn't the case, let me know and I can re-open and investigate
