### ISSUE TITLE
I have  this issue when open the image picker and image picker not open... - "TypeError: Cannot read property 'launchCamera' of null" [🐛] 

### ISSUE THREAD

**Issue by Rananjaya** [react-native-image-picker/react-native-image-picker#2008]
I have this issue when open the image picker

TypeError: Cannot read property 'launchCamera' of null
TypeError: Cannot read property 'launchCamera' of null

  const captureImage = async (type) => {
        let options = {
          mediaType: type,
          maxWidth: 300,
          maxHeight: 550,
          quality: 1,
          videoQuality: 'low',
          durationLimit: 30, //Video max duration in seconds
          saveToPhotos: true,
        };
        let isCameraPermitted = await requestCameraPermission();
        let isStoragePermitted = await requestExternalWritePermission();
        console.log("isCameraPermitted",isCameraPermitted)
        console.log("isStoragePermitted",isStoragePermitted)
        
        if (isCameraPermitted && isStoragePermitted) {
        
            try{
                launchCamera(options, (response) => {
                    console.log('Response_= ', response,options);
             
                    
                    if (response.didCancel) {
                      alert('User cancelled camera picker');
                      return;
                    } else if (response.errorCode == 'camera_unavailable') {
                      alert('Camera not available on device');
                      return;
                    } else if (response.errorCode == 'permission') {
                      alert('Permission not satisfied');
                      return;
                    } else if (response.errorCode == 'others') {
                      alert(response.errorMessage);
                      return;
                    }
                    console.log('base64 -> ', response.base64);
                    console.log('uri -> ', response.uri);
                    console.log('width -> ', response.width);
                    console.log('height -> ', response.height);
                    console.log('fileSize -> ', response.fileSize);
                    console.log('type -> ', response.type);
                    console.log('fileName -> ', response.fileName);
                    setFilePath(response);
                  }); 
            }catch(error){
                 console.log("Error",error)
            }
     
        }
      };

**Comment by faisal3413** [comment]
I'm also facing this issue.

**Comment by Rananjaya** [comment]
anyone have solution ?

**Comment by julienR2** [comment]
Could this be because you're testing on simulators, where the camera isn't available ?

> The following hardware is not supported in Simulator:
> ...
> Camera

https://help.apple.com/simulator/mac/current/#devb0244142d

**Comment by Dsalvat596** [comment]
I believe the native modules are not linking automatically on Android.

**Comment by gurbela** [comment]
any news?

**Comment by Johan-dutoit** [comment]
Please look at the example app to ensure you setup is correct, along with usage related to the version you're using.
