### ISSUE TITLE
[🐛]  When I click picture in the image gallery, screen go back to previous page automatically

### ISSUE THREAD

**Issue by SamiAltuncu** [react-native-image-picker/react-native-image-picker#2010]
### Description

When I click picture in the image gallery, screen go back to previous page automatically

### Additional Information

- Image Picker version: ^4.8.4
- React Native version: 0.68.2
- Platform: Android
- Development Operating System: Windows

**Comment by chenjunweicc** [comment]
The same, when I click image it always returns `{"didCancel": true}`.

**Comment by Senea98** [comment]
Same here. Returns {"didCancel": true}. Device - Redmi Note 9 Pro. Camera works perfectly

**Comment by Senea98** [comment]
> The same, when I click image it always returns `{"didCancel": true}`.

Can you tell me please what device do you use? I think there is a problem with the new update on mi devices (package was working as expected before that update)

**Comment by yangga** [comment]
Same here. 
2.x.x versions are fine.
3.x.x and 4.x.x always returns `{"didCancel": true}`.

- Galaxy A9 Pro.

**Comment by fede38** [comment]
This is happening on android 12, I replicated it in A22, A03 and Galaxy Note 10+
This ONLY happens when first picking if you want to open gallery/photos, if "Always use this option" option is picked, then error doesn't happen anymore.

There's no error in console, but object always returns {"didCancel": true}

Library version is 4.10.0

**Comment by the-habu** [comment]
> This is happening on Android 12, I replicated it in A22, A03 and Galaxy Note 10+ This ONLY happens when picking if you want to open gallery/photos and keep selecting "Just this time", if "Always use this option" option is picked, then error doesn't happen anymore.
> 
> There's no error in console, but object always returns {"didCancel": true}
> 
> Library version is 4.10.0 React native version is 0.68.2

Amazing find! Actually both my Android phones behave that way. (note 8, poco f2 pro).

**Comment by nekoka** [comment]
> This is happening on Android 12, I replicated it in A22, A03 and Galaxy Note 10+ This ONLY happens when picking if you want to open gallery/photos and keep selecting "Just this time", if "Always use this option" option is picked, then error doesn't happen anymore.
> 
> There's no error in console, but object always returns {"didCancel": true}
> 
> Library version is 4.10.0 React native version is 0.68.2

Same here.
My Activity’s `android:launchMode` value is `singleInstance` in  Manifest.xml, always return {"didCancel": true}.

Change value to `singleInstancePerTask` or `singleTop` or `singleTask` , then working as expeceted.
