### ISSUE TITLE
[🐛] picker is returning opposite width and height values on IOS for .MOV (Quicktime) video from gallery

### ISSUE THREAD

**Issue by nica0012** [react-native-image-picker/react-native-image-picker#2038]
When selecting a video with type "video/quicktime" (which is an MOV file) from the gallery the width and height are flipped.

The width is what the height should be and the height is what the width should be.

Everything else seems to be fine (images are okay, screen recordings are good, other videos, etc...

I believe this may be related to video type "video/quicktime" which is an MOV file, because **MP4 videos are displaying fine.**

Version: 4.10.0
RN Version: 0.66.0

**Comment by nica0012** [comment]
My fix here was to get the orientation with react-native-video, then adjust accordingly from there. Perhaps an IOS issue?

**Comment by Futy99** [comment]
For other people facing this issue I fixed it with adjusting `getVideoDimensionsFromUrl` function as following and then patching it.

```
// ImagePickerUtils.m 

+ (CGSize)getVideoDimensionsFromUrl:(NSURL *)url {
    AVURLAsset *asset = [AVURLAsset URLAssetWithURL:url options:nil];
    NSArray *tracks = [asset tracksWithMediaType:AVMediaTypeVideo];

    if ([tracks count] > 0) {
        AVAssetTrack *track = [tracks objectAtIndex:0];
        CGSize naturalSize = track.naturalSize;
        CGAffineTransform preferredTransform = track.preferredTransform;

        if (preferredTransform.a == 0 && preferredTransform.b == 1.0 && preferredTransform.c == -1.0 && preferredTransform.d == 0) {
            // Video is in portrait mode
            return CGSizeMake(naturalSize.height, naturalSize.width);
        } else {
            // Video is in landscape mode
            return naturalSize;
        }
    }

    return CGSizeMake(0, 0);
}
```

**Comment by chocky335** [comment]
@Futy99 thnx for your solution! Just opened PR with it.

**Comment by saintyusuf** [comment]
> For other people facing this issue I fixed it with adjusting `getVideoDimensionsFromUrl` function as following and then patching it.
> 
> ```
> // ImagePickerUtils.m 
> 
> + (CGSize)getVideoDimensionsFromUrl:(NSURL *)url {
>     AVURLAsset *asset = [AVURLAsset URLAssetWithURL:url options:nil];
>     NSArray *tracks = [asset tracksWithMediaType:AVMediaTypeVideo];
> 
>     if ([tracks count] > 0) {
>         AVAssetTrack *track = [tracks objectAtIndex:0];
>         CGSize naturalSize = track.naturalSize;
>         CGAffineTransform preferredTransform = track.preferredTransform;
> 
>         if (preferredTransform.a == 0 && preferredTransform.b == 1.0 && preferredTransform.c == -1.0 && preferredTransform.d == 0) {
>             // Video is in portrait mode
>             return CGSizeMake(naturalSize.height, naturalSize.width);
>         } else {
>             // Video is in landscape mode
>             return naturalSize;
>         }
>     }
> 
>     return CGSizeMake(0, 0);
> }
> ```

you are a super hero! this should have been fixed after all this time...

**Comment by saintyusufpupas** [comment]
if the video recorded with rear cameras, this solution is working. if the video recorded with front camera, then this solution is not working.

> For other people facing this issue I fixed it with adjusting `getVideoDimensionsFromUrl` function as following and then patching it.
> 
> ```
> // ImagePickerUtils.m 
> 
> + (CGSize)getVideoDimensionsFromUrl:(NSURL *)url {
>     AVURLAsset *asset = [AVURLAsset URLAssetWithURL:url options:nil];
>     NSArray *tracks = [asset tracksWithMediaType:AVMediaTypeVideo];
> 
>     if ([tracks count] > 0) {
>         AVAssetTrack *track = [tracks objectAtIndex:0];
>         CGSize naturalSize = track.naturalSize;
>         CGAffineTransform preferredTransform = track.preferredTransform;
> 
>         if (preferredTransform.a == 0 && preferredTransform.b == 1.0 && preferredTransform.c == -1.0 && preferredTransform.d == 0) {
>             // Video is in portrait mode
>             return CGSizeMake(naturalSize.height, naturalSize.width);
>         } else {
>             // Video is in landscape mode
>             return naturalSize;
>         }
>     }
> 
>     return CGSizeMake(0, 0);
> }
> ```

**Comment by saintyusuf** [comment]
if the video recorded with rear cameras, this solution is working. if the video recorded with front camera, then this solution is not working.

> For other people facing this issue I fixed it with adjusting `getVideoDimensionsFromUrl` function as following and then patching it.
> 
> ```
> // ImagePickerUtils.m 
> 
> + (CGSize)getVideoDimensionsFromUrl:(NSURL *)url {
>     AVURLAsset *asset = [AVURLAsset URLAssetWithURL:url options:nil];
>     NSArray *tracks = [asset tracksWithMediaType:AVMediaTypeVideo];
> 
>     if ([tracks count] > 0) {
>         AVAssetTrack *track = [tracks objectAtIndex:0];
>         CGSize naturalSize = track.naturalSize;
>         CGAffineTransform preferredTransform = track.preferredTransform;
> 
>         if (preferredTransform.a == 0 && preferredTransform.b == 1.0 && preferredTransform.c == -1.0 && preferredTransform.d == 0) {
>             // Video is in portrait mode
>             return CGSizeMake(naturalSize.height, naturalSize.width);
>         } else {
>             // Video is in landscape mode
>             return naturalSize;
>         }
>     }
> 
>     return CGSizeMake(0, 0);
> }
> ```

**Comment by kyma** [comment]
Hi, this still seems to be an issue. Can the fix be merged?

**Comment by saintyoseph** [comment]
Hi, I already solved it! 

I'm using mirrored front camera. So, when I record a video or take a picture with front camera, they are going to be reversed horizontally. 

Here is the final solution to avoid this bug:

```
// ImagePickerUtils.m 

+ (CGSize)getVideoDimensionsFromUrl:(NSURL *)url {
     AVURLAsset *asset = [AVURLAsset URLAssetWithURL:url options:nil];
     NSArray *tracks = [asset tracksWithMediaType:AVMediaTypeVideo];
 
-    if ([tracks count] > 0) {
+    if (tracks.count > 0) {
         AVAssetTrack *track = [tracks objectAtIndex:0];
-        return track.naturalSize;
+        CGSize naturalSize = track.naturalSize;
+        CGAffineTransform t = track.preferredTransform;
+
+        CGFloat angleInDegrees = atan2(t.b, t.a) * (180 / M_PI);
+        angleInDegrees = fmod((angleInDegrees + 360), 360);
+
+        BOOL isPortrait = (angleInDegrees == 90 || angleInDegrees == 270);
+
+        if (isPortrait) {
+            return CGSizeMake(naturalSize.height, naturalSize.width);
+        } else {
+            return naturalSize;
+        }
     }
 
     return CGSizeMake(0, 0);
}
```
