### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'response.assets[0]')[🐛] 

### ISSUE THREAD

**Issue by bibekkotal** [react-native-image-picker/react-native-image-picker#2048]
Possible Unhandled Promise Rejection (id: 6):
TypeError: undefined is not an object (evaluating 'response.assets[0]')

 **"react-native-image-picker": "^4.10.1",
 "react-native": "0.70.1",**

TypeError: undefined is not an object (evaluating 'response.assets[0]')
_callee2$@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.kawamotors2&modulesOnly=false&runModule=true:224548:80
tryCatch@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.kawamotors2&modulesOnly=false&runModule=true:25197:23
invoke@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.kawamotors2&modulesOnly=false&runModule=true:25367:32
tryCatch@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.kawamotors2&modulesOnly=false&runModule=true:25197:23
invoke@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.kawamotors2&modulesOnly=false&runModule=true:25269:30
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.kawamotors2&modulesOnly=false&runModule=true:25279:21
tryCallOne@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.kawamotors2&modulesOnly=false&runModule=true:29919:16
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.kawamotors2&modulesOnly=false&runModule=true:30020:27
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.kawamotors2&modulesOnly=false&runModule=true:30590:26
_callTimer@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.kawamotors2&modulesOnly=false&runModule=true:30490:17
_callReactNativeMicrotasksPass@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.kawamotors2&modulesOnly=false&runModule=true:30525:17
callReactNativeMicrotasks@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.kawamotors2&modulesOnly=false&runModule=true:30733:44
__callReactNativeMicrotasks@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.kawamotors2&modulesOnly=false&runModule=true:2876:46
http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.kawamotors2&modulesOnly=false&runModule=true:2654:45
__guard@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.kawamotors2&modulesOnly=false&runModule=true:2859:15
flushedQueue@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.kawamotors2&modulesOnly=false&runModule=true:2653:21
flushedQueue@[native code]
invokeCallbackAndReturnFlushedQueue@[native code]

**Comment by Johan-dutoit** [comment]
Do you have repro steps?
