### ISSUE TITLE
[🐛] [Ios] Uploaded file size is bigger than original size

### ISSUE THREAD

**Issue by Cliff-Hsieh** [react-native-image-picker/react-native-image-picker#2059]
### Description

I selected an image using this library, and library response fileSize  is correct. But when upload to server, file size bigger 2 (even 3) times.

### How to repeat issue and example

- Select that image using this library (options: quality: 1, maxWidth and maxHeight not set)
- upload image to server
- download image from server
- compare image size with origin image

### Solution

What needs to be done to address this issue?

### Additional Information

- Image Picker version: 4.10.0
- React Native version: 0.68.5
- Platform: Ios
- Development Operating System: macOS 12.6
- Dev tools: Xcode: 13.0

**Comment by Ramaraju1992** [comment]
Same Issue here. Uploaded Image(76kb) Size is bigger than original(9kb) in `"react-native-image-picker": "^4.10.0"`.

**Comment by Johan-dutoit** [comment]
Specifically iOS images or both platforms?

**Comment by Ramaraju1992** [comment]
@Johan-dutoit we face this issue in iOS only so far

**Comment by Johan-dutoit** [comment]
Can you share an image that reproduces this?  Attached here of course (not linking out).

**Comment by hahaha28** [comment]
same

**Comment by cannyRamji** [comment]
[Johan-dutoit](https://github.com/Johan-dutoit) any update/workaround on this issue, we are facing same

**Comment by Johan-dutoit** [comment]
It seems it's something on your server that's causing the increased file size.  Especially if the library reports the correct size.

**Comment by hahaha28** [comment]
this is a bug of react native. Because react native re-render jpg image in ios. see https://github.com/facebook/react-native/pull/31457
