### ISSUE TITLE
[🐛] No callback or any error in console after taking image

### ISSUE THREAD

**Issue by satheshrgs** [react-native-image-picker/react-native-image-picker#2084]
### Description

Hi, I was using the version "react-native-image-picker": "^5.0.2" with react native 0.68.2 and it was working fine. Recently after upgrading to react native **0.71.1**, the callback is not getting called. I am running in integrated app (Integrated with existing native app). No callback triggered, tried keeping breakpoint also, it was not working

### How to repeat issue and example

- step to reproduce the issue
- Upgrade to latest version of react native
- Update the react native image picker library to latest
- Try running it from react native

### Additional Information

- Image Picker version: "^5.0.2" 
- React Native version: "0.71.1"
- Platform: Android
- Development Operating System: MacOS
- Dev tools: Android Studio Electric Eel | 2022.1.1 Patch 1

**Comment by Johan-dutoit** [comment]
Likely unrelated to the new arch changes, are you able to reproduce your issue with the example app?

**Comment by satheshrgs** [comment]
Nope, with the example app it is working fine. Will it be because of `com.android.tools.build:gradle:7.4.0`. I see the new arch changes uses 7.3.1

**Comment by satheshrgs** [comment]
@Johan-dutoit  I have figured out. I have used Singleton React Instance Manager which is not extended from ReactActivity. Native module's onActivityResult is called by ReactContext which is called by ReactInstanceManager called by React Activity.

Have added this to the Activity in which am calling React Native and it works 
```
override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)
        instanceManager?.onActivityResult(this, requestCode, resultCode, data)
    }
```
