### ISSUE TITLE
[🐛]  launchImageLibrary promise takes too long to return video result on iOS.

### ISSUE THREAD

**Issue by fixerloop** [react-native-image-picker/react-native-image-picker#2117]

**Comment by ratz6** [comment]
Picking Large Videos results in app crash also in android, and takes a lot of time on iOS (feels like app is stuck) > what's the best way to handle considering memory issues @Johan-dutoit @marcshilling @ravirajn22 

Picker version > 5.3.1
RN version > 0.70.6

So what I see is after picking the video from device, it gets copied to app storage (temp storage) which increases the size of the app also and might lead to uncertain crashes once device is close to full memory.. Any suggestions how to handle these ? Youtube's size doesn't increase after picking, wonder how they do it..

**Comment by kusche12** [comment]
I have also faced this issue for the past few months. 

The function launchImageLibrary() works relatively quick for any video < 500mb, but for larger file sizes, it can take upwards of 15min to get the function to finish running!

Has anyone found a workaround for getting large video URI's in react native?

**Comment by ratz6** [comment]
I'm trying to use UIimagepickercontroller in swift directly and it plays the recording in a second screen after picking .. and once it's picked , in the second screen there is a progress loader of the video being processed/compressed ..
so if that works with react native , will stop using RNImagePicker for the time being.. 

I see a fn **_mapVideoToAsset_** being called here > https://github1s.com/react-native-image-picker/react-native-image-picker/blob/HEAD/ios/ImagePickerManager.mm#L230
which uses some temp directory and is that causing this issue ? @Johan-dutoit @marcshilling 

Assuming the video file is first being ready from phone storage and been copied to App's temp storage which also increases the app size also and brings in a delay to process the Video so we don't the callback response until then ..

Any suggestions ?

**Comment by ratz6** [comment]
found out a config
`      phPickerConfig.preferredAssetRepresentationMode = .current
`  
doing this on my native module of PHPicker I'm able to pick even 3 GB instantly and get the response instantly. Can we add a flag to enable this in this library ?  @Johan-dutoit @marcshilling

**Comment by Johan-dutoit** [comment]
Seems like a good idea!

**Comment by ratz6** [comment]
Any workaround for picking and playing large videos on android ?
We tried directly using the File path instead of copying to app's cache but that also didn't improve the video picking time

Image Picker becomes very slow making the app unresponsive and crashes sometime or if i get result  after the wait, React native video on exoPlayer throws outOfMemory issues for large videos..

Let me know if you have any experience in this @Johan-dutoit @marcshilling @cobarx @c-moyer @freeboub

**Comment by c-moyer** [comment]
> Any workaround for picking and playing large videos on android ?
> 
> We tried directly using the File path instead of copying to app's cache but that also didn't improve the video picking time
> 
> 
> 
> Image Picker becomes very slow making the app unresponsive and crashes sometime or if i get result  after the wait, React native video on exoPlayer throws outOfMemory issues for large videos..
> 
> 
> 
> Let me know if you have any experience in this @Johan-dutoit @marcshilling @cobarx @c-moyer @freeboub 

Can you post an example of your react native code please?

**Comment by dwosk** [comment]
@Johan-dutoit @ratz6 would #2083 be what's needed here?

**Comment by ratz6** [comment]
@dwosk yes it solved the long wait time while picking videos for iOS. thanks, to point out the PR :)

**Comment by Johan-dutoit** [comment]
Changes merged.  Closing for now.

**Comment by asdolo** [comment]
> @dwosk yes it solved the long wait time while picking videos for iOS. thanks, to point out the PR :)

What value of `assetRepresentationMode` did you use to solve this issue?

**Comment by Taimoor20** [comment]
@ratz6 solution worked in my case. Thanks man, you saved my day.

**Comment by viniciusaugutisps** [comment]
Hi, for me it didn't work. Is it correct like this?
![image](https://github.com/react-native-image-picker/react-native-image-picker/assets/112719722/00c26032-b4a0-4003-9498-1897cb041c43)

**Comment by ratz6** [comment]
@viniciusaugutisps what is the file type and file size ? 

So the time comes in 2 cases : 
1) iOS 14 and above for PHPicker 
2) when we pick a large .mov video and ask it to be converted to .mp4 .. it takes time. You can modularise picking and conversion separately and show it in Ui accordingly, even though picking will be instant now. 

You can also try out with a custom swift module pasted above, that should do the work

**Comment by viniciusaugutisps** [comment]
@ratz6 the file i am trying to upload is a 270mb video of type mp4

**Comment by stomataln** [comment]
I think this issue isn't completely solved. When user picks a video which is in iCloud, it will still take a long time for the picker promise to respond.
I checked the PhPicker and seems like it's an issue on their end and they don't provide any progress and status that can help this...
I just hope there is a way for me to know when the image picker is offscreen, at least by then I know the picker is gone but still trying to fetch what user selects.

**Comment by 99-digital** [comment]
I had trouble uploading a MOV video, which took a long time to convert to MP4.

**Comment by interstates21** [comment]
The issue still exists
