### ISSUE TITLE
[🐛] Video quality is too low.

### ISSUE THREAD

**Issue by yqz0203** [react-native-image-picker/react-native-image-picker#2123]
### Description

```javascript
launchCamera({
        mediaType: 'video',
        videoQuality: 'high',
        ...option,
})
```
The video qulity is too low even though `videoQuality: 'high'` passed

### Solution

`videoQuality` seems not work at all.

### Additional Information

- Image Picker version: 5.3.1
- React Native version: 0.71.7
- Platform: ios
- Development Operating System: Macos
- Dev tools: xcode

**Comment by satyabrata-dash5** [comment]
Same from my side

**Comment by zhu-xiaowei** [comment]
This bug still exists on iOS 18
