### ISSUE TITLE
[🐛]  iOS - No callback when swiping to close camera

### ISSUE THREAD

**Issue by mattlewer** [react-native-image-picker/react-native-image-picker#2159]
### Description

No callback fired when the camera is swiped to close on iOS.

The callback is fired when the gallery is swiped to close and we get a `"didCancel": true` but this does not happen when taking an image or video and swiping to close.

### How to repeat issue and example

- Open camera iOS
- Swipe to close camera
- Callback isn't called

### Solution

The callback needs to run on gesture closes.

### Additional Information

- Image Picker version: 4.8.5
- React Native version: 0.70.8
- Platform: iOS
- Development Operating System: MacOS
- Dev tools: VSC

**Comment by JDrizzy** [comment]
The workaround to this issue appears to be setting the [option `presentationStyle` ](https://github.com/react-native-image-picker/react-native-image-picker#options) to another value that's not `pageSheet`. 

`presentationStyle: 'fullScreen'` is working as expected, and I'm not able to close the view by sliding down.
