### ISSUE TITLE
The current character read is 'i' with an int value of 105

### ISSUE THREAD

**Issue by feralxan** [react-native-image-picker/react-native-image-picker#2163]
### Description
i Got error 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Script '/Users/User/projects/helloworld/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 250
> 
> * What went wrong:
> A problem occurred evaluating script.
> > Calling `[node, /Users/User/projects/helloworld/node_modules/@react-native-community/cli/build/bin.js, config]` finished with an exception. Error message: groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object
>   
>   The current character read is 'i' with an int value of 105
>   Unable to determine the current character, it is not a string, number, array, or object
>   line number 1
>   index number 0
>   info Run CLI with --verbose flag for more details.
>   ^. Output: info Run CLI with --verbose flag for more details.
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 4s

### How to repeat issue and example

- yarn add react-native-image-picker 
- export JAVA_HOME=`/usr/libexec/java_home -v 17.0.7` && clear && rm -r node_modules yarn.lock && yarn && cd android && ./gradlew clean && cd .. && yarn run android

### Solution

What needs to be done to address this issue?

### Additional Information

- Image Picker version: ^5.6.0
- React Native version: 0.69.10
- Platform: Android
- Development Operating System: MacOS Ventura v13.4
- Dev tools: JDK 17.0.7, Gradle 7.3.3, Android Studio Flaminggo 2022.2.1 Patch 2

**Comment by marcosbarbosa031** [comment]
I'm getting the same error. Anyone has been able to solve this?

**Comment by prerakd** [comment]
I am also facing the exact same issue. Anyone able to fix this?

**Comment by DanielSuarezDev** [comment]
I am getting the same problem, help me

**Comment by DanielSuarezDev** [comment]
I could solve it you must use version 5.0.1 of image picker if your react native version is lower than 71 - I have version 0.70.6 - then clear cache and compile.

**Comment by DanielSuarezDev** [comment]
> ### Description
> i Got error
> 
> > FAILURE: Build failed with an exception.
> > 
> > * Where:
> >   Script '/Users/User/projects/helloworld/node_modules/@react-native-community/cli-platform-android/native_modules.gradle' line: 250
> > * What went wrong:
> >   A problem occurred evaluating script.
> > 
> > > Calling `[node, /Users/User/projects/helloworld/node_modules/@react-native-community/cli/build/bin.js, config]` finished with an exception. Error message: groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object
> > 
> > 
> > The current character read is 'i' with an int value of 105
> > Unable to determine the current character, it is not a string, number, array, or object
> > line number 1
> > index number 0
> > info Run CLI with --verbose flag for more details.
> > ^. Output: info Run CLI with --verbose flag for more details.
> > 
> > * Try:
> > 
> > > Run with --stacktrace option to get the stack trace.
> > > Run with --info or --debug option to get more log output.
> > > Run with --scan to get full insights.
> > 
> > 
> > 
> > * Get more help at https://help.gradle.org
> > 
> > BUILD FAILED in 4s
> 
> ### How to repeat issue and example
> * yarn add react-native-image-picker
> * export JAVA_HOME=`/usr/libexec/java_home -v 17.0.7` && clear && rm -r node_modules yarn.lock && yarn && cd android && ./gradlew clean && cd .. && yarn run android
> 
> ### Solution
> What needs to be done to address this issue?
> 
> ### Additional Information
> * Image Picker version: ^5.6.0
> * React Native version: 0.69.10
> * Platform: Android
> * Development Operating System: MacOS Ventura v13.4
> * Dev tools: JDK 17.0.7, Gradle 7.3.3, Android Studio Flaminggo 2022.2.1 Patch 2

I could solve it you must use version 5.0.1 of image picker if your react native version is lower than 71 - I have version 0.70.6 - then clear cache and compile.

**Comment by crukundo** [comment]
> problem solved after i trying downgrade to ^4.0.3

This worked for me too but there needs to be better documentation for backwards compatibility for other RN versions. There was a lot of trial and error here

**Comment by crukundo** [comment]
> > problem solved after i trying downgrade to ^4.0.3
> 
> This worked for me too with RN 0.70.6 but there needs to be better documentation for backwards compatibility for other RN versions. There was a lot of trial and error here

**Comment by anazcodesap** [comment]
i  tried downgrade to ^4.0.3 &  5.0.1 in my react native version 0.70.7.
But still the issue persists.
