### ISSUE TITLE
[🐛] app crashes when calling launchImageLibrary on android

### ISSUE THREAD

**Issue by AMINEDGE** [react-native-image-picker/react-native-image-picker#2166]
### Description

hey there, I'm using the package on android ,the issue is
the package nam in PackageList.java file is undefined.ImagePickerPackage in version 5.6.0
so I downgraded to 5.4.2 but after picking image from image library, app crashes with no error
I guess it's something with newer sdk and android versions, could someone give me a workarounnd?

my emulator android version is 11
and react native version is 0.66.4

### How to repeat issue and example

try to select image from library with the `launchImageLibrary({mediaType: 'photo'})` function

### Solution

it was okay before, not sure why this happens

### Additional Information

- Image Picker version: **5.4.0** and **5.4.2**
- React Native version: **0.66.4**
- Platform: **Android**
- Development Operating System: **macOS**
- Dev tools: **VSCode**

**Comment by IslamRustamov** [comment]
If android app crashes with no error: 
1. open Android Studio
2. open Logcat
3. select your device in Logcat
4. reproduce the error
5. find error log in Logcat

If logs in Logcat won't help you much, post error here and maybe I could help you out

**Comment by AMINEDGE** [comment]
> If android app crashes with no error:
> 
> 1. open Android Studio
> 2. open Logcat
> 3. select your device in Logcat
> 4. reproduce the error
> 5. find error log in Logcat
> 
> If logs in Logcat won't help you much, post error here and maybe I could help you out

thanks I cheked the logcat and found out it was something with onActivityResult that was modified and caused the crash, I commented the added codes and it fixed the problem

**Comment by AMINEDGE** [comment]
closed as the problem fixed

**Comment by DoVanBachTlu** [comment]
> onActivityResult

can you share how to fix it?

**Comment by Kavahardik** [comment]
Hello Everyone,

I am facing a crash issue in my React Native app when taking a photo using the camera. After capturing the photo, the app crashes when I click the right icon on the preview screen. Can anyone help me?

Details:

Dependency: react-native-image-picker
Device: Moto G52
Android Version: 13
