### ISSUE TITLE
Image rotating 90 degree in some devices and couldn't find any possible solution [🐛] 

### ISSUE THREAD

**Issue by minhaz19** [react-native-image-picker/react-native-image-picker#2186]
While taking a picture image is rotating at 90 degrees in some devices. I couldn't find any possible solution for this. I tried the already-answered issue. But couldn't fix this. While showing in local devices it looks fine. but after uploading the server it become horizontally 90 degrees angled. 

          `import * as ImagePicker from 'react-native-image-picker';
          let options = {
                  maxWidth: 1080,
                  maxHeight: 720,
                  title: 'Select Photo',
                  storageOptions: {
                    skipBackup: true,
                    path: 'images',
                  },
                  quality: 1,
                  rotation: 360,
                  isVertical: true,
                };
                ImagePicker.launchCamera(options, response => {
                  console.log(response, 'response');
                  })`
        
        the response I am getting is like that - 
        `{"assets": [{"fileName": "rn_image_picker_lib_temp_c1be1715-65a3-48ed-99b8-4fda23d949c8.jpg", "fileSize": 396495, "height": 720, "type": "image/jpeg", "uri": "file:///data/user/0/com.nagadapp/cache/rn_image_picker_lib_temp_c1be1715-65a3-48ed-99b8-4fda23d949c8.jpg", "width": 960}]}`

- Image Picker version: "5.6.0",
- React Native version: "0.71.8"
- Platform: Android
- Development Operating System: MacOS

**Comment by sauravjmedhi-softsensor** [comment]
You will have to switch the values of maxHeight and maxWidth:
` let options = {
      maxWidth: 720,
      maxHeight: 1080,
      title: 'Select Photo',
      storageOptions: {
        skipBackup: true,
        path: 'images',
      },
      quality: 1,
};`

**Comment by DheerajKhush** [comment]
Hi, you can manually resize the image using this library 
"@bam.tech/react-native-image-resizer": "^3.0.4",
 
 const orientedImage = await ImageResizer.createResizedImage(
          result.assets[0].uri,
          result.assets[0].width,
          result.assets[0].height,
          'JPEG',
          100,
          0,
          undefined,
          false,
        );

**Comment by subhankar40** [comment]
Hi,
Any way to fix this without using any other library

**Comment by shahanaahmad** [comment]
Hi
Is there any update? How can we fix this issue without using any other library?

**Comment by minhaz19** [comment]
Hello everyone, I have solved that using Expo ImageManipulator.

**Comment by aguschapuis** [comment]
To fix this i use 'react-native-image-resizer' library [https://www.npmjs.com/package/@bam.tech/react-native-image-resizer](url)

```
    launchImageLibrary()
      .then(async (response: any) => {
        if (response.assets) {
          let compressedFiles: any[] = [];
          for (let i in response.assets) {
            const image = response.assets[i];
            let result = await ImageResizer.createResizedImage(
              image.uri || '',
              image.width || 0,
              image.height || 0,
              'JPEG',
              100,
              0,
              undefined,
              false,
              {
                mode: 'contain',
                onlyScaleDown: true,
              },
            );
            const resizedImage = isIOS
              ? {
                  fileName: result.name,
                  fileSize: result.size,
                  height: result.height,
                  uri: result.uri,
                  width: result.width,
                  type: image.type,
                }
              : image;
              
              ....
        }})
```
