### ISSUE TITLE
[🐛] No property originalPath TS interface Asset

### ISSUE THREAD

**Issue by Yusk03** [react-native-image-picker/react-native-image-picker#2218]
### Description

No property _originalPath_ TS interface Asset, so if call 

`
  const result = await launchImageLibrary({
      selectionLimit: 3,
      mediaType: "mixed",
    });
   
  const originalPathFirstFile = result.assets[0].originalPath;
`

We receiving TS error 
TS2339: Property 'originalPath' does not exist on type 'Asset'.

### Solution

Need to add to _interface Asset_ property 

originalPath?: string;

### Additional Information

- Image Picker version: 7.0.0
- React Native version: 0.71.13
- Development Operating System: MacOS

**Comment by efstathiosntonas** [comment]
this is fixed on [7.0.1](https://github.com/react-native-image-picker/react-native-image-picker/releases/tag/v7.0.1)
