### ISSUE TITLE
 [🐛] Having trouble with options param in launchCamera

### ISSUE THREAD

**Issue by SitaMelark** [react-native-image-picker/react-native-image-picker#2223]
Im currently to use launchCamera but isnt congnising the options params im using, it gets this error

> Argument of type '{ mediaType: string; cameraType: string; durationLimit: number; saveToPhotos: boolean; }' is not assignable to parameter of type 'CameraOptions'.
>   Types of property 'cameraType' are incompatible.
>     Type 'string' is not assignable to type 'CameraType | undefined'.

This is my code:

```
const options = {
    mediaType: 'photo',
    cameraType: 'back',
    durationLimit: 5,
    saveToPhotos: true,
  };

  const abrirCamara = async () => {
    const results = await launchCamera(options, result => {
    });
  }
```

Also tried to import CameraType to do CameraType.back but getting following error:

> 'CameraType' only refers to a type, but is being used as a value here.

- Image Picker version: "^7.0.0",
- React Native version: "0.72.4",
- Platform: Android
- Development Operating System: Windows

**Comment by SitaMelark** [comment]
Okay i found the way to solve it adding a "as MediaType and as CameraType" (needs to be imported) to options const:

```
const options = {
    mediaType: 'photo' as MediaType,
    cameraType: 'back' as CameraType,
    durationLimit: 5,
    saveToPhotos: true,
  };
```

**Comment by Aakash359** [comment]
CameraType back is not working in Android i have tried many times do you have find any solutions for this ?

**Comment by saeidtkh** [comment]
any solution on this?
