### ISSUE TITLE
[🌟] ITMS-91053 (Apple Required Reasons APIs): Declare an approved Required Reason for `NSPrivacyAccessedAPIType`

### ISSUE THREAD

**Issue by taylorkline** [react-native-image-picker/react-native-image-picker#2288]
### Description

This picker [uses the `creationDate` from the `FileManager` class](https://github.com/search?q=repo%3Areact-native-image-picker%2Freact-native-image-picker%20creationdate&type=code), which by May 1, 2024, must be declared with an approved reason in a Privacy Manifest.

### Proposed Solution

- Create a [Privacy Manifest](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files#4284009) named `PrivacyInfo.xcprivacy` with an appropriate entry for `NSPrivacyAccessedAPIType` within the `NSPrivacyAccessedAPITypes` array.
   - Likely reason code: `3B52.1` - "Declare this reason to access the timestamps, size, or other metadata of files or directories that the user specifically granted access to, such as using a document picker view controller."
   - As a reference: expo/expo#27770

### Test Solution

Ensure that none of [the Required Reasons APIs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api) are used without a provided, Apple-approved reason.

[This iOS 17 Required Reasons scanner](https://github.com/Wooder/ios_17_required_reason_api_scanner) may be ran on the codebase.

### Additional Notes

It's possible that there are System boot time APIs or Disk space APIs that must also be declared. I did not perform an exhaustive search.

**Comment by vasuchawla** [comment]
Can confirm on the `NSPrivacyAccessedAPICategoryDiskSpace` `NSPrivacyAccessedAPICategorySystemBootTime` requirements too

**Comment by antoninleissen** [comment]
I'v got 4 requirements from apple when trying to submit : 

- `NSPrivacyAccessedAPICategorySystemBootTime`
- `NSPrivacyAccessedAPICategoryFileTimestamp`
- `NSPrivacyAccessedAPICategoryDiskSpace`
- `NSPrivacyAccessedAPICategoryUserDefaults`

**Comment by Jignesh1303** [comment]
Found potentially required reason API usage '.creationDate' in './node_modules/react-native-image-picker/ios/ImagePickerManager.m'
Line numbers: 198 263

**Comment by aliza-khu** [comment]
Has anyone found a solution to this?

> I'v got 4 requirements from apple when trying to submit :
> 
> * `NSPrivacyAccessedAPICategorySystemBootTime`
> * `NSPrivacyAccessedAPICategoryFileTimestamp`
> * `NSPrivacyAccessedAPICategoryDiskSpace`
> * `NSPrivacyAccessedAPICategoryUserDefaults`

**Comment by LCseniordev** [comment]
Are there any updates or plans for this?

Thank you!

**Comment by Baudouin-Renie** [comment]
Hi @Johan-dutoit, could you please tell us when the Privacy Manifest File will be available in the public repo? Starting tomorrow, we'll need it to release our app in the AppStore. Thanks a lot!

**Comment by aliza-khu** [comment]
@Baudouin-Renie, Same here. The issue opened on 26 March, Still, there is no update on this even though it binds with Apple's deadline and can stop releasing new app versions.

**Comment by alzalabany** [comment]
guys any updates ? can someone give us pointers how to bypass this, i must release this week and still getting warning

**Comment by aliza-khu** [comment]
@Johan-dutoit, Can you share any input on this?

**Comment by taylorkline** [comment]
You don't **need** this library to declare its privacy manifest. You can declare a valid reason in your own project's privacy manifest.
