### ISSUE TITLE
[🐛]  Manifest merger failed

### ISSUE THREAD

**Issue by AliYar-Khan** [react-native-image-picker/react-native-image-picker#2300]
### Description
Package is not working with latest react native version 0.74.1.

Explain the bug in as much detail as possible

Package requires min sdk version to 21 but react native 0.74.1 requires 23. While building the project the manifest merge failed with following error:

```
C:\Freelance\Meetkor\android\app\src\debug\AndroidManifest.xml Error:
        uses-sdk:minSdkVersion 21 cannot be smaller than version 23 declared in library [com.facebook.react:react-android:0.74.1] C:\Users\acer\.gradle\caches\transforms-3\817bf4b774b7361c46230e491303d01c\transformed\jetified-react-android-0.74.1-debug\AndroidManifest.xml as the library might be using APIs not available in 21
        Suggestion: use a compatible library with a minSdk of at most 21,
                or increase this project's minSdk version to at least 23,
                or use tools:overrideLibrary="com.facebook.react" to force usage (may lead to runtime failures)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 23 declared in library [com.facebook.react:react-android:0.74.1] C:\Users\acer\.gradle\caches\transforms-3\817bf4b774b7361c46230e491303d01c\transformed\jetified-react-android-0.74.1-debug\AndroidManifest.xml as the library might be using APIs not available in 21
        Suggestion: use a compatible library with a minSdk of at most 21,
                or increase this project's minSdk version to at least 23,
                or use tools:overrideLibrary="com.facebook.react" to force usage (may lead to runtime failures)
```
### How to repeat issue and example

- step to reproduce the issue
- create a project wiith latest react native version
- install the package
- run the project

### Solution

- probably need to increase the minsdk version in the gradle file of package

### Additional Information

- Image Picker version: "^7.1.2",
- React Native version: "0.74.1",
- Platform: Android,
- Development Operating System: Windows,
- Dev tools: Android Studio Jellyfish | 2023.3.1

**Comment by brendan1809** [comment]
In your android/build.gradle folder just modify your minSDK to 23

buildscript {
  ...
        minSdkVersion = 23
  ...
}

**Comment by AliYar-Khan** [comment]
yeah it was causing issue. I have resync with gradle files

**Comment by teckbeng-payboy** [comment]
I also facing this error on the latest version of react native and the above method doesnt work for me..

**Comment by jblemee** [comment]
Doesn't for me neither. 

But, chaging minSdkVersion on `react-native-image-picker` works !

I think this issue should be reopen and fix

**Comment by professorkolik** [comment]
same here, I have minSDK 21 for long time

```
buildscript {
    ext {
        buildToolsVersion = "34.0.0"
        minSdkVersion = 23
        compileSdkVersion = 34
        targetSdkVersion = 34

        ndkVersion = "26.1.10909125"
        kotlinVersion = '1.9.22'
   }
}
```

**Comment by Ggayane** [comment]
@professorkolik did you solve his?

**Comment by professorkolik** [comment]
@Ggayane yes, patch-package the version until the lib maintainer updates it

**Comment by LaGregance** [comment]
The library `build.gradle` should be edited like:
```
android {
  defaultConfig {
    minSdkVersion project.hasProperty('minSdkVersion') ? project.minSdkVersion : 21
    targetSdkVersion project.hasProperty('targetSdkVersion') ? project.targetSdkVersion : 33
```
