### ISSUE TITLE
[🐛] After double tapping the image picker.....pop up window appears continuously

### ISSUE THREAD

**Issue by SoumyashreeBehera** [react-native-image-picker/react-native-image-picker#2314]
### Description

After double tapping the image picker.....pop up window appears continuously

https://github.com/user-attachments/assets/63e3eeb9-3bfe-4758-a838-be0542ee1f2c

- Image Picker version: [5.6.0]
- React Native version: [0.72.0]
- Platform: [ Android]
- Development Operating System: [MacOS]

**Comment by Johan-dutoit** [comment]
This seems to be a problem related to your code.  Closing for now.
