### ISSUE TITLE
[🐛] undefined symbol

### ISSUE THREAD

**Issue by EzequielMonteleone** [react-native-image-picker/react-native-image-picker#2318]
### Description
I am receiving this error in iOS, in android work fine
 "react-native": "0.74.2"
 "react-native-image-picker": "^7.1.2"
<img width="1792" alt="Screenshot 2024-08-12 at 1 36 17 PM" src="https://github.com/user-attachments/assets/d3c05617-1132-40a7-9b39-66cc447b8cd7">

Explain the bug in as much detail as possible

### How to repeat issue and example

- step to reproduce the issue
- ...

### Solution

What needs to be done to address this issue?

### Additional Information

- Image Picker version: [FILL THIS OUT: Be specific, filling out "latest" here is not enough.]
- React Native version: [FILL THIS OUT: Be specific, filling out "latest" here is not enough.]
- Platform: [FILL THIS OUT: iOS, Android, or both?]
- Development Operating System: [FILL THIS OUT: Are you developing on MacOS, Linux, or Windows?]
- Dev tools: [FILL THIS OUT: Xcode or Android Studio version, iOS or Android SDK version, if applicable] navigation crash for Android

**Comment by jpancotti** [comment]
Same problem with react native image picker 7.1.2 on both react native 73.9 and 74.0

**Comment by EzequielMonteleone** [comment]
4.0.6 work!

**Comment by TheNoShade** [comment]
I have same issue any solution?

**Comment by jguerinet** [comment]
@TheNoShade What I have done temporarily is change it to be a static framework so that it includes everything. You can do so by adding this to your Podfile: 
```
pre_install do |installer|
    installer.pod_targets.each do |target|
      # Make some targets static as they throw errors if not
      if target.name.eql?('react-native-image-picker')
        def target.build_type;
          Pod::BuildType.static_library
        end
      end
    end
  end
```

**Comment by TheNoShade** [comment]
<img width="384" alt="Screenshot 2024-09-10 at 12 24 47 PM" src="https://github.com/user-attachments/assets/7fba9e77-d904-4600-9d8c-bc24dcbb459b">

Now facing this error

**Comment by jguerinet** [comment]
This is for another library, so you will need to see if there's a fix for that or maybe also include this library in the script above to be build as a static library.

**Comment by Johan-dutoit** [comment]
This should be fixed in newer versions, please check
