### ISSUE TITLE
[🐛] With our App's target SDK as 34 Google is asking to update this dependency to target 34

### ISSUE THREAD

**Issue by jrahil** [react-native-image-picker/react-native-image-picker#2322]
We have updated App's target SDK as 34 but now Google is asking to update this NPM dependency to target 34 which is not in our control and without this change they are not ready to approve the application for release. Please suggest about issue's solution.

**Comment by marcinkapica** [comment]
Any update about this? We are facing a similar problem.

**Comment by eisodev** [comment]
ext {
        buildToolsVersion = "34.0.0"
        minSdkVersion = 23
        compileSdkVersion = 34
        targetSdkVersion = 34
        ndkVersion = "25.1.8937393"
        firebaseMessagingVersion = "24.0.0"
        androidXCore = "1.8.0" // <-- Add this (for react-native-community/netinfo).
}

We are using the following and have this package on ^7.1.2 and is not facing the same issue as you. We did however have the app distributed before these changes. Are you launching for the first time to the store?

We do have to handle the new policy mentioned here before the deadline regarding image/video permissions added in Android 13 (SDK 33) and above: 
https://support.google.com/googleplay/android-developer/answer/14115180

**Comment by BogdanRad** [comment]
@eisodev I have same problem... I use this version   `"react-native-image-picker": "^7.1.2",`

<img width="1163" alt="image" src="https://github.com/user-attachments/assets/8793c5a0-7ec2-44f0-863b-51eda05875af">

In build gradle the compile sdk is `node_modules/react-native-image-picker/android/build.gradle:    compileSdkVersion 33`

Google error:
<img width="630" alt="image" src="https://github.com/user-attachments/assets/54257ecf-0e9b-456c-836f-634dd0e3b455">

**Comment by Johan-dutoit** [comment]
This is resolved with in 7.1.3+
