### ISSUE TITLE
[🌟] Update compileSdkVersion and targetSdkVersion to 34

### ISSUE THREAD

**Issue by BogdanRad** [react-native-image-picker/react-native-image-picker#2330]
### Description
I have received this error from google.
<img width="611" alt="image" src="https://github.com/user-attachments/assets/d90a19e1-a9b6-41bf-b685-3847e8e2748a">

Can you update the compileSdkVersion and targetSdkVersion to 34? Thank you

<img width="763" alt="image" src="https://github.com/user-attachments/assets/04ab73d6-605f-437b-9c39-b7533fc658ad">

**Comment by ivangonzalezg** [comment]
You have to update your `targetSdkVersion` in file `android/build.gradle`. I had same error days ago

**Comment by BogdanRad** [comment]
> You have to update your `targetSdkVersion` in file `android/build.gradle`. I had same error days ago

In my project the targetSdkVersion is 34..

**Comment by erie-e9** [comment]
I fixed it updating values on react-native-image-picker/android/android/build.gradle, thanks. I hope there's new package version with these fixes soon.
